cram/cram_codecs.c, cram/cram_encode.c, cram/cram_io.c, cram/rANS_static.c
CRAM supported unsorted data OK, but wasn't so well optimised.  Sometimes it deremented the reference sequence ref-counters too early, causing it to have to reload the same sequence file multiple times.  Other times it didn't decrement them early enough, causing it to fail to free memory at an appropriate time (it did on file close instead).
In the process of testing it all under valgrind, I also found and fixed a couple small but genuine memory leaks.
=> Misc CRAM fixes (mainly unsorted data)

cram/cram_decode.c, test/test_view.c
The CRAM_REQUIRED_FIELDS option can restrict which data components are decoded.  This patch fixes things with a tighter analysis of code paths.  The upshot is that flagstats should run at about double the speed (once it starts setting the appropriate options).
To experiment with the effect of this, try:
````
./test/test_view -i REQUIRED_FIELDS=0x1800 some_file.cram
````
The hex codes there relate to the definitions found in htslib/hts.h:
```
// REQUIRED_FIELDS
enum sam_fields {
SAM_QNAME = 0x00000001,
SAM_FLAG  = 0x00000002,
SAM_RNAME = 0x00000004,
SAM_POS   = 0x00000008,
SAM_MAPQ  = 0x00000010,
SAM_CIGAR = 0x00000020,
SAM_RNEXT = 0x00000040,
SAM_PNEXT = 0x00000080,
SAM_TLEN  = 0x00000100,
SAM_SEQ   = 0x00000200,
SAM_QUAL  = 0x00000400,
SAM_AUX   = 0x00000800,
SAM_RGAUX = 0x00001000,
}; …
```
=> Improved the data-series interdependence analysis

htslib/regidx.h, htslib/vcf.h, htslib/vcf_sweep.h, htslib/vcfutils.h
regidx.h
vcf_sweep.h
vcfutils.h
are missing their:
#ifdef __cplusplus
extern C {
#endif
// functions
#ifdef __cplusplus
}
#endif
Anti-name mangling measures. Also vcf.h has some of the inline functions outside the extern C bracers.
=> Add c++ name mangling protection where it's missing

cram/cram_io.c, test/test.pl
The following compile error was observed on FreeBSD 9.3:
```
gcc -g -Wall -O2 -I. -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c: In function 'paranoid_fclose':
cram/cram_io.c:1432: warning: implicit declaration of function 'fsync'
cram/cram_io.c: In function 'bgzf_open_ref':
cram/cram_io.c:1546: warning: implicit declaration of function 'access'
cram/cram_io.c:1546: error: 'R_OK' undeclared (first use in this function)
cram/cram_io.c:1546: error: (Each undeclared identifier is reported only once
cram/cram_io.c:1546: error: for each function it appears in.)
cram/cram_io.c: In function 'cram_populate_ref':
cram/cram_io.c:2052: warning: implicit declaration of function 'unlink'
cram/cram_io.c: In function 'full_path':
cram/cram_io.c:3427: warning: implicit declaration of function …
```
=> Include unistd.h & exec bash instead of /bin/bash

Makefile, cram/cram_index.c, hts.c, hts_internal.h, htslib.mk, htslib/hts.h, test/test_view.c
For .bai files on remote protocols we download the .bai locally and
use the local copy.
The previous .crai implementation just used hopen so it opened the
remote end and never cached it.  We now follow the same procedure used
in hts_idx_load for bai.
=> Fixed .crai loading of local irods:... caches.

hts.c, htslib/hts.h, regidx.c, synced_bcf_reader.c, tabix.c
This suggested pull request adds to the previous scientific notation functionality (772ba54000b33ece0b823a1e2f446f34112d286d), adding a utility function that uses strtol() when it can (so faithful accuracy is clear and obvious) or strtod() if needed (because scientific notation has been used).
=> Parsing scientific notation as integers

cram/cram_codecs.c, cram/cram_codecs.h, cram/cram_decode.c, cram/cram_io.c, cram/cram_io.h, cram/cram_structs.h, cram/rANS_static.c
These commits fix various problems found by the "american fuzzy lop" tool.  It was actually run on scram_flagstats from the Staden io_lib.  The fixes put in there are all ported to htslib in this branch.
=> CRAM fuzz testing bug fixes

sam.c
Alas, htslib calculates alignment stop positions and bin values via direct CIGAR calculations, without checking the UNMAPPED flag bit.  We did a bunch of work around this in old samtools and added `bam_endpos()` to htslib in 037860be80f321e19e78c2ac2a3b925aa9addf62, but sadly we didn't start using it in htslib at that time.
So htslib has been writing BAM files with occasionally incorrect bin fields for unmapped reads with non-`*` CIGARs (as in #206; also we were giving unmapped CIGARred POS=0 reads bin 0 rather than bin 4680), and constructing indices with similarly not quite correct bins for such reads.
See also PR samtools/samtools#391 which updates test *.bam files accordingly.
Any concerns with this change?  Please check implications for `overlap_push()` in particular.
=> Use bam_endpos() to fix bins for unmapped reads

cram/cram_codecs.c
Add missing check for enough bits to cram_beta_decode_char().
Ensure that beta.nbits is within the valid range in cram_beta_decode_init().
=> Add more checks to beta codec.

cram/cram_codecs.c, cram/cram_codecs.h
Using the beta codec with nbits=0 is valid, but confuses
cram_not_enough_bits() as it's possible to have no input data in
this case so cram_not_enough_bits thinks it has run out.
Move the calls to cram_not_enough_bits inside checks that c->beta.nbits
is non-zero to avoid the problem.
=> Fix handling of zero-bit beta codec case.

bgzf.c, cram/sam_header.c, sam.c
Stop sam_hdr_update_hashes from returning partly filled-in structures when certain header tags are missing.
Prevent sam_parse1 from reading qnames longer then 255 chars (as the length must fit in a byte).
Stop bgzf_read_block from reading uninitialised memory in its gzip handler if the file ends part way through the header.
=> Fix more crashes found while fuzz testing

Makefile, cram/cram.h, cram/cram_external.c, cram/cram_io.c, cram/cram_io.h, cram/cram_structs.h, cram/sam_header.c, htslib/cram.h
Needed for the Samtools reheader branch.
The changes fix a bug uncovered by using a function we haven't needed so far (io_lib's Scramble used it, but not Samtools).  Also exported a couple more CRAM functions.
=> Cram reheader branch

htslib/vcf.h, vcf.c
if key is NULL in bcf_hdr_remove, then remove all records of the given type
=> bcf_hdr_remove: NULL to remove all records of the given type

htslib/synced_bcf_reader.h, synced_bcf_reader.c
see samtools/bcftools#220
bcf_synced_reader will warn if the BGZF EOF marker is missing
when adding a new file. Error is added to bcf_sr_strerror so it
could be used. However, we don't fall over, just warn. We want
to be able to, say, view a BCF file while it is still being
written. Samtools also just warns when EOF missing from a BAM.
=> warn if no BGZF EOF for VCF/BCF files

vcf.c
htslib side changes to make variant type detection case
insensitive. See samtools/bcftools#285
=> vcf: Case-insensitive detection of the variant type

htsfile.c, htslib/sam.h, sam.c, test/test_view.c
Makes bam_hdr_read more resistant to broken bam files.  Fixes valgrind failures in several of my American Fuzzy Lop test cases.
=> Extra checks in bam_hdr_read.

cram/rANS_static.c
rans_compress_O1 needed about 1.25 Mb of stack for a couple of 256x256
arrays.  This caused problems on MacOS X when running in threaded mode
due to running out of per-thread stack.  The default stack size for
threads on MacOS X is 512 K.  For details, see:
https://developer.apple.com/library/mac/qa/qa1419/_index.html
This changes rans_compress_O1 and rans_uncompress_O1 to use malloc
and calloc to allocate the arrays instead of using the stack.
=> Change rANS O1 codecs to allocate large arrays on the heap.

cram/cram_decode.c, cram/cram_index.c, sam.c
Bug fix for CRAM index querying when the query sequence has zero entries in the index.  It was accessing element -1 in a NULL array.
Also fixed the code so that searching on ref id -1 (unmapped data)
works.
Fixes samtools#454
Tricky to test exhaustively, but it passes our normal tests plus anything I can dream up on the command line.
=> CRAM indexing bug fix

Makefile, test/test-vcf-hdr-in.vcf, test/test-vcf-hdr.c, test/test-vcf-hdr.out, vcf.c
Making the function bcf_header_parse ignore trailing spaces fixes issue #248.
A test file is included, but I haven't been able to integrate it with the rest of the VCF test suite (test/test.pl). For some reason, it won't copy the input file into the temporary folder.
=> Function bcf_hdr_parse_line now ignores trailing spaces

htslib/vcf.h, vcf.c
Gaps in IDX blocks were causing incorrect tags on output.
Fixes samtools/bcftools#317.
=> Fixed for handling of BCF string dictionaries

htslib/vcf.h, vcf.c
* const has been removed... is that okay?
* Fixes samtools/bcftools#332
=> bcf_write: sync dirty header before writing

Makefile, cram/sam_header.c, cram/sam_header.h, htslib/vcfutils.h, vcfutils.c
* new bcf_remove_alleles_set function to the new kbitset.h api to indicated alleles
to be removed. This avoids overflowing the old integer bitmask in bcf_remove_alleles
when there are more than 31 alleles
* bcf_remove_alleles updated to use the new bcf_remove_alleles_set
* Fixes samtools/bcftools#319
=> vcfutils: add bcf_remove_alleles_set

hfile_libcurl.c
Handles temporary credentials specified in the URL (as `s3://ID:SECRET:TOKEN@bucket/...`), via $AWS_SESSION_TOKEN, or as specified in a configuration file.
Reads credentials from the URL, via the usual environment variables, from [~/.aws/credentials](https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs), from [~/.s3cfg](http://s3tools.org/kb/item14.htm), or from [~/.awssecret](http://timkay.com/aws/).
=> Support config files and temporary credentials for S3 URLs

cram/cram_encode.c, cram/cram_structs.h, test/xx#repeated.sam
Passes all the tests and doesn't seem to change output in normal behaviour, but PR for review if anyone wishes prior to merge.
If we have a complex template where more than 2 reads exist and we
have valid pnext/tlen fields between each successive pairs, the code
was erroneously removing the statistics for the tlen(etc) values
multiple times instead of just once.  Test data included.
=> Fixed a CRAM encoding assertion failure on repeated templates.

cram/sam_header.c
A sort order of "unknown" is not an unknown sort order, it's a perfectly reasonable sort order defined in the BAM specification. This change will avoid unnecessary warnings in our log files when using samtools.
=> Avoid unnecessary warning on unknown sort order

htslib/vcf.h
Add a comment to vcf_parse() to document that the input line must not end with a newline character.
=> vcf.h:vcf_parse() add documentation

vcf.c
Change BCF_HL_FMT to BCF_DT_ID when looking up GL header id.
The GL check can't have worked correctly, and using the wrong dictionary
caused odd things to happen if you used GL as a sample name.
=> Correct constant passed to bcf_hdr_id2int in bcf_hdr_check_sanity.

cram/cram_io.c
On filesystems that don't support exclusive fopen, it was possible
totrigger a race condition causing the downloaded data to become
corrupt.  We now randomise the filenames to make this much less
likely.
The data is also md5sumed before writing.  (Logically we'd check after
writing, but if we've hit an NFS issue with multiple clients writing
to the same file then we're unlikely to detect that anyway as each
system will just read back what it wrote from its own local cache.)
=> Populating CRAM cache is now much less likely to have a race condition

vcf.c
This test vcf file:
```
##fileformat=VCF
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	A	B
1	0	.	.	.	.	.	.	x:y:z	.:show_me_some_random_memory:.	.:
```
can make hts_file -c write out some uninitialized memory.  This is because  vcf_parse_format skips filling out end of vector values if the last sample record on a line finishes early without including all formats.  Fix by moving the code that fills end of vector values outside the loop that reads a sample record, to ensure it always gets run.
=> Ensure vcf_parse_format always fills out end of vector values.

cram/cram_stats.c, hfile.c, hts.c, sam.c
Previously the cram_stats_encoding() function was written to
roughly minimise the storage requirements.  As such it used HUFFMAN or
BETA codec for data low-volume series and EXTERNAL for larger ones.
This avoided any block overheads.  (Actually there was a lot of
additional commented-out code to deal with subexponential codec too.)
However this comes at the price that (more or less) any field may
potentially be mixed with with any other field in the CORE block.
Checking a random file I see this is so:
$ cram_dump /tmp/_2.cram | egrep 'HUFFMAN|BETA'|less
RL =>          HUFFMAN {1, 100, 1, 0}
BA =>          HUFFMAN {4, 65, 67, 71, 84, 4, 1, 2, 3, 3}
DL =>          HUFFMAN {4, 1, 2, 3, 4, 4, 1, 2, 3, 3}
RG =>          HUFFMAN {1, 0, 1, 0}
RI =>          HUFFMAN {1, 0, 1, 0}
...
Huffman …
=> Removed use of CRAM "CORE" block while encoding.

htslib/vcf.h, vcf.c
`bcf_hdr_read()` and `bcf_hdr_write()` need to consider BCF's `l_text` (header text length) as unsigned, so that huge headers can be handled.
Fixes samtools/samtools#567.
=> Add bcf_hdr_format(), handle BCF headers larger than 2GiB

hts.c
When searching for HTS_IDX_NOCOOR reads, hts_itr_query would return the
wrong result for indexes where the last reference was unused.  Such
references have no entries in the binning index so it it not possible
to return an end offset for them.  Add a loop so that hts_itr_query finds
the last reference with mapped reads.  If found, its ending offset is
returned as the location where the no-coor reads start.
Fixes samtools/samtools#568
=> Make hts_itr_query find no-coor reads when last reference is unused.

htslib/bgzf.h, htslib/cram.h, htslib/faidx.h, htslib/hfile.h, htslib/hts.h, htslib/regidx.h, htslib/sam.h, htslib/synced_bcf_reader.h, htslib/tbx.h, htslib/vcf.h, htslib/vcf_sweep.h, htslib/vcfutils.h
We will soon start using [doxygen](http://doxygen.org/) to generate API documentation web pages.  However doxygen only generates documentation for items within header files that have `@file` annotations, so we need to add those to each of _htslib/*.h_ that we want to appear in the API docs.  Here are a couple of styles for adding them — each has various pros and cons.
Since it is Friday, here is a poll on a topic I'm sure we all care about deeply!
Please add a :+1: reaction on one of the comments below to vote for the one you think is preferable…
=> Example doxygen @file annotations [POLL]

cram/cram_encode.c, cram/cram_encode.h, cram/cram_io.c, cram/cram_structs.h, hts.c, htslib/hts.h
Added support for CRAM_OPT_LOSSY_NAMES option and "lossy_names" in the -O command line options.
This throws away read-names where all reads for the same template occur in the same CRAM slice.
=> Cram lossy name compression

cram/cram_external.c, htslib/cram.h
This permits explicit sharing of references between file descriptors.
=> Expose cram_get_refs() function to return the opaque refs_t data type.

htslib/tbx.h, htslib/vcf.h, vcf.c
This is to allow VCF/BCF indexing via streamed input and is a
pre-requisite for adressing samtools/bcftools#373
* distinguish negative return values as in sam_index_build2()
* expose tbx_index() via tbx.h
* add documentation for bcf_index_build() and bcf_index_build2()
=> allow bcf_index_build2 to index both bcf and vcf

sam.c
This fixes a nasty (and embarrassing) bug, whereby pointer 's' is no longer valid iff b->m_data has to be reallocced.
=> Fixes bug in bam_aux_update_str()

cram/cram_encode.c
This was previously causing the slice reference md5sum to crash.
Fixes samtools/samtools#600, but note this perhaps isn't a perfect
fix.  The test data for that issue is broken, but ideally we should be
able to reproduce the broken input after round-tripping.  Currently we
lose track of MD/NM tags.
However making cram totally lossless even when faced with invalid data
is an issue for another date.
NOTE: the CRAM file produced here cannot be decoded by htsjdk (however it also couldn't turn the test BAM into CRAM either).  Perhaps it's just a case of garbage in, garbage out, but fixing a crash is nonetheless important.
=> Protect against sequences starting beyond reference end.

htslib/sam.h, probaln.c, sam.c
This involves two main components.
1) Speeding up the probaln_glocal function to do less malloc/freeing, have better memory layout and to avoid so much cache pollution. (It still needs a lot of work there though.)
2) To add a callback mechanism to mpileup, permitting the caller to attach arbitrary additional information to pileup structs.  ABI breaking.
This is needed by my PR to the bcftools feature/mpileup branch.
=> Mpileup speedup

test/formatmissing-out.vcf, test/formatmissing.vcf, test/test.pl, vcf.c
For example, this is a valid VCF line
```
1	300	.	C	A	.	PASS	.	.	.	.
```
Previously this would emit a warning saying:
`[W::vcf_parse_format] FORMAT '.' is not defined in the header, assuming Type=String`
and internally we would have a new `FORMAT=.` tag.
This will now be recognised as missing.
htslib already writes out such lines when  `n_fmt == 0` and `n_samples > 0`
Mixing missing and non-missing FORMAT tags (e.g. `.:GT` or `GT:.:AD`) is not allowed.
See conversation in #409
=> Handle VCF lines with missing `FORMAT=.`

vcf.c
This is to prevent issues like https://github.com/samtools/bcftools/issues/428
=> More thorough INFO cleaning

hts.c
Prevents a warning message being written to stderr from calls to  hts_idx_load2 when the target index is younger than the read file.
=> Suppress index date warning when hts_verbose == 0

cram/cram_decode.c, cram/rANS_byte.h, cram/rANS_static.c
Fixes a couple of problems detected during American Fuzzy Lop testing:
* cram_decode_estimate_sizes() would segfault if either the SQ or RN data series codecs were not defined.
* The rANS uncompressors could try to read beyond the end of the input data, for malformed inputs.
=> Cram bug fixes

cram/cram_codecs.c, cram/cram_decode.c, cram/cram_io.c, htslib/sam.h
Prevent out-of-bounds array accesses and dubious memory allocations.
Test cases found with American Fuzzy Lop and Valgrind.
=> Various memory-related bug fixes

hts.c, htslib/hts.h
The hts_expand() and hts_expand0() macros don't return a value, and will
set (ptr) to NULL if realloc fails.  This could lead to segmentation faults
if callers don't check the value of (ptr).  As few if any do, and some
callers are in external packages, the best solution is to make the
hts_expand macros print an error message and call exit(1).
It's not ideal behaviour for library code, but fixing this in any other
way is just too hard.
This implementation removes the assumption that (m) and (n) are of type
int.  It should work with any integer type no bigger than size_t.
=> Make hts_expand handle realloc failure a bit better.

htslib/kstring.h, kstring.c, sam.c, vcf.c
Update to PR #395 from @jkbonfield to speed up `ksprintf(s,"%g",val)`. See discussion there.
Squashes those commits, reverts the addition of trailing `.` for whole floating point numbers. Also fixes a small bug for negative exponential values.
=> Add a kputd for %g specialisation

.gitignore, Makefile, NEWS, cram/cram_encode.c, cram/cram_io.c, cram/cram_io.h, cram/cram_samtools.c, cram/os.h, hts.c, htslib.mk, htslib/hts_defs.h, htslib/hts_endian.h, htslib/sam.h, htslib/vcf.h, htslib_vars.mk, md5.c, sam.c, test/hts_endian.c, test/sam.c, test/test.pl, vcf.c
Undefined behaviour includes:
* Illegal shifts
* Calls to memcpy(ptr, NULL, 0)
* Unaligned access
A new header file htslib/hts_endian.h is added.  This includes functions to read and write little-endian
values, which may be unaligned, in a portable way.  Some endian-specific code is rewritten to be
endian-neutral, but with optional optimisations for little-endian platforms that allow unaligned access.
Behaviour on big-endian systems is also changed, notably bam auxiliary data is now stored in little-endian order instead of being byte-swapped.  This means code accessing aux data needs to byte swap integer and float values on big-endian platforms.  To assist this, more bam_aux functions are added.  These include bam_auxB_len(), bam_auxB2i() and bam_auxB2f() for accessing array elements. …
=> Fix undefined behaviour and improve endian-related behaviour

knetfile.c
The <sys/select.h> header is needed for calling select() on some
non-Linux Unices. Unbreaks build on OpenBSD.
=> Include <sys/select.h>

Makefile, bgzf.c, htslib/thread_pool.h, test/thrash_threads1.c, test/thrash_threads2.c, test/thrash_threads3.c, test/thrash_threads4.c, test/thrash_threads5.c, test/thrash_threads6.c, thread_pool.c
This replaces PR #462 with a revised method suggested by @daviesrob.
The synchronisation between main and reader is now done within thread
pool using half-shutdown of the process-queue via reference counting.
Also fixed some memory leaks during shutdowns.
=> Further thread pool fixes.

htslib/sam.h, sam.c
See #469.  This removes the call to `abort()` in `skip_aux()` and makes `bam_aux_get()` and `bam_aux_del()` return an error status if the input bam record has broken aux data.  `bam_aux_get()` has to set `errno` so that the caller can tell the difference between a missing aux tag and a corrupted record.
sam_format1() gets a small addition to catch invalid aux types.  It also now prints an error message if hts_verbose is set for any aux data related failure, and an ancient pointer arithmetic related FIXME is fixed.
Thanks to @TracyBallinger and @ctsa for the original test case.
=> Make bam_aux_get(), bam_aux_del(), sam_format1() return error for broken aux data

NEWS, hts.c, htslib/hts.h, tbx.c
Index metadata stored in an hts_idx_t struct was byte-swapped for
tbi indicies but not for csi.  Make them both the same by leaving the
data in little-endian order, and make tbx_index_load2() access the
data in an endian-neutral manner.
Functions hts_idx_get_meta() and hts_idx_set_meta() are changed to
treat the metadata length as an unsigned value (uint32_t) to match
the integer type that is used to store the length in the hts_idx_t
struct.  hts_idx_set_meta() is also changed to return an int
so callers can detect if it ran out of memory.
hts_idx_load_local() and hts_idx_set_meta() now ensure that the stored
meta-data is always followed by a NUL.  This is to prevent tbx_index_load2()
from running off the end of the metadata if there is an unterminated
string in the list of sequence …
=> Fix endianness, integer type and memory safety issues in index metadata

htslib/vcf.h, vcf.c
Alternatively, the function could return VCF_OTHER instead, which would not require changes in `vcf.h`
=> Make bcf_set_variant_type() aware of breakends

faidx.c
Make `faidx_read()` use `isspace()` instead of `isgraph()` to find the end of the sequence name.  This fixes a problem uncovered when someone used a UTF-8 encoded ligature in a fasta file sequence name.  Searching for such a name requires the use of the exact binary representation in the original fasta file (we don't try anything clever like normalising UTF-8), but is at least now possible.  Fixes #521.
Improve fai_fetch() and faidx_fetch_seq().  Fixes #522 where a non-existent sequence name followed
by a colon would be incorrectly returned as an empty sequence.  This also fixes a few other problems with region parsing, adds more error checking and removes some code duplication.
=> Faidx bug fixes

vcf.c
Second commit from #519, rebased with extra commits to fix a couple of issues.
- Make `bcf_hdr_parse()` try to include more header records when it encounters a read error.
- Add checks on the return value of `bcf_hdr_parse()`.
- Ensure data structures are cleaned up if `bcf_hdr_parse()` fails.
- Stop `bcf_hdr_parse_line()` from going on to the next line when it doesn't find '='.
- Ensure `bcf_hdr_parse_line()` sets `*len` to the correct number of bytes to get to the next line.
=> Improved VCF/BCF header parsing

sam.c
Although the htslib code checks things like headers starting with @,
nl vs cr-nl, nul termination, etc, not all BAM implementations are as
friendly.  The specification doesn't state for example that we must
have nl and not cr-nl for the header in BAM.
This code sanitises on input, also fixing samtools/samtools#661 in the
process.
=> Trivial SAM header sanitising.

configure.ac
This was always the intention for the C99 tidyup, but sadly forgotten
about causing compilation errors of thread_pool.c for Centos/RHEL 5
and SUSE/SLES 11 systems.
Fixes samtools/bcftools#610
Fixes samtools/bcftools#611
=> Added a PTHREAD_MUTEX_RECURSIVE check.

vcf.c
Fixes #537
Also "fixed" the parser to prevent this from happening in the first
place, but poorly as there is no way to return an error from
bcf_hdr_register_hrec. (see also #246)
The following minimal VCF triggered this crash. Note "dype".
```
##fileformat=VCFv4.1
##INFO=<ID=S,Number=1,dype=String,Description="blah">
##INFO=<ID=I,Number=1,Type=Integer,Description="blah">
##contig=<ID=chr1,length=249250621,assembly=b37>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr1    10327   .       T       C       .       .       S=foo;I=12345
chr1    10327   .       T       C       .       .       S=foo;I=12345
```
=> Fix buffer overrun in vcf_format.

htslib/sam.h, sam.c, vcf.c
Trivial fixes for #538 and #541 involving SAM fuzz testing bugs.  (Both minor decode issues rather than security concerns.)
=> SAM fuzz testing fixes. (Fix for 538)

cram/cram_codecs.c
The decoders currently assume that they are writing to an integer array,
and neither htslib nor htsjdk appear to write anything other than
integers using these codecs.  So it should be reasonable to restrict
them to use with only integer data streams.
Fixes #548 (Stack buffer overflows in cram_gamma_decode and
cram_subexp_decode)
=> Limit subexp and gamma decoders to integer cram_external_type

Makefile, bgzf.c, cram/cram_io.h, hfile.c, hfile_internal.h, hts.c, htslib/hts.h
Note: this exposes new API bgzf_hfile(), cram_hfile() and hts_set_blksize()
functions.
They could all be internal, but I don't know if there is an official
htslib way of having inter-file function exports that don't
externalise to the library.  Just comments to say as much?
It is unknown whether hts_set_blksize() works on vcf/bcf (there is no
test_view equivalent so I didn't bother trying), but there is also no
equivalent -I / -O options for vcf/bcf either so it doesn't matter for
now.
Fixes #216
=> Adds HTS_OPT_BLOCK_SIZE support for SAM/BAM/CRAM.

bcf_sr_sort.c, cram/cram_codecs.c, cram/cram_decode.c, cram/cram_encode.c, cram/cram_external.c, cram/cram_index.c, cram/cram_io.c, cram/cram_stats.c, cram/cram_structs.h, cram/mFILE.c, cram/sam_header.c, hts.c, htslib/hts.h, realn.c, sam.c
Replaced fprintf(stderr, ...) calls with hts_log_... calls in the CRAM code. This pull request is part of a series that aims to solve #403 .
Most of the changes are search-and-replace, but there is one change that I'd like to bring up for discussion: I've removed the CRAM-specific verbosity flag. No use with a separate flag for that part of the code, right? And it's not part of the public API. (In case there are actually good reasons to keep it, those changes are isolated in a separate commit and so can be easily reversed.)
I've also put #ifdefs around debugging functions in a few cases. The reason is that I don't think the implementations should be there when the invocations are commented out. After the change, both the implementation and invocation are enabled or disabled by a single …
=> Logging improvements 4

htslib/sam.h
For `sam_read1`, it appears that a return value of -1 indicates a non-erroneous end-of-file/stream, and other negative values indicate various errors, but there are no docs on this return value in `htslib/sam.h`.
If this function is part of the stable api, could this interface be documented? I submitted the following line as a minimum starting point.
=> Add return value documentation to sam_read1()

bgzf.c, htslib/bgzf.h
Note this normally is an insignificant overhead, but if decoding
uncompressed BAMs it becomes dominant.  Eg perf on samtools flagstat
shows:
70.47%  samtools.tmp  libz.so.1.2.8       [.] crc32
8.91%  samtools.tmp  [kernel.kallsyms]   [k] 0xffffffff8104f45a
8.40%  samtools.tmp  libc-2.19.so        [.] __memcpy_sse2_unaligned
4.80%  samtools.tmp  samtools.tmp        [.] bgzf_read
3.95%  samtools.tmp  samtools.tmp        [.] bam_read1
One solution is either to have an option to not check (I don't like
this), or to replace the default zlib crc algorithm with a much more
performant alternative.  See #467 for discussion.  Libdeflate's SSE
crc is around 11x faster, meaning this overhead would be around 20%
instead.
Perhaps it's time we had a build option linking against libdeflate
anyway as it's …
=> Added BGZF CRC32 checking.  Fixes #402.

hts.c, hts_internal.h, htslib/hts.h, htslib/hts_defs.h, multipart.c
PR samtools/hts-specs#230 updates the htsget specification so that all htsget JSON starts with a protocol identifier.  This is implemented by wrapping the payload inside a JSON object with the single key "htsget".  Update multipart.c and hts_detect_format() in hts.c to understand the revised format.
As the protocol now has an official name, change some mentions of 'json' to 'htsget'.  One of these is in the htsExactFormat enumerated type, which is in htslib/hts.h.  This is left in place for API compatibility, but marked as deprecated (if using a compiler that supports this).
=> Update multipart to work with revised htsget specification

hts.c
Plus a few other changes to make it and hts_idx_getfn() work a bit more sensibly.  For example, the latter will now notice if the input file name doesn't have a '.' in it when trying to remove the suffix.
Fixes issue #580
=> Make hts_test_and_fetch check for fwrite() errors

hfile_internal.h, hfile_libcurl.c, hfile_s3.c
Three commits here.
The first fixes a problem where connections would be dropped in `libcurl_seek()` if the server did not support byte ranges.  This is a problem for the BAM EOF check, which expects to be able to continue reading if the seek fails.  The update makes `libcurl_seek()` open a new connection using the byte range before closing the original.  If it works, the old connection is closed and replaced with the new one.  If it fails, the new connection is closed and errno is set to ESPIPE so that the caller can choose to continue in streaming mode.
The second allows HTTP headers to be set using a callback function.  It's called at file open and by `libcurl_seek()` when it opens a new connection.  It allows headers to be changed at seek time if necessary, for example if a stale …
=> libcurl_seek improvements

cram/cram_codecs.c, cram/cram_io.c
Fixes #593
The second case in the issue above shows a bug in how huffman table entries are sorted which could be triggered by valid data.  If two integer values are more than 2^32 apart (say, 2000000000 and -20000000000) then they would compare and sort incorrectly.  As the same comparison is used when reading and writing, it's possible that HTSlib could create data that was invalid, but it could read itself.  Hopefully we haven't written anything like that as we tend to avoid using the Huffman codec.  I haven't yet been able to work out if htsjdk can produce the same incorrect output (it uses the same subtraction trick when making the comparison).
In the third case, a RAW block had different compressed and uncompressed sizes.  This enforces the rule (in the specification) that they …
=> Fix cram integer overflows

hfile_libcurl.c
Allow overriding the cURL CA bundle via the CURL_CA_BUNDLE environment
variable. This allows users to specify a new CA root certificate to use
when communicating with a host (such as an htsget server using a
self-signed certificate).
=> Allow overriding the cURL CA bundle path

htslib/khash.h
- KHASH_SET_INIT_INT annotations is correct, while KHASH_SET_INIT_INT64 is not. KHASH_SET_INIT_INT64 should be hash set, not map, just as KHASH_SET_INIT_INT is.
```
/*! @abstract     Instantiate a **hash set** containing integer keys */
#define KHASH_SET_INIT_INT(name)
/*! @abstract     Instantiate a **hash map** containing integer keys*/
#define KHASH_MAP_INIT_INT(name, khval_t)
/*! @abstract     Instantiate a **hash map** containing 64-bit integer keys*/
#define KHASH_SET_INIT_INT64(name)
```
=> Fix annotations: hash [map] => hash [set]

hfile_libcurl.c, multipart.c
Allows you to set `HTS_AUTH_LOCATION` to point to a file or URL where HTSlib can find an OAUTH2 Bearer token (see [RFC 6750](https://tools.ietf.org/html/rfc6750).  `%h` in `HTS_AUTH_LOCATION` will be substituted with the host (and currently port) part of the URL, so that tokens can be sent to specific sites.
The file can either contain just the token (e.g. `mF_9.B5f-4.1JqM`) or an OAUTH2 access token response:
```JSON
{
"access_token":"mF_9.B5f-4.1JqM",
"token_type":"Bearer",
"expires_in":3600,
"refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA"
}
```
`HTS_AUTH_LOCATION` can be a URL as well as file path.  For URLs, care is taken to avoid trying to read an access token for them (otherwise infinite recursion could result).  Allowing URLs enables a way of implementing authentication agents that handle …
=> Add Bearer token support to hfile_libcurl (for htsget)

hfile.c
This makes it easier to use the extra parameters when we don't know exactly which handler will be used.  It also makes file:// URLs work the same way as simply specifying the file name.
=> Make hfile handlers without vopen ignore extra hopen parameters

errmod.c
using the expansion:
log(a + c) = log(a) + log(1 + c/a)
fixes calculation of PLs on ARM and POWER
see: https://github.com/samtools/bcftools/issues/702
=> Calculate sum in logarithmic form

hfile_libcurl.c
If the env var was unset, passing NULL on to curl_easy_setopt here
clobbered access to the system certificates, evidenced by libcurl
error CURLE_SSL_CACERT on access to public BAM files on GCS.
=> Don't override the cURL CURLOPT_CAINFO option if env var is unset.

hts.c, htslib/hts.h, test/test_view.c
Simplifies the call to `hts_itr_multi_destroy` by removing the second argument, region count, which was already contained in the iterator.
=> hts_itr_multi_destroy with one argument

configure.ac, m4/hts_prog_cc_warnings.m4
The m4 file here is an evolution of the one from the Staden io_lib.  In tests it works better that the equivalent one in autoconf_archive, which seems to be broken for some compilers.  This one first tries to identify the compiler and then attempts to run it with the option, so should be reasonably safe.
Also included is an option to enable -Werror or equivalent.  Currently it only works on GCC compatible compilers and Sun Studio, as they're the ones I've been able to test so far.  Setting -Werror can break some tests (notably AC_SEARCH_LIBS), so this option is only applied to CFLAGS towards the end of the configure script.
Default settings are to enable warnings, but not -Werror.
=> Add configure options to enable warnings and optionally Werror

cram/cram_decode.c, cram/cram_samtools.c
1. bam_construct_seq returned 0 instead of number of bytes written to
the bam_seq_t struct.  This in turn bubbled up to cram_get_seq
returning only the number of auxiliary bytes written to instead of the
total record size.
Under specific circumstances (no RG tag, no NM/MD requested, and no
other aux fields), this meant cram_get_bam_seq returned 0 on a
successful read.  This in turn was interpreted as EOF by the iterator.
Given bam_read1 returns the size of the bam structure it feels
appropriate for the cram version to mirror it, as originally intended.
2. If we use the required_fields option to exclude sequence data, then
we also exclude loading of the reference (which is a useful
optimisation).  However this then also meant the cram_decode_seq
function wasn't correctly modifying the …
=> Fixed return value of cram_get_bam_seq and fixed a bug in required_fields option.

kstring.c
In a previous implementation of `kstrtok`, the LSB of `tab[0]` was used as a flag to indicate that the tokenization process had ended. However, a new dedicated flag (`finished`) was later added to the `aux` structure, but the change to the new flag hasn't been completely carried out.
=> Fixes the finished flag usage.

hfile_libcurl.c
The BGZF cache calls `hseek()` whenever `load_block_from_cache()` [returns a block from the cache](https://github.com/samtools/htslib/blob/da27bfd89a/bgzf.c#L548).  This can lead to a lot of seeks happening without any actual reads between them.  On real files this doesn't matter very much, but with hfile_libcurl it results in lots of pointless HTTP requests for data that is never used.  Even worse, the problem gets bigger if the cache size in increased as a seek happens on every cache hit.
This patch fixes the problem by making `libcurl_seek()` perform the full process the first time it is called on each file handle (to test that seeking actually works), then for all following calls simply record the location where the next read should start and delay the actual work until …
=> hfile_libcurl seek improvements

bgzf.c, htslib/bgzf.h
An alternative to https://github.com/samtools/htslib/pull/620 for consideration.
Difference here is random removal (via round-robin approach) vs removal of oldest object.  Pros and cons of each.  (Thanks @ramyala for spotting it was bugged and raising the other PR implementation.)
=> Bug fix to random bgzf cache removal.

cram/cram_decode.c, sam.c
In the loop that skips over containers in range queries, check that the range and container references are the same before comparing the start and end positions. Also check that range.refid is not -1 (unmapped), as in that case the start and end positions may not be valid.
Ensure that fd->eof is set when making range requests and the container found does not have the desired reference id.
Fixes #651
Also avoid accessing the bam record if cram_get_bam_seq() fails.  It's not likely to contain valid data. Spotted when looking into the problem above.  Instances fixed in cram_readrec(), sam_bam_cram_readrec() and sam_read1().
=> Fix end-of-range check & setting fd->eof in cram_next_slice()

cram/cram_decode.c
In cramtools it appears that the "N" cigar op doesn't update the end position for reference extents, meaning a long N can cause the slice header to be invalid.  If we only load the part of the reference listed in the header, we can then read beyond the end of this buffer.
This works around the bug reported here https://github.com/enasequence/cramtools/issues/65.
Note this bug only happened when using the standard Makefile (ie not ./configure).  This disables use of mmap, which avoided the problem by having the entire reference in memory instead of the requested region.  Also use of multi-threading caused the code to fetch the entire reference, also working around the issue.
Trivial example SAM file to trigger the issue:
```
@HD	VN:1.5	SO:coordinate
@SQ	SN:18	LN:78077248 …
```
=> Fixes crashes caused when decoding some cramtools produced CRAM files.

cram/rANS_static.c
In rans_uncompress_O0() and rans_uncompress_O1(), change in_sz and
out_sz to unsigned integers.  Prevents attempts to allocate
negative-size memory if out_sz bit 31 gets set.
In rans_uncompress_O1(), zero column 0 of `syms` as well as row 0
to prevent uninitialized memory reads on invalid input.  This
should be sufficient protection.  The decode array is calloc'd
so any invalid rANS state will decode to 0 and the next `syms`
look-up will go to column 0 as a result.  Any look-up in the
decode array that does not return 0 will have a corresponding
entry in `syms` due to the way they are set up together.  So as
long as the unused entries in row and column 0 of `syms` have been
zeroed the rANS codec should not try to access any other
uninitialized locations.
=> Fix a couple of minor rANS issues with handling invalid data

.appveyor.yml, bgzf.c, cram/cram_codecs.h, cram/cram_encode.c, cram/cram_external.c, cram/cram_io.c, cram/cram_structs.h, hfile_libcurl.c, htslib/kseq.h, htslib/ksort.h, knetfile.c, kstring.c, sam.c, synced_bcf_reader.c, tabix.c, test/test.pl, thread_pool.c, vcf.c, vcfutils.c
SunStudio compiler warnings:
- Unreachable code
- Anonymous unions
- Integer conversions
- Suppressed 'end of loop not reached' error in a macro.  SunStudio annoyingly does not like `do { return; } while (0)`.
MinGW-w64:
- No return statement in function returning non-void.  Possibly due to mingw-w64's gcc not knowing that pthread_exit() can't return.
- Suppressed -Wformat warnings in appveyor config.  These are just broken on mingw-w64.
NetBSD:
- Warnings about char passed to isspace() ...etc.
- Fix unintended macro expansion in KSORT_INIT_GENERIC().  This is likely a bug as it caused the wrong symbols to be generated, and it's not entirely clear how the result got linked.
clang:
- Unused function warnings in kseq.
=> Fix warnings on various platforms

NEWS, cram/cram_encode.c, cram/cram_io.c, cram/cram_structs.h, hts.c, htslib/hts.h
See samtools/samtools#717 for discussion.
The NM tag is ambiguous and infact differs in implementation between
htsjdk and htslib.  Specifically N in both ref and seq is considered
to be a mismatch for samtools and a match in picard.
If we detect this case we now also store NM and MD verbatim, along
with the suspect case of falling off the end of the reference (who
knows what people write to these fields in that ill-defined case).
This makes it more likely that a round-trip from SAM -> CRAM -> SAM
will work even when the input SAM was produced via htsjdk.
To be ultra careful, we also add store_md and store_nm options to
always store this data verbatim.  When combined with decode_md (note
this implicitly also implies decode_nm) this means it is possible to
round-trip while keeping these …
=> Improved round-trip support for NM and MD tags in CRAM.

hts.c
Fixes a bug in the creation of the multi-region iterator, that
caused some reads to be wrongly skipped when reading a BAM file.
=> Fix for multi-region iterator

htslib/sam.h, sam.c, test/sam.c
Fixes #686 by adding interfaces in the style of `bam_aux_update_str()` that do the same job on integer, floating point and array type tags.  They should provide an easier interface than having to use `bam_aux_del()` and `bam_aux_append()` to achieve the same result.  `bam_aux_update_int()` is also easier to use as it will choose an appropriate size for the inserted data.
The new functions don't change the order of existing tags.  `bam_aux_update_int()` and `bam_aux_update_float()` will try to avoid moving the following data on updates if the new value fits inside the old space.
Some code for reallocating bam data is put into its own function as the number of copies was starting to get rather high.
Includes tests and doxygen.  Tests have been run on sparc to ensure the big-endian parts …
=> New interfaces to add or update bam integer, float and array aux tags

cram/cram_encode.c, cram/cram_io.c, htslib/kstring.h, sam.c, synced_bcf_reader.c
Possible integer overflow in kputs.
Possible buffer overflow in cram_populate_ref().
Not caught by gcc, but seen at the same time: Possible overflow in expand_cache_path().
Possible use of uninitialised values in bcf_sr_regions_next().  @pd3 probably needs to check the fix for this one.
=> Fix warnings found when compiling with gcc 8.1.0

bgzf.c, hfile.c, htslib/hfile.h, thread_pool.c
The first two commits here reduce the number of times threads get woken up only to discover there's nothing to do.  Fewer wake-ups means less lock contention.
The third avoids a `memcpy()` and extra call to `fp->backend->write()` when `hwrite()` is called with more data than fits in the buffer and the buffer was empty to begin with.  This seems to happen quite a bit when writing bam files.
The fourth copies the code for handling level 0 (uncompressed blocks) from the libdeflate version of bgzf_compress() into the zlib version as well.  The main benefit is that it avoids some unnecessary memory allocations in `deflateInit2()` and frees in `deflateEnd()` for buffers that are never used.
The fifth is also for uncompressed bgzf, this time when using threads.  It removes the `memcpy()` between …
=> Make htslib a little bit more efficient

cram/open_trace_file.c
We previously printed "failed to populate ref" etc, but not why.
This would have been helpful in samtools/samtools#857 to diagnose the
cause of the problem.
=> Report the reason for failing to open a reference.

configure.ac
In samtools/samtools#862 a fairly experienced user managed to not notice the voluminous error message at the end of the voluminous configure output, and continued by running `make` despite configure having ended in error.
With no _config.mk_ etc, `make` carried on and built a default configuration of HTSlib, which did not have desired functionality that would have been --enabled during configure.
This PR makes configuration errors write a _config.mk_ fragment that causes:
```
… … …
checking for curl_easy_pausebork in -lcurl... no
checking for curl_easy_init in -lcurl... yes
configure: error: libcurl library is too old (7.18+ required)
Support for HTTPS and other SSL-based URLs requires routines from the libcurl
library <http://curl.haxx.se/libcurl/>.  Building HTSlib with libcurl enabled …
```
=> Prevent make from working after configure errors

hts.c
Usage example:
samtools view -O bam,level=1 -o u.bam b.bam
Fixes samtools/samtools#872
=> Adds a level=%d option to hts_set_opt.

.appveyor.yml, htslib/hts_log.h
Infrastructure to do this was added to hts_defs.h in 75d9f0d, but was not applied to the hts_log() declaration in hts_log.h
Remove -Wno-format CFLAGS from appveyor config (reverting 5fef1b) now a better solution has been found.
=> Fix mingw printf format warnings

htslib/sam.h
We support SAM 1.6 features, notably the BAM CG tag for long CIGAR strings.
=> Bump SAM_FORMAT_VERSION to 1.6

sam.c, test/sam.c
Check for NULL `fp` in `sam_hdr_read()`, `sam_hdr_write()`
Add more tests for failure in copy_check_alignment()
Catch problems like sam_open() and sam_read1() failing.  Prevents a seg fault if sam_open() fails on either the input or output file.  #728 triggered this by running `./sam` in the `test` directory instead of `./test/sam` in the base directory.
Fixes #728
=> Add NULL checks to sam_hdr_read(), sam_hdr_write(); add checks to test/sam.c copy_check_alignment()

INSTALL
The configure.ac script has guidance on the missing packages when it
finds them, but it is useful to have this information listed upfront
rather than hitting each in turn.
If approved, I can make the same change to Samtools (it's only curses / ncurses though).
=> Additional installation hints for dependencies.

cram/cram_decode.c
It sometimes failed to set the EOF flag correctly, reporting decode
failures instead of terminating correctly.
Fixes #734
=> Fixes a multi-threading cram decode bug.

cram/rANS_static.c
A noddy failure to reinitialise fsum.  Odd that it worked when tested
before on the original bug - presumably due to luck somehow (wrap
around not being detrimental).
Fixes samtools/samtools#895.
=> Corrected rans normalisation bug introduced in 4ef6c76f.

vcf.c
Set `free()`-ed pointers to NULL, calling `bcf_empty()` repeatedly should not result in segfault.
=> Repeated calling of bcf_empty() must not segfault

htslib/vcf.h, tabix.c, test/test-bcf-translate.c, test/test-vcf-api.c
As discussed in #740
Possibly more functions could be added, but at the very least these checks
should be always performed.
=> Warn if the return status of VCF I/O functions is not checked

.appveyor.yml, .travis.yml, tbx.c
Also enabled -O3 as some of the bugs aren't spotted at -O2.
Fixes a Tabix error handling bug, detected by gcc7 which (with -Werror) caused  AppVeyor to fail.
=> Added -Werror  to travis & appveyor builds.

bgzip.c, tabix.c
Minor change to make these utilities' `--help` options follow the GNU conventions. And so be conveniently greppable.
=> Make bgzip --help and tabix --help write to standard output

htsfile.1, htsfile.c
Add `htsfile --copy` option that does byte-for-byte file copies. This exercises hFILE writing as well as reading, and provides a useful utility to copy files between HTSlib-implemented URLs.
And a small option-handling bug fix.
=> Add file copy facility to htsfile

knetfile.c
This fixes a memory leak found by fuzzing tools at Google.  Here's the comment from the team that found this:
fp->size_cmd is set to allocated memory in kftp_parse_url() but this is not freed by knet_close(). The fix should be safe in other cases as these allocate the memory of fp via calloc leaving fp->size_cmd equal to NULL by default, and free(NULL) is a nop (https://linux.die.net/man/3/free).
=> Fix memory leak in knetfile.c

tabix.c
Fix the end coordinate passed to the `regidx_overlap `function,
in order to match its expected **0-based inclusive** format.
Fixes #753
=> regidx end coordinate fix

cram/cram_io.c, cram/string_alloc.c
Detected on Windows after MinGW upgraded to gcc 8.2.0.
string_ndup() now uses memcpy() instead of strncpy() so it
will now copy len bytes even if the string contains a NUL.  This
could only possibly happen in one use of this function (to store
paired read names in process_one_read, if the name illegally
includes an embedded NUL), and even in that case it will not read
any uninitialised memory.
=> Fix possible string truncation warnings

.gitignore, Makefile, hts.c, htslib/kstring.h, kstring.c, sam.c, test/test_kstring.c
Warning - a scary level of changes to fundamental parts of the code.
It does however speed up reading by about a factor of 2.1 and writing by 1.8 (gcc8 tests).  See the commits for a more detailed speed analysis.
The main relevant changes are:
- New kputw/kputuw which is >2x faster than the old one, depending on compiler.
- A new kgetline2 function which accepts `hgetln` instead of `hgets` prototype.  This means we return the length rather than the original pointer, avoiding a pointless second pass over the string.
- Replacements for strtol and strtoul which are base 10 specific and better optimised.
- (Now the scarier stuff!).  Unaligned 64-bit specific code (with appropriate guards) taken from io_lib for tab/newline tokenisation during SAM decode.
- Various tweaks to use `kputc_` …
=> Sam reading and writing speed improvements

cram/open_trace_file.c, hfile.c, hfile_libcurl.c
The MSYS2 default build environment is similar to Cygwin, with the exception of the path style, which is Windows like for MSYS2.
`__MSYS__` macro is only defined for this environment, so it doesn't affect Cygwin, MINGW or Linux builds.
`_WIN32` macro is not defined for this environment, although it is defined for MINGW environments (which can be installed under MSYS2).
=> Fix the MSYS2 test harness for samtools

bgzf.c
This makes the segfault in
https://ci.appveyor.com/project/samtools/samtools/builds/20362947
an error message instead.
(A proper fix for that belongs elsewhere though.)
=> Check for malloc failure.

.travis.yml
Since libdeflate commit 73017f0 it needs an up to date binutils so that the assembler understands avx512 instructions.  This is necessary even if gcc options do not enable avx512 as libdeflate uses inline assembly.  Using the "xenial" distribution supported by travis is the easiest way to get a new enough binutils.
Pull requests will need to be rebased over this commit for the gcc-8 build with libdeflate to work.
=> Fix libdeflate build using gcc-8 on travis

realn.c
`sam_cap_mapq()` might be called with arbitrary data in _ref_, including characters '\x80'..'\xFF' that are negative on many platforms.
All uses of `seq_nt16_table[]` in htslib are now cast appropriately.
OTOH there are lots of `seq_nt16_table[(int) ref[x]]` in the SAMtools codebase still. For most of these, `ref` has come from `fai_fetch()` et al, which returns only `isgraph()` characters, so for the typical POSIX/C locale problematic characters won't occur. (Not that this makes such code right…)
All this somewhat suggests that HTSlib could usefully have a wrapper function around `seq_nt16_table` that does this casting for you…
=> Fix seq_nt16_table[(unsigned char) foo] cast

bgzf.c, htslib/bgzf.h, test/test_bgzf.c
The seeking part has quite a lot in common with bgzf_seek(), so put it into new function bgzf_seek_common() which both call.
Enable bgzf_useek() with threads tests in test/test_bgzf.c
=> Make bgzf_useek() work with threads

hts.c
When hts_itr_query() returns NULL, it should also free the hts_itr_t object if that object is previously allocated.
=> Fix leak of hts_itr_t in hts_itr_query

bgzf.c, htslib/thread_pool.h, thread_pool.c, thread_pool_internal.h
Add infrastructure to clean up unused thread pool jobs, and use it to fix a leak that occurred when seeking on bgzf files when using threads.
Fixes #822
=> Thread cleanup

bgzf.c, thread_pool.c, thread_pool_internal.h
In the thread pool, we now set "no_more_input" flag in
hts_tpool_process_destroy as it was possible for deadlocks to occur
with another process hammering the input queue while attempting to
reset and flush prior to destroying the queue.  The shutdown flag
isn't quite sufficient here as that also changes the flush behavior.
We wish to flush correctly (on valid termination), but do not wish to
add more items to the input queue.
In the bgzf side, I also improved the error handling so that
fp->errcode isn't set within bgzf_mt_writer (no intervening lock so
that is a data race).  It now handles this properly with the join
retval.
Fixes #831
=> Fixed deadlock in thread pool / bgzf error handling.

bgzf.c
Fixes bug where EOF would be checked after reading each block which is much more than strictly necessary.  Only happened if the thread pool was enabled before checking EOF, so not all programs were affected.  On BAM files, this requires setting up the thread pool before calling `bam_hdr_read()`.  `test/test_view` did this and had the problem while `samtools view` did not.
synced_bcf_reader checks EOF before setting up the thread pool so was not affected.
=> Reset mt->command to NONE in bgzf_mt_eof()

Makefile, hts.c, htslib/hts.h, htslib/sam.h, region.c, sam.c, test/test_view.c
Merge the two iterator structures (`hts_itr_t` and `hts_itr_multi_t`) into one.
Add a method for creating a `hts_reglist_t` out of a char array of reg:interval elements.
Fixes #785
=> Multi-region iterator interface merger

test/test-vcf-api.c, test/test-vcf-api.out, vcf.c
Fixes #842 and an alternative to #843.
=> Allow removed vcf headers to be replaced.

errmod.c, hts.c, htslib/ksort.h
Consider the following program:
```c
#include "htslib/ksort.h"
#include "htslib/hts.h"
/* Compile and link with
gcc -o foo foo.c libhts.a -lbz2 -llzma -lz
*/
typedef struct {
int x;
} foo;
#define bar(a,b) ((a).x < (b).x)
KSORT_INIT_GENERIC(uint16_t)
KSORT_INIT(_off, foo, bar)
KSORT_INIT(_off_max, foo, bar)
int main() {
hts_version();  // pull in hts.o
errmod_cal(NULL, 0, 0, NULL, NULL);  // pull in errmod.o
}
```
This fails to link due to 24 duplicate `ks_*` functions, as the ksort usage in _errmod.c_ and _hts.c_ uses non-`hts_`-prefixed public namespace functions. It would be possible to make those HTSlib source files use ksort functions with names like `…_htslib_internal_…` which would not collide with sensible third-party code, but it's about as easy to add `static` support to …
=> Allow making KSORT functions static

cram/cram_decode.c
When the NM tag is decoded in `cram_decode_seq()`, the tag integer type is set to `I`, regardless of NM value. This commit allows setting the decoded NM tag integer type as `C`, `S` or `I`, depending on NM value, which mirrors how `sam_parse1()` encodes auxiliary tag integer values.
=> Set different integer types when decoding NM tag from CRAM

test/test-vcf-api.c, vcf.c
I needed this for something else, hence… Rather than asserting that no value has previously been set, free any previously set value array before unpacking the new one.  Fixes #813.
(This free() is all that's left after duplicating the "Mark the tag for removal, free existing memory if necessary" code from earlier in each function, and removing assignments that are unnecessary due to the immediately following bcf_unpack_info/fmt_core1() call.)
=> Allow repeated invocations of bcf_update_info/format_*()

htslib/hts.h
4c2c536 added a typedef of bam_hdr_t in htslib/hts.h which made old versions of gcc complain about "redefinition of typedef 'bam_hdr_t'". [Versions of gcc after 4.6 don't mind.](https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=ce3765b)
Fix by referring to the struct instead of the typedef.
Fixes #857 (htslib/sam.h update breaks compatibility with gcc 4.4.7)
=> Fix builds on gcc older than 4.6

htslib/kstring.h
Helps to clear build warnings on MinGW.
=> Make kvsprintf format checking platform configurable

htslib.mk
Add extra target `hts.dll.a` for building htslib as a shared library. Needed for compiling bcftools plug-ins on Windows.
=> Add extra target for shared library

m4/hts_prog_cc_warnings.m4
AC_ARG_ENABLE's third argument, ACTION-IF-GIVEN, includes when the argument is given as --enable-werror=no / --disable-werror. The fourth argument continues the existing default of enable=no.
=> Fix configure --disable-werror (trivial m4 fix)

Makefile, faidx.c
While I had the Illumos VM running, I noticed that the htslib build had regressed slightly.  This fixes a linking problem and a couple of warnings.  The last one didn't generate a warning, I just noticed it as it was nearby.
* Remove unnecessary -pthread option from test/pileup
* Fix unreachable code warnings in faidx.c
* Remove if statement where condition is always true.
=> Fix compilation on Illumos / Sun C compiler

bgzf.c, hts.c, htslib/bgzf.h, vcf_sweep.c
On Windows, `long` is defined as a signed 32 bit type, even on a 64 bit OS, while it is a 64 bit type on a 64 bit Linux machine. This creates discrepancies, especially when working with values larger than 2<sup>31</sup>.
On the other hand, the length of `off_t` is determined by the platform configurable macro `_FILE_OFFSET_BITS`.
Fixes #866
=> Change long to off_t for file offsets

Makefile, NEWS, config.mk.in, hfile.c, hfile_internal.h, hfile_libcurl.c, hfile_s3.c, hfile_s3_write.c
This change will default to using version 4 signatures over the current version 2 ones.  It will also allow the writing of files to S3 repositories. Fixes #776, #764, #492, #477 and #454.
Documentation of new and old environmental variables and of general s3 htslib usage will be done in a separate pull request.
=> Update S3 code to use version 4 signatures.

bcf_sr_sort.c, errmod.c, htslib/ksort.h, htslib/sam.h, htslib/synced_bcf_reader.h, htslib/vcf.h, htslib/vcfutils.h, kstring.c, sam.c, synced_bcf_reader.c, tbx.c, textutils.c, vcf.c, vcf_sweep.c, vcfutils.c
There are numerous places where we call e.g. hts_expand, kh_init, kh_put, malloc/calloc, and so on, but the function has void return type.  Clearly these can fail.
What this commit specifically does NOT do is add error checking.  It is simply a placeholder that changes the return types, and thus technically the ABI, permitting us to do the full checks at a later
stage.  That PR will be much larger and more time consuming, hence splitting in two.
Every function that now returns a dummy 0 (success) value now contains a comment "_FIXME: check for errs in this function_" so we can grep for these and fix them in later releases.
We also do not add explicit HTS_RESULT_USED statements, because doing so will force us to start adding error checking in our own code; please refer to the earlier …
=> Change return type of functions that can error (and nothing more).

hfile_s3.c, hfile_s3_write.c, htslib-s3-plugin.7
Stop escaping query strings in their entirety. Handle query string properly in the authentication steps.  Added two new environment variables and added the documentation for all our S3 environment variables.
=> S3 query string handling and other additions.

.travis.yml, bgzf.c, hts.c, hts_internal.h, sam.c, test/test.pl
3 things, 2 small 1 not.
1. Added address sanitizer to travis config.  It appears to be an oversight that we only did this for samtools and not here.
2. Made hts_open_format behave as expected; where the `fmt` argument takes precedence over mode string.
3. Fixed BGZF auto-indexing so it works when running with multiple encoder threads.
=> Auto index

bgzf.c, test/test_bgzf.c
Instead of always trying to seek, check to see if the desired location is within the data that has already been read.
Fixes repeated reads of the same data spotted when running tests for samtools/samtools#1066 where a test reference fasta file had lots of very small entries.  While most normal reference fastas are going to have much bigger entries in them, it's still likely that most of the seek calls that skip over the headers can actually be avoided.
=> Make bgzf_useek more efficient if data is already available.

hfile.c, hts.c, hts_internal.h, htslib/hts.h, htslib/sam.h, htslib/tbx.h, htslib/vcf.h, sam.c, synced_bcf_reader.c, tabix.1, tabix.c, tbx.c, vcf.c
1. First search for a local index file with any of the possible extensions (`*.bam.csi`, `*.csi`, `*.bam.bai`, `*bai`).
2. If a file is found, load it or report an error.
3. If no index file is found and the alignment file is remote, try downloading it from the same server.
4. Before beginning the full download, check if the format is correct and only proceed if it is a known index format.
5. Load the downloaded file.
Fixes https://github.com/samtools/samtools/issues/1045
=> Improve index file search and load

NEWS, cram/cram_decode.c, cram/cram_decode.h, cram/cram_encode.c, cram/cram_external.c, cram/cram_io.c, cram/cram_io.h, cram/cram_structs.h, header.c, header.h, hts.c, htsfile.c, htslib/cram.h, htslib/hts.h, htslib/sam.h, htslib_vars.mk, sam.c, test/fieldarith.c, test/fuzz/hts_open_fuzzer.c, test/pileup.c, test/sam.c, test/test-parse-reg.c, test/test_realn.c, test/test_view.c
With the exception of some early functions, HTSlib's convention for generic SAM/BAM/CRAM functions is a `sam_` prefix. (cf e.g. `bam_hdr_read()` which works for BAM files only vs. `sam_hdr_read()` which is for any of SAM/BAM/CRAM.)
For your consideration, this PR renames the newly added public header API functions to use a `sam_hdr_` prefix rather than the `bam_hdr_` prefix of PR #812. If the maintainers' consensus is that they would like to go down this route, I would be happy to add commits to rename the new internal functions similarly and/or to add renaming shims for e.g. `sam_hdr_init()` and `sam_hdr_t`, i.e., things that have long had a somewhat unfortunate `bam_hdr_` prefix.
I have also tried out the renaming on samtools/samtools#998; that compiles cleanly, and both htslib and …
=> Proposal: Use sam_hdr_ prefix for new header API functions

.gitignore, Makefile, NEWS, htslib/sam.h, sam.c, test/sam.c
[Something that I noticed while going over the header code…]
Since 3bb8fd1b1a940ca6c30f744451e58bafdf177461 all SAM file readers share a static `cigar_tab` that is reinitialised each time a `sam_hdr_t` is given to `sam_parse1()` for the first time. If multiple SAM files are being read by a multithreaded program, in theory this could cause spurious parse failures if `cigar_tab` is reinitialised while another thread is parsing a CIGAR string.
This could be improved by only actually writing to `cigar_tab` the first time `cigar_tab_init()` is called, but to be really threading-correct I think this would need a mutex. Easier just to do what should have been done years ago and write out the contents of the table explicitly and make it `const`! :smile:
Also a small commit to fix a dependency …
=> Fix sam_parse1() / cigar_tab[] race condition

header.c, htslib/sam.h, sam.c
Rename `sam_hdr_name2ref` to `sam_hdr_name2id`.
Add methods `sam_hdr_id2name` and `sam_hdr_id2len`.
=> [header API] Methods for retrieving reference sequence name and length

configure.ac
By default or with --with-libdeflate=check, the intention is to carry on as per --without-libdeflate when either header or library is missing.
For the case when libdeflate.h is missing but the library is found (admittedly an odd case!), the default AC_CHECK_LIB ACTION-IF-FOUND will define HAVE_LIBDEFLATE and add to $LIBS itself — leading to later build failures as we (ab)use that macro to mean both HAVE_LIBDEFLATE_H and HAVE_LIBDEFLATE.
Instead use a no-op found action, and only AC_DEFINE(HAVE_LIBDEFLATE) and add to $LIBS when **both** checks have succeeded.
This scenario was the cause of the Travis failures in pysam-developers/pysam#829.
=> Fix libdeflate configure check

header.c, htslib/sam.h
Make `sam_hdr_length` return **SIZE_MAX** in case of error, thus matching its return type range.
The underlying error would be logged by the called method that produced it.
=> [header API] Change return value of sam_hdr_length

cram/cram_index.c, sam.c, test/sam.c
[More things noticed while going over the header code…]
Avoid overflow in `STRTOL64()` and `STRTOUL64()` (and similar functions in _cram/cram_index.c_) by ensuring that the subtraction occurs first. Compiling with `-fsanitize=undefined` (for the unsigned ones, use `-fsanitize=unsigned-integer-overflow` as well) demonstrates these overflows.
At the moment this doesn't matter too much for the _sam.c_ functions as they are used only up to 32 bits, but this prepares them for actual 64-bit use. Also changed the return type of `STRTOUL64()` to be unsigned — @jkbonfield was it intentional to use `int64_t` for `STRTOUL64` (performance reasons?) or is changing this to `uint64_t` okay?
Prior to the recent 9f28a4f1bee95eb0842e92a8a994c34bdfb657ae, `sam_parse1()` used `strtol(p, &p, 0)` to parse …
=> sam_parse1(): return to allowing FLAGs in hex/octal; avoid overflow

NEWS, cram/cram_samtools.c, htslib/sam.h, sam.c, test/sam.c
Another ABI breaker that was in danger of being forgotten about while the ABI change window is open (leastwise I for one had forgotten about it!): change `l_qname` to `uint16_t` so QNAME length can be returned to the spec's 254 from 079c7b81d3eb740f575d6ee07f8d0df36932559e's 251 — see #520.
As the soversion is being bumped, we have the luxury of fixing this by simply enlarging the `l_qname` field. It needs to represent the values 0…256 so most of the new bits are wasted, but ¯\\\_(ツ)\_/¯ and maybe one day we may have a format wanting longer QNAMEs…
Adds test cases with long read names. I wish I had though of such test cases when I first implemented the align-the-CIGAR-data thing in 5d114ebd8e9b80622769b8e575c5a9359cd51273!
Fixes #520. Supersedes and closes #523.
=> Restore support for QNAMEs longer than 251 characters

header.c, htslib/sam.h, test/sam.c
`@SQ`, `@RG` and `@PG` lines have dedicated look-up tables and arrays, that should be exposed via the header API for faster retrieval of line position and identifier string.
=> [header API] Add methods `sam_hdr_line_index` and `sam_hdr_line_name`.

.travis.yml
I just send a pull-request to do refactoring to make `.travis.yml`'s conditional statements more readable.
YAML's `|` block style enables it.
Thanks.
=> Make .travis.yml conditional statements readable

cram/cram_index.c
Query on ref "*" sometimes fails if the unmapped data is in a ref -1
block (rather than ref -2 == multi-ref). This is now more commonly
triggered due to the change in switching back out of multi-ref mode.
The problem was the range start..end is 1 to 0 (a bit odd) which
causes the slices to be skipped as unmapped slices have start 0.
In addition to the old fix from #958, we now also reset the range
query start pos.
=> Bug fix to cram index query.

htslib/cram.h, htslib/sam.h
Allows it to be used without having to include "htslib/cram.h" just for the one function.
"htslib/cram.h" includes "htslib/sam.h" itself, so anyone looking for it there will still get it.
=> Move stringify_argv() from htslib/cram.h to htslib/sam.h

hts.c
Inserting malformed ranges into the index leads to a broken index for which `hts_itr_query()` produces incorrect results for nearby query regions. This pretty much can't happen for SAM/BAM/CRAM (the CIGAR calculation produces a length >= 0), but does happen for VCF/BCF when the input record has an invalid INFO/END field that's < POS.
In particular, this will make `bcftools index` refuse to index files where INFO/END is being used for a different purpose — see samtools/hts-specs#425. Previously it would happily produce an index that didn't work properly.
Instead of this PR, it would be possible to validate that `rlen >= 0` in the _vcf.c_ code that computes `rlen` from an input INFO/END field value. However that would mean that HTSlib would refuse to read in these delly/gnomad/etc records …
=> Validate record range when constructing BAI/CSI indexes

cram/cram_codecs.c, cram/cram_decode.c, cram/cram_encode.c, cram/cram_external.c, cram/cram_io.c, cram/cram_io.h, cram/cram_stats.c, cram/cram_stats.h, cram/mFILE.c, header.c, htslib/kstring.h, sam.c
(And also a few SAM ones.)
These have been found by exhaustively making the Nth malloc, calloc or realloc fail and testing the behaviour of reading and writing.  This found several crashes due to not spotting the failure.
This PR fixes those, but it does NOT fix all the potential memory leaks that may ensue when running out of memory and bubbling the error back up the chain to the calling application.  That's a bug too, but in the whole spectrum of bug severity "meh" to "OMG it's on fire" it's down the feeble end so in the interests of time this focuses on the crash / incorrect behaviour issues.
It passes htslib and samtools test harnesses, but I want to hammer it on some large files to check it doesn't have undesireable speed issues or problems.
=> Cram mem fixes

Makefile, header.c, hfile_libcurl.c, hfile_s3_write.c, hts.c, htslib/hts.h, sam.c, vcf.c
Various minor tidy ups, as described in the commit messages.
Potentially interesting ones are:
* Future-proof CRAM magic detection by recognising up to `CRAM\x07\x07`, “CRAM v7.7”
* `hts_resize()` documentation didn't appear to describe its return value and error codes
=> More various minor tidy ups

header.c
Fix a bug in the header API, which prevented the removal of all lines when the line ID_key was NULL.
=> [header API] Bugfix in line remove

header.c, htslib/sam.h, test/sam.c
Improve documentation of `sam_hdr_remove_lines`, which now removes all lines if the keep hash set is NULL.
Add tests for `sam_hdr_remove_lines`.
Fix #928
=> [header API] Documentation and tests for sam_hdr_remove_lines

NEWS, header.c, test/sam.c
Support alternative sequence names as per samtools/hts-specs#100.
This is a work-in-progress for testing purposes, as `sam_hdr_update_line()` does not yet handle AN altnames. Everything else should be ready to go though.
(View the `sam_hrecs_remove_hash_entry()` diff with -w as the bulk of the code is unchanged other than its indentation level.)
=> Add support for SQ-AN alternative sequence names

hts.c, test/test_view.c
With samtools view -t ref.fa, fp->fn_aux is set.
With samtools view -o reference=ref.fa, this didn't happen.
Both of them load the reference and generate a CRAM_OPT_REFERENCE
parameter, but when writing the CRAM header if fn_aux is set it'll
cause a reload to validate the order in the fai file matches the order
in the header, and if not reorders the structures.
The result of this is using -o to set reference could sometimes get
M5 values out of sync with SQ SNs.
=> Fixed CRAM_OPT_REFERENCE handling for files with reordered headers.

hfile_s3_write.c, htslib-s3-plugin.7
Added a way of setting the upload part size.
Use the HTS_S3_PART_SIZE environment variable to set the upload size.  Minimum part size is still 5Mb.
Fixes #938.
=> Change upload part size.

bgzf.c, test/test_bgzf.c
Patch suggested by @jkbonfield
This is an alternative to #901 that will also fix #899. But in this version, virtual offsets in uncompressed files are virtual: they consist of a block start address and an offset in the block.
Many virtual offsets can point to the same byte in the file, because a block could start at any byte in an uncompressed file. However, the library will read the file in max size blocks starting from 0, so unless the user is synthesizing virtual offsets there will still be a canonical set of block start points.
=> Allow seeking to virtual offsets in uncompressed streams

cram/cram_decode.c, cram/cram_encode.c, cram/cram_structs.h
The preservation map for 1.0 defines MI, UI and PI keys, which in turn
set a bunch of variables related to how quality scores are stored.
The 1.0 spec required this, but even in the official 1.0 cramtools-jar
completely ignored them.
They appear in this C code as I added them while writing io_lib's
implementation from the 1.0 specification, but the variables are never
accessed as that was the only way to get parity with cramtools.jar.
This patch keeps the keys so a 1.0 file doesn't whinge (cramtools did
write those fields out, even if it never did anything with them), but
they are now silently skipped.
[TODO:  ditch 1.0 entirely!  I'm not convinced it works in any
meaningful way, given the specification and Java implementation
differed greatly. CRAM 2.0 was born from this - unifying code …
=> Removed some CRAM pre-1.0 legacies.

sam.c
Fix runtime warnings that appear when running `make test` on an undefined behaviour sanitizer build.
=> Fix call of memcpy with NULL source in sam_dispatcher_read

Makefile, NEWS, hfile_gcs.c, hfile_libcurl.c, hfile_s3.c, hfile_s3_write.c, hts.c, htslib/hts.h, test/sam.c
Here is a proposal for adding a public `HTS_VERSION` macro, for use by third-party code wishing to probe for the existence of newly-added HTSlib capabilities (without going to the effort of writing configure tests to check for them!), as wished for in #794.
HTSlib already has a `hts_version()` function that reports the version of HTSlib that a program is _running against_, which is the most useful thing for third-party programs to report as it reflects the HTSlib behaviour observed and in particular what library bugs may have been fixed.
It would additionally be useful for HTSlib to have a preprocessor macro so that programs could enquire about the version of HTSlib being _compiled against_ at compile time, and emit an understandable `#error` or (if they are overachievers) adjust their …
=> Add HTS_VERSION macro for compile-time HTSlib version checks

bgzf.c, htslib/bgzf.h, test/test_bgzf.c
Move `#include <zlib.h>` from _htslib/bgzf.h_ to _bgzf.c_, as callers of BGZF functions don't need zlib declarations. This was the only non-system #include in the public HTSlib headers (apart from inclusion of other HTSlib headers, of course).
This is something I've had lying around for a long time, but hadn't previously looked at how long the `z_stream_s` tag has been stable in zlib — happily the answer is decades and it is used in other zlib language bindings too so won't be changing.
This could cause minor breakage to third-party code itself using zlib functions but only #including `<htslib/bgzf.h>`. I've verified that samtools and bcftools both 1.9 and **develop** compile fine with this change. The possibility of breakage for other third-party code remains, but there's enough …
=> Move <zlib.h> include out of the public bgzf.h header

faidx.c, htslib/faidx.h
Exposes `fai_set_cache_size` for setting the cache of BGZF based faidx files.
Fixes #913
=> [new method] fai_set_cache_size

faidx.c, hts.c, htslib/faidx.h, htslib/hts.h, htslib/sam.h, sam.c, test/test-parse-reg.c
Also fixed a few other assumptions of hts_pos_t equalling int64_t.
Updated the test-parse-reg to use hts_pos_t as well.
Added a comment to hts_parse_reg64 indicating that it is not our
preferred API.  It was added in a separate commit for ease of API
migration from hts_parse_reg, but was added only because the
hts_parse_region code hadn't been accepted.  This is now the correct
interface.
---
Note the name of hts_parse_reg64 is mildly annoying.  When Linux switched from fseek taking long to taking off_t it didn't use fseek64, but fseeko.  It's largely irrelevant though as both hts_parse_reg and hts_parse_reg64 should be considered deprecated.
=> Changed int64_t to hts_pos_t for *_parse_region API

cram/cram_index.c, hfile.c, hts.c, hts_internal.h
When doing a indexed search in a CRAM file, look first for a local CRAI index file in the current folder. If unsuccessful and the CRAM file is remote (e.g. S3, HTTP, FTP), go to the same remote location and try to fetch it from there.
Fixes https://github.com/samtools/samtools/issues/1132
Improves https://github.com/samtools/htslib/pull/870
=> Search for a local .crai index first

.gitignore, Makefile, htslib.mk
Fixes a missing shared dependency on the HTSlib object files for the (Windows and Mac) shared and static library targets in `htslib.mk`.  This was causing random [build failures](https://ci.appveyor.com/project/samtools/bcftools/builds/28720476) for BCFtools on Appveyor because it was trying to build both the shared and static libraries at the same time, resulting in the `.o` files being built twice and one of the libraries to become corrupt because one of the object files being included got rebuilt as it was added.
The fix creates an empty file target file `hts-object-files` in HTSlib's Makefile which `htslib.mk` uses to track the shared dependency for the libraries.  While adding an empty target isn't ideal (for example it won't notice missing `.o` files if the `.c` file is unchanged), …
=> Fix htslib.mk parallel build

hfile_s3_write.c, vcf.c
For some optimisation levels, gcc would report a format-truncation warning for the line that measured how much memory was needed to store the header string.  Silence it by supplying a reasonably big buffer, which has the added bonus that the malloc and second call to vsnprintf can be avoided completely in most cases.
=> Silence gcc warnings

Makefile, configure.ac, cram/open_trace_file.c, hfile.c, hfile_s3.c, hts.c, htslib/hts.h, plugin.c, test/test-regidx.c, textutils_internal.h
Works around the plug-in's insistence on linking against and using the shared hts.dll by spotting when this causes a problem and using `dlopen()` /  `dlsym()` to find `hfile_add_scheme_handler()` in the executable and call that instead.  This ensures the plug-in is registered in the correct place.  It's not elegant but it works.
Additional bonus fixes:
- A missing dependencies on hts.dll.a which could result in the plug-in dlls trying to build before the shared library was available.
- Some char-subscripts warnings due to use of `ctype` functions with `char` types.  These don't appear to trigger warnings in our CI builds (including Appveyor) but did when I made a MinGW build by hand.
Fixes #964
=> Fix crash when loading external plug-ins into Windows executables that statically link HTSlib

sam.c
CRAM files have the header structure integrated in the file descriptor, so `cram_name2id` should take the CRAM file descriptor as its first parameter, as opposed to `bam_name2id`, which works with a detached header structure.
Fixes https://github.com/samtools/htslib/issues/977
=> Fix parameter passed to cram_name2id

header.c, sam.c, test/sam.c, test/test.pl
This is a simplified version of the `sam_hdr_dup` fix from PR #976 split out into its own pull request.
If the source header has not been parsed yet (i.e. `sam_hdr_t::hrecs` is NULL) it just copies any entries in `sam_hdr_t::sdict`.  If it has been parsed, `sam_hdr_t::sdict` entries are added in `sam_hdr_update_target_arrays` where necessary.
`sam_hdr_update_target_arrays` will now also remove `sam_hdr_t::sdict` entries if they are no longer needed.  This fixes a bug where dangling pointers could be left in `sdict` if any target names have been removed.
Adds some `sam_hdr_dup` tests in `test/sam.c` `check_big_ref()`.
=> Fix sam_hdr_dup to cope with long refs.

.gitignore, Makefile, htslib/faidx.h, htslib/hts.h, htslib_vars.mk, textutils.c
Another round of updating dependencies to correspond to `#include` updates in recent PRs.
It has occurred to me (and it seems obvious in retrospect!) that I could add a version of my dependency checking script to `make maintainer-check` so these would be caught immediately. (You could even use it as a pre-commit hook if you wanted to.) Could do this after the dust has settled on the current release activities.
=> Add missing Makefile dependencies and ignored test executable

htslib/cram.h, htslib/faidx.h, htslib/hts.h, htslib/regidx.h, htslib/sam.h, htslib/synced_bcf_reader.h, htslib/tbx.h, htslib/thread_pool.h, htslib/vcf.h
This is a very tedious PR that just expands the API documentation comments in _htslib/*.h_. No non-comment changes.
Add a note about the corresponding `*_destroy()`/`*_free()` function to the API doxygen for each function that allocates a structure and returns it with the expectation that the caller will eventually free it.
=> Mention _destroy function in each init function's documentation

synced_bcf_reader.c
Ensuring properly-prefixed functions (whose names start with `hts_`, `sam_`, or whatever) are `static` where possible is less necessary now that visibility control has been merged. However it is still important (at least for static linking against _libhts.a_) for functions that would otherwise pollute the user's namespace. Also remove the leading underscore from the new identifiers, as that is reserved to the compiler.
(These functions appeared in db90fb58b06d6f3b27b5b873588da7c77844da22 which was not done via a pull request, so was not reviewed.)
(Also a recent addition and a function that could be `static` is `sam_hdr_dup_sdict()`, but as that is properly prefixed there's no need to address it.)
=> Mark new internal synced_bcf_reader.c functions as static

htslib/kstring.h
In particular the second parameter should be `size_t`, not `int`.
The incorrect version worked when using `hgetln()`, mainly because the ABI passes arguments in registers.  This ensures it will work because the types match instead of due to a happy accident.
Presumably the original version was trying to match `fgets()`, but there's not much point in that as the return value is different.
Thanks to @jmarshall  for spotting this.
=> Change signature of kgets_func2() to be more like hgetln()

NEWS, configure.ac, hts_os.c, htslib/hts_os.h
This is a prerequisite for an upcoming samtools PR to make the test suite work on OpenBSD, where there are test suite failures testing `samtools merge -c -p` because OpenBSD produces a different random number sequence and so the renamed reference sequences are different from the tests' expected output.
This could be fixed in samtools, but as _hts_os.h_ collects together platform-specific `srand48()/drand48()/etc` foibles, it seems better to fix it here. Typically for HTSlib clients, cross-platform repeatability seems more important than unneeded  cryptographic secureness on one platform.
It would be possible to `#define srand48(S) hts_srand48((S))` on OpenBSD to get the standard sequence whichever of the two functions were used, but (1) this is very fragile as it is impossible to ensure …
=> Use srand48_deterministic() on platforms that have it

cram/cram_encode.c, cram/cram_index.c, cram/cram_io.c, cram/cram_structs.h
For transition from mapped to unmapped the types of codec to use in CRAM can change, particularly for the BA data series (used for unmapped sequence bases).
The data that is unmapped but placed along side the mapped, is often fairly random looking and entropy encoding does well.  The pure unmapped data is also usually fairly random looking, but with "samtools sort -M" can have strong similarities with previous reads making gzip or lzma a good tool.
As a demonstration on SRR1770413 (bwa aligned, sort -M).  Current htslib gives BA at 12.5Mb (larger with big slice sizes as it doesn't get time to restart the compression trials).  With this patch it's 6.6Mb for the same data (5.0Mb with lzma).
The second commit enables libdeflate usage within CRAM.  Previously we only used this for BAM and for …
=> Cram unmapped reset

cram/cram_io.c, cram/cram_structs.h
This means we don't validate the CRC until we have a need to use that
data.  Thus we don't pay the price when doing sub-queries such as
samtools index and samtools flagstats.
This brings htslib into line with io_lib's implementation which has
done this for some time.
Some benchmarks below on 1 million PacBio reads, which show this problem up more than most files due to the small nature of flags vs long sequence & quality blocks:
This branch:
```
time MALLOC_TOP_PAD_=1000000000 ./samtools flagstat /tmp/_1m.cram
real 0m0.523s
user 0m0.332s
sys  0m0.184s
time MALLOC_TOP_PAD_=1000000000 ./samtools index /tmp/_1m.cram
real 0m0.221s
user 0m0.024s
sys  0m0.196s
time MALLOC_TOP_PAD_=1000000000 ./samtools view -c /tmp/_1m.cram
real 0m30.824s
user 0m30.426s
sys  0m0.324s
```
Dev branch:
```
time …
```
=> Delay CRAM crc32 checks to block decompression step.

cram/cram_codecs.c
Fixes possible integer overflow in code_sort() by reporting an error on any negative Huffman code length.  A large negative value was needed to trigger the problem, and all lengths < 0 are invalid.
=> Error on negative CRAM Huffman code length

cram/cram_codecs.c
Only happens if high bit of last external block content_id byte is set.  This is unlikely in real data, but turned up in fuzz testing.
=> Fix possible undefined shift in cram_byte_array_stop_decode_init()

Makefile, header.c, header.h, htslib/synced_bcf_reader.h
Another collection of minor miscellanea:
* Add a couple of minor makefile targets to `make all`. While converting lofreq to use HTSlib directly, I wanted to use _htslib_static.mk_ to get `$(HTSLIB_static_LIBS)` but didn't want to use _htslib.mk_'s dependency infrastructure. This meant that e.g. https://github.com/CSB5/lofreq/pull/86/files#diff-354f30a63fb0907d4ad57269548329e3 couldn't just use `make all` but had to list `htslib_static.mk` as an explicit target. Adding it to HTSlib's `all` would remove this need.
* Fix the semi-theoretical sign-extension bugs in `TYPEKEY()` and use it throughout _header.c_. This replaces a bunch of bit-shifting on plain maybe-signed `chars` and makes for (to my eye) clearer code. Also prevents some `-Wextra` and cppcheck warnings.
* In the same source …
=> Add items to `make all`; fix some warnings in header.c [minor]

cram/cram_codecs.c, cram/cram_decode.c, cram/cram_encode.c, cram/cram_io.c, cram/cram_stats.c, cram/pooled_alloc.c, cram/rANS_static.c, hfile_s3.c, hts.c, htslib/kbitset.h, htslib/vcf.h, sam.c, synced_bcf_reader.c, tabix.c, test/hfile.c, test/sam.c, test/test_bgzf.c, test/test_kstring.c, thread_pool.c, vcf.c
Command ran: cppcheck --inline-suppr  --enable=warning -q -f --language=c .
This is a mix of silencing false positives, rewriting code to be less confusing to cppcheck (and sometimes to us), and genuine minor issues around handling running out of memory.
In some cases I've added inline suppressions, eg
// cppcheck-suppress objectIndex
This isn't ideal, but I personally think it's worth having a little annotation in order to make detection of future buglets easier to find.
Fixes #995
Propose merging immediately *after* 1.10 release as there are no serious bugs fixed.
Note cppcheck 1.72 still finds some false positives, but I don't propose silencing them.  1.90 is the latest version at time of PR.
=> Fixes to pass cppcheck-1.90 warnings

hts.c
Bug visible when trying to run `bcftools view "https://url1.gvcf.gz##idx##https://url2.gvcf.gz.tbi" 1:10000-10010`
The calling function `idx_filename` was receiving ret=0, but `local_len` wasn't set. As it was never initialized it randomly failed at the `memmove` operation.
=> Fix missing return parameter value

hts.c
Unspecified region interval ends are now set to **HTS_POS_MAX**, so the comparison should be made with **HTS_POS_MAX**, instead of **INT_MAX**.
Fixes https://github.com/samtools/samtools/issues/1173
=> Fix interval end comparison in CRAM iterator method

cram/cram_io.c, faidx.c, hts.c, hts_internal.h, htslib/faidx.h, htslib/hts.h, sam.c
1. The new method `fai_path` takes the full path to a reference file (e.g. _prot://path/to/ref.fa_) and returns the path to a corresponding index file (e.g. _prot://path/to/ref.fa.fai_). 
- If the index file is missing and the reference file is local, the index file is generated locally, in the same location as the reference.
- If the reference file or index file is remote, neither will be downloaded locally.
- If the reference file is remote and an index file cannot be located, **NULL** is returned and the user will see an error message.
2. The method `refs_load_fai` can now handle remote files, via `hFILE` pointers, and only tries to infer the name of the reference file starting from the index file, if a previous reference has not been provided (e.g. via `sam_open_format`).
3. **UR** …
=> Add support for remote reference files

htslib/hts.h, sam.c
Fixes oss-fuzz 20473
This also fixes the indexing tests forbidding samtools index on
gzipped or naked SAM and BAMs.  Previously the index command did not
fail, but gave broken indices.
Ironically with 1.10 samtools index on a totally raw uncompressed BAM
did actually start working (but not gzipped BAM or raw/gzipped SAM).
This was not by design and the indices produced couldn't be used by
1.9 and prior so it's safest to forbid this case too.
Also added documentation on the ambiguous "is_bgzf" field given this
is set for BAM files, even if ungzipped.  It's purely a flag on usage
of the bgzf_open/read functions, which can read uncompressed data, and
has nothing to do with the file format actually being BGZF.
=> Fixed nuances between gzip vs bgzf compressed files.

cram/cram_index.c, cram/cram_index.h, hts.c, htslib/hts.h
Remove the usage of `hts_pair64_max_t::max`, as the same value is already contained in `hts_reglist_t::max_end`.
Remove references to `hts_pair64_max_t` type.
=> Make the iterator work with 64 bit positions

htslib/sam.h
This has been copied over from the samtools sort_minimiser PR.
For now this is a macro to keep the code style consistent with all the
other bam_* macros.
Ideally we'd use a static inline, but if so I think this is a second
PR (or second commit) that rewrites all these macro-functions so we
have some level of consistency in code style.
=> Added bam_set_seqi function.

cram/cram_io.c, cram/cram_io.h
Occurs when block content_id is INT_MIN, which cannot be negated in an int.
Casting to uint32_t fixes the problem and allows checks for negative values to be eliminated.  Blocks with negative content_id will end up in different hash buckets, but that shouldn't matter as long as cram_get_block_by_id() is consistent with cram_read_slice().
Fixes oss-fuzz 20102
=> Fix integer overflow in cram_read_slice

bgzf.c, hts_internal.h, sam.c
Fixes samtools/samtools#1197
Fixes the bug which caused the auto-indexing (--write-index) code to produce different output when multi-threaded.  The difference being whether a BGZF virtual offset is the first byte of the next block or points to the end of the previous block.  Hence we'll no longer produce indices like this which gives data compatibility with older samtools releases.
Also fixed the bug which caused usual offsets pointing to the end of a block to be misinterpreted as hitting EOF in the bgzf file.  This gives compatibility with reading indices produced using multi-threaded auto-indexing using samtools 1.10.
=> Write index fix

htslib/hts_defs.h
Assuming that it's not the intention for `HTS_DLL_EXPORT` to be independently useful, this PR removes it and defines `HTSLIB_EXPORT` directly instead. This improves #1013 a bit, as there's only one macro to print out spuriously rather than two — see the discussion on that issue.
You may wish to squash this when merging, but it's presented as two commits because the individual diffs are understandable but the combined diff less so.
=> Define HTSLIB_EXPORT without using a helper macro

cram/cram_encode.c, sam.c, sam_internal.h
1. Use the same two bytes at a time approach (seq2nibble) already used
in CRAM for sequence.
2. Ensure the quality c = s+33 statement doesn't trigger any type
aliasing rules, permitting SIMD usage.
Benchmarks on 10 million NovaSeq records, reading from uncompressed
BAM (bgzf wrapped):
```
Read only: ./test/test_view -B /tmp/u.bam
8993715174      cycles                    #    3.541 GHz
18985281221      instructions              #    2.11  insn per cycle
2.540721616 seconds time elapsed
Read + write SAM (develop):
21910087899      cycles                    #    3.566 GHz
55089448827      instructions              #    2.51  insn per cycle
6.144628857 seconds time elapsed
Read + write SAM (this commit):
18882595700      cycles                    #    3.558 GHz
42301339830      instructions …
```
=> Improve SAM writing speed by ~30%

sam.c
Upon successful completion of `sam_hdr_create`, ownership of the newly created **SN** strings is given to `sam_hdr_t::target_name`, which takes care of freeing them at the end. But if an error occurs, the handover might fail and the allocated strings are missed by the clean-up routines. 
Fixes oss-fuzz 20888
=> [fuzz] Free allocated SN strings when encountering an error

Makefile, tabix.1, tabix.c
Check for error returns from bcf_itr_next(), hts_getline() and tbx_itr_next() so failures can be reported properly.
Add checks in other places that could fail, mostly memory allocations and writes to the output file.
Note that bcf_itr_querys() and tbx_itr_querys() return NULL for both general failures and those caused by the requested region not being present.  As tabix silently skips missing regions, it is currently not possible to detect errors in these functions.
=> Add more error checking to the tabix application

hts.c
Move the `free` call after the error checking.
Fixes #1033
=> Prevent a double free in case of failure

bgzf.c, hts.c, tabix.c
* Make `bgzf_read_block()` print more error messages, including the offset of the BGZF block where it failed.
Note that this introduces a small change of behaviour as block_address is now updated after an empty block has been read.  This may change the location stored in indexes of files with empty blocks.
* Make `hts_itr_next()` return an error on seek failure.
The return code needs to be less that -1, or the caller will incorrectly interpret it as end of data, causing it to silently finish too early.
* Fix missing newline in tabix error messages.
=> Report more BGZF errors

htslib/vcf.h, tbx.c, test/test-vcf-api.c, vcf.c
This is an extension of ea879e19b8 which added checks for reading
VCF.
Resolves https://github.com/samtools/bcftools/issues/1154
=> Prevent negative rlen on erroneous INFO/END when reading BCF

cram/cram_decode.c
Makes the error case decrement the reference count on any used refs and free the refs array.
While this fixes the case found by the fuzzer, `cram_decode_slice()` is a complicated function so it's possible other memory or reference count leaks still exist.  It would be a good idea for others to check to see if there are any obvious ones left.
Fixes oss-fuzz 21393
=> Fix memory leak on failure in cram_decode_slice()

hfile_libcurl.c, tabix.1, tabix.c
First commit adds a `--cache` option to tabix, set by default to a reasonably modest value (10 Megs; enough for at least 160 BGZF blocks).  This will mainly have an effect with the `-R` option, which can cause blocks to be accessed repeatedly, especially when the requested regions are close together.
The second attempts to reduce the number of backward seeks made by `hfile_libcurl` when the cache is in use.  Each seek causes a new web request to start, so they can be quite expensive and are best avoided.  Commit ad2e24f was an earlier fix that stopped a new request from happening on every single BGZF cache hit, however it wasn't a complete fix as `hseek()` [can discard a small amount of data](https://github.com/samtools/htslib/blob/0bff7c1/hfile.c#L472) from the hFILE buffer.  If this …
=> Add tabix --cache option; make bgzf cache work better with hfile_libcurl

bcf_sr_sort.c, bgzf.c, htslib/bgzf.h, htslib/hts_defs.h, htslib/kseq.h, htslib/regidx.h, htslib/vcf.h, synced_bcf_reader.c, tabix.c, vcf_sweep.c
A couple of stacked up trivialities:
* Use the newly-available `ks_expand()` to avoid kstring-related explicit `kroundup32+realloc` calls
* Tidy up inclusions of standard C headers from the public _htslib/*.h_ headers — in particular don't include `<assert.h>` from any public headers. (Verified that current samtools and bcftools still build after this change.)
=> Minor improvements and public header cleansing

header.c, test/sam.c
1. The length of PG chains is now computed and only chains with at least two PG lines are considered valid candidates for further extension.
2. PG linkage is redone before adding a new PG line.
Fixes https://github.com/samtools/samtools/issues/1235
=> [header API] Link a new PG line only to valid chains

hts.c, htslib/hfile.h, htslib/hts_endian.h
More collected minor items:
* Fix a buglet in the #917 check: this should be tested even if this is the first read on a new chromosome.
* Fix `-Wextra` warnings emanating from the public _htslib/*.h_ headers:
```
$ gcc-9 -c -Wall -Wextra includeall.c
In file included from includeall.c:4:
htslib/hfile.h: In function 'hwrite':
htslib/hfile.h:271:35: warning: comparison of integer expressions of different signedness: 'long int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
271 |         if (fp->limit - fp->begin < nbytes){
|                                   ^
In file included from includeall.c:7:
htslib/hts_endian.h: In function 'le_to_i32':
htslib/hts_endian.h:245:34: warning: operand of ?: changes signedness from 'int' to 'uint32_t' {aka 'unsigned int'} due to unsignedness of …
```
=> Collected minor issues: warning fixes, buglets

cram/cram_io.h, htslib/hts_endian.h, textutils_internal.h
A few more instances of dc3303b6da542f74c965b3f3f50a58776f87104b uncovered not quite in time for PR #1066.
My grepping suggests this now accounts for all the instances of this pattern in htslib.
=> Improve a few more instances of so-called navel gazing

cram/cram_decode.c
The already present check in `cram_decode_slice` did not account for the last byte. This has been corrected.
Fixes oss-fuzz 22231
=> Fix buffer overflow in hts_md5_update()

tabix.1
A _tabix.1_ companion to PR samtools/samtools#1248. In fact the [bfx.SE question](https://bioinformatics.stackexchange.com/questions/13282/vcf-merge-fails-due-to-tabix-not-producing-tbi-files) was about tabix indexes…
=> [manpage, minor] Mention TBI chromosome length limit

sam.c, test/test_str2int.c, textutils.c, textutils_internal.h, vcf.c
Dusting off another minor branch from a few months ago… This addresses most of the small warning improvements noted in passing on samtools/samtools#1158:
> There is room for improvement in the warning: it could give an indication of the line number in question and/or print out the problematic contig name (carefully, as this is potentially adversarial input); and there is a buglet (`s/tid/mtid/`) nearby (and a typo in the message).
To print out the contig name, the PR adds a hopefully armour-plated `hts_strprint()` utility function which formats user-supplied text truncated to a sensible length and with unprintable characters escaped. This may be helpful for printing out adversarial input elsewhere in htslib. Added some tests (which pass plain `valgrind`) to _test/test_str2int.c_ as it …
=> Improve SAM parser unrecognised RNAME warnings

cram/cram_index.c, cram/cram_io.c, cram/cram_structs.h, hts.c, htslib/hts.h
Fixes #1061
This appears to have been introduced during bfc9f0d and fixed for BAM only in 6149ea6.  The effect on multi-threading decoding for CRAM was significant.
This fix takes a totally different approach, which not only fixes the regression but passes it.  CRAM can do CRAM_OPT_RANGE queries, used by the single version of the iterator, which informs the decode of both start and end range positions.  When threading this means we don't preemptively decode the next container unless it'll actually be used. This same logic is now used in the multi-region iterator, although it's complex.
The general strategy is as follows:
- Ensure we know the next container start from index.  This needs a small tweak to cram_index struct as the next container isn't quite the same as this container + slice …
=> Fix the multi-threaded CRAM multi-region iterator regression.

cram/cram_structs.h, hts.c, htslib/hts_defs.h, test/test-regidx.c
Compiling htslib with GCC 10.1 or **trunk** produces:
```
hts.c: In function 'hts_idx_init':
hts.c:1714:59: warning: overflow in conversion from 'uint32_t' {aka 'unsigned int'} to 'int' changes value from 'idx->z.last_bin = 4294967295' to '-1' [-Woverflow]
1714 |     idx->z.save_bin = idx->z.save_tid = idx->z.last_tid = idx->z.last_bin = 0xffffffffu;
|                                                           ^~~
cram/cram_io.c: In function 'cram_dopen':
cram/cram_io.c:4493:9: warning: '__builtin_strncpy' specified bound 20 equals destination size [-Wstringop-truncation]
4493 |         strncpy(def->file_id, filename, 20);
|         ^~~~~~~
```
Compiling it with Clang **master** (the upcoming release 11) produces:
```
test/test-regidx.c:193:41: warning: implicit conversion from 'int' to …
```
=> Avoid warnings from recent and upcoming Clang and GCC releases [minor]

cram/cram_decode.c
We don't normally generate these features, using "B" instead.  However some hand crafted CRAM files have shown we didn't create the correct MD tag due to forgetting to clear the distance since last edit, giving rise to the last numeric in MD being high.
Eg: MD:Z:0A98T0 came out as MD:Z:0A98T98 if that last T edit was a "b" feature.
[0503_mapped.cram.zip](https://github.com/samtools/htslib/files/4805153/0503_mapped.cram.zip)
=> CRAM fix for MD tag generation with "b" FC.

cram/cram_codecs.c, cram/cram_external.c
Because of the missing `else`, `cram_codec_decoder2encoder` was erroneously returning **-1**, causing its caller method `cram_block_compression_hdr_decoder2encoder` to abort converting the other codecs from decoding to encoding. This resulted in uninitialized codec fields, which were subsequently used.
Fixes https://github.com/samtools/samtools/issues/1276
=> [CRAM] incomplete decode to encode conversion

cram/cram_decode.c
If we have lossy quality enabled and couple that with the use of 'B',
'q' or 'Q' features, CRAM starts off with QUAL being all 255 (as per
BAM spec and "*" quality) and then starts to modify individual
qualities as dictated by the specific features.
However that then produces ASCII quality <space> (q=-1) for the
unmodified bases.  Instead we use ASCII quality "?" (q=30), as per
htsjdk.  We use have quality 255 for sequences with no modifications
at all though.
NB: Neither htslib nor scramble can produce test data to demonstrate
this bug.  I used gdb to tweak the CF value (b cram_encode.c:2769 and
then set cr->cram_flags=0) along with using a SAM file using IUPAC
codes in the sequence.
See https://github.com/jkbonfield/hts-specs/blob/CRAM_tests/test/cram/passed/1003_qual.cram for a cram …
=> Set CRAM default qual for lossy qual modes.

sam.c
When RNEXT / PNEXT / TLEN are set to the uninitialised values (* / 0 / 0) the overlap_push function was escaping the overlap removal code.
We now still look for overlaps in this case.  It's not as efficient when it doesn't have these values as we can't optimise the case of detecting non-overlapping reads, but we do get the correct answer again.
Example BAM to demonstrate the issue:
```
@HD	VN:1.6	SO:coordinate
@SQ	SN:bar	LN:10000
foo	163	bar	503	60	20M	*	0	0	AAAAAAAAAAAAAAAAAAAA	FFFFFFFFFFFFFFFFFFFF
foo	83	bar	506	60	20M	*	0	0	AAAAAAAAAAAAAAAAAAAA	GGGGGGGGGGGGGGGGGGGG
```
=> Fix mpileup regression between 1.9 and 1.10.

htslib/sam.h, sam.c, test/sam.c
While recommending `bam_aux_update_str()` elsewhere, I noticed that it's interface was somewhat unfriendly as it required a NUL-terminated string, and the passed-in length had to include the NUL-terminating byte.  This PR removes that restriction in a backwards-compatible manner so that forgetting to count the NUL no longer creates an invalid tag.  As a side benefit, it becomes possible to create a tag from part of a longer string.
`bam_aux_update_str()` is made a bit more efficient, especially when replacing an existing tag, by reducing the number of `memmove()` calls used to get any following aux tags into the correct position.  It also calculates the new record size more accurately when resizing.
Includes more tests for tag growth and shrinkage, and fixes a (mostly) unrelated bug in …
=> Improve bam_aux_update_str()

htslib/kstring.h
Considering `kputs` is exposed as a public method and used extensively with data parsed directly from input files, it should check that its source string is not null.
Probably, a similar check should be implemented for `kputsn`, which has the potential of an undefined behaviour when calling `memcpy` with a null pointer.
Fixes oss-fuzz 23670
=> Check for null pointer in source string.

.gitignore, .travis.yml, Makefile, configure.ac, hfile.c, hfile_internal.h, hts.c, hts_internal.h, htslib/hts.h, plugin.c, test/plugins-dlhts.c, test/with-shlib.sh
Previously I was trying to avoid linking the `hfile_*.so` plugins back to `libhts`, probably mainly because I didn't want arbitrary numbers of libhtses in the address space at once — but of course `dlopen`'s reference counting prevents any such weirdness. Other reasons for not linking them to _libhts.so/.dylib/etc_ are:
* Avoiding plugins being tied to a particular libhts SOVERSION
* Especially if your main program (e.g. samtools) has libhts.a statically linked, avoiding needing to dynamically link to libhts at all and so avoiding needing to set `$LD_LIBRARY_PATH` or rpath or etc so that you can find libhts.so/.dylib
But there is a very good reason **for** linking them to _libhts.so_:
* Making programs that dynamically load libhts with the default `dlopen` flags on Linux able to use …
=> Link plugins against libhts.so/.dylib and fix dynamically unloading HTSlib

hfile_libcurl.c
Curl update curl/curl#5050 (pause: bail out on bad input) made curl_easy_pause() return an error if passed
a disconnected CURL handle.  In hfile_libcurl this could happen when libcurl_read() or libcurl_close() was called after all
bytes had been read; or all the time in restart_from_position().
Fix by checking for fp->finished in libcurl_read() and libcurl_close(); and by removing the curl_easy_pause() in restart_from_position().
Thanks to @jmarshall for tracking down the exact libcurl change that caused the incompatibility.
Fixes samtools/samtools#1254 (Trouble reading SRA CRAM files in Google Cloud buckets)
Fixes samtools/samtools#1284 (samtools view crashes reading from amazon s3 http url?)
=> Fix hfile_libcurl breakage when using libcurl 7.69.1 or later

htslib/vcf.h, test/test-vcf-api.c, vcf.c
Avoid crash for `bcf_update_alleles(hdr, rec, NULL, 0)`.
Updating a `bcf1_t` to have 0 alleles is not particularly meaningful, but it is a valid state as that's what bcf_init() and bcf_clear() produce. Hence it is a valid thing for bcf_update_alleles() to do too, so calling it with `nals==0` should not crash. Instead set `rlen` the same way that bcf_init() and bcf_clear() leave it. Fixes #994.
=> Fix minor issue 994: avoid bcf_update_alleles() crash

cram/cram_decode.c
This was caused by the fix in PR #1094.
The problem there was data without explicit quality scores being set
(CF data series with "preserve qual scores" not set) could be coupled
with explicit Q or q feature codes to add qualities at specific
sites.  Without quals, the default is "*" (a run of Q255), but we
can't just amend a few qualities here and there as that leads to a mix
of Q255 and Q-something-else.  We memset from Q255 to Q-something-else
the on the first explicit quality change.
The flaw is that this check is applied even on data where the
"preserve qual scores" CF value is set, but we haven't initialised the
quality string to all-Q255 in that scenario.
However it was totally harmless, as if we preserve quality scores,
then the entire array of quality values are then subsequently …
=> Fixed a (harmless) CRAM uninitialised data access.

cram/cram_io.c, hts.c, hts_internal.h
In https://github.com/samtools/samtools/issues/1242#issuecomment-627386086, @valeriuo wrote:
> A footnote: when running parallel jobs on a S3 file, it is advisable to download the index file in the current folder a priori, otherwise each job might try to do that independently, resulting in a corrupt index file.
This is a pretty tragic bug in the index downloading — instead it should use the same technique as the CRAM reference code does to download into a unique temporary filename and atomically `rename()` the file into place at the end.
This PR extracts filename uniquification into a new `hts_open_tmpfile()` function declared in _hts_internal.h_ and uses it in the two places where files are currently downloaded and saved as a byproduct of htslib operations. (Are there any others?)
No …
=> Download index files atomically in idx_test_and_fetch()

htslib/sam.h, sam.c
For the purposes of indexing, maybe for (somewhat invalid) alignment records whose CIGARs consume no reference bases htslib should consider them to have length 1 — similarly to reads that are unmapped or have no CIGAR string at all.
Thus they would be considered to cover one reference position (rather than zero), and would be returned by iterator-based queries. See for example samtools/samtools#1240, in which alignment records with CIGAR=`66P` are used to represent something somewhat different from mapping to a reference.
This may or may not be a good idea, but it would mean that htslib/samtools would do something more sensible for these records (even though they do not represent a traditional mapping).
=> Maybe consider alignments which consume no reference bases to have length 1

Makefile
This was missed during PR #1035.
It's still a back burner project to update my script for checking these to deal with the `../` added in #1078, but for now: also verified that all necessary `#include "../etc"` relative paths are correct in htslib source code; and also that there's no missing dependencies in current **develop** on samtools or bcftools.
=> Add missing Makefile dependency [minor]

bgzf.c, faidx.c, hts.c, htslib/bgzf.h, htslib/faidx.h, htslib/hts.h, htslib/kstring.h, htslib/regidx.h, htslib/sam.h, htslib/synced_bcf_reader.h, htslib/tbx.h, htslib/vcf.h, htslib/vcf_sweep.h, sam.c, synced_bcf_reader.c, vcf.c, vcf_sweep.c
This PR adds struct tags so it's possible to write e.g. `struct htsFile` to forward declare htsFile as an incomplete struct in circumstances when you'd rather not `#include <htslib/hts.h>`, thus fixes #1106.
Presented as separate commits in vaguely increasing order of theoretical API compatibility issues:
* Adds tags where there weren't any before — no issues.
* Removes `aux_key_t` which was accidentally added and never used in HTSlib.
* Renames reserved-to-the-compiler tags such as `typedef struct __bgzidx_t bgzidx_t` — third party code could conceivably have been using these tags but as they start with underscores users should have …uh… been expecting undefined results.
* Renames `variant_t` to `bcf_variant_t`. This struct is used only as the type of a field within `bcf_dec_t`, which …
=> Add struct tags to htslib/*.h public typedefs

sam.c
We call constructor and destructor for each new bam object that is added to and removed from the pileup.  Pileup also takes its own copy of the bam1_t struct as sam_read1 loops may be using the same structure over and over again.
However the constructor was called with the passed in bam1_t instead of pileups own copy of it (unlike destructor).  Hence anything the constructor attempts to cache, such as the location of an aux tag, may get written over.
=> Bug fix to the pileup constructor.

htslib/kroundup.h, htslib/kstring.h
This PR is an alternative solution to https://github.com/samtools/htslib/pull/1119. Instead of pushing the `free` call inside the HTSlib compiled code, this solution brings `realloc` back to the inline function `ks_resize`, so that it can be directly called by the upper layer.
To minimize the number of CPU instructions generated for `ks_resize`, the round-up to a power of two has been replaced with a simpler approach to increase the string size with 1.5 X requested size. It's the same strategy used by the MS C++ runtime when increasing the capacity of a `vector`.
Fixes #1114
=> Have realloc and free in the same layer of kstring

kstring.c
NB: This never made it into a release so it isn't an ABI breaking change and nor does it need to be listed in the NEWS file.
=> Remove now unused ks_resize2 function.

vcf.c
Verify that the BCF input is within the length of its assigned type.
Fixes oss-fuzz 25533
=> [fuzz] Check against the actual type lenght

.gitignore, Makefile, kfunc.c, test/test_kfunc.c
As reported in arq5x/bedtools2#855 (bedtools contains a lightly-modified copy of htslib's _kfunc.c_). This backports PR arq5x/bedtools2#856 and adds test cases.
When some of `kt_fisher_exact()`'s input arguments are very large, `hypergeo(…)` is dominated by the subtracted `lbinom()` so returns `exp(≤ -750)`, which underflows, hence `hypergeo()` returns 0.0.
When `q` is 0.0, `kt_fisher_exact()`'s loops never execute and which of `i` and `j` is closer to `n11` is indeterminate. Hence we handle the adjustment of `left`/`right` separately in this case.
The `n11 + n22 < n12 + n21` test in that additional handling is motivated by [this description of left/right](https://www.langsrud.com/fisher.htm#INTRO) and agrees with the implementations in R and SciPy for various test cases, but this …
=> Account for underflow in kt_fisher_exact()

NEWS
Sorry for not getting to proofreading #1136 yesterday before it was merged…
Some minor updates. Reword `tabix --separate-regions` description. Fix PR#1094 text — the
original has `<space>` in the description (edit the PR comment to see it). Credit @lczech. Trivial formatting fixes. My spelling mistakes PR is surely too trivial to mention :smile: — it's fairly automatic from some wrappers around [codespell](https://github.com/codespell-project/codespell.git).
=> Minor NEWS formatting etc updates

htslib/vcf.h
This undoes a change in #1060.
It's a philosphical point.  On one hand we have an inclusion of a
spurious file that we do not utilise ourselves.  On the other hand we
have an API breakage where old software (in this case bcftools 1.10)
attemting to compile against current htslib no longer succeeds because
we've changed which symbols we declare.
This is unclean, but I think backwards compatibity trumps tidyness in
this case.
=> Add back assert.h to vcf.h.

hts.c
Include unistd to guarantee access to R_OK definition.
On a mac (Xcode 11) - **when compiling via rust-htslib** - I get a compile error about missing R_OK. As far as I can tell R_OK is defined officially in unistd.h, but probably comes in via other includes.
htslib by itself compiles fine on my mac - so I realise this is not specifically a htslib problem - presumably papered over a bit by the autoconf system.
The only other spot in htslib that used R_OK does include unistd (cram/cram_io.c)
=> Add unistd.h include to hts.c now that it used R_OK

htslib/sam.h, sam.c, test/plugins-dlhts.c, test/test-vcf-api.c, test/test_index.c, test/test_kstring.c, test/test_realn.c, test/test_str2int.c, test/test_view.c
Similarly to PR #1143, _sam.c_ also needs `<unistd.h>` explicitly for environments in which it doesn't get it via `<zlib.h>` or similar.
Both _htslib/sam.h_ and _test/test-vcf-api.c_ use `errno` but get it only semi-accidentally via _htslib/kstring.h_. Include `<errno.h>` explicitly, and similarly `<string.h>` for `strerror()`.
Various _test/*.c_ programs that use `getopt()` need include only `<unistd.h>` rather than `<getopt.h>`, which is needed only for `getopt_long()`.
All uncovered by building in an environment with dummy `<zlib.h>` and `<getopt.h>` headers that don't `#include` any other headers or define anything extraneous, and temporarily commenting out `#include <errno.h>` and other `errno` usage in _htslib/*.h_.
=> Include <unistd.h> and <errno.h> directly where needed

hts.c
This code detects when the end positioni s too large for the current
index.  It then computes an adjusted n_lvls parameter and tells the
user to switch to CSI with this parameter.
That has numerous failings though.
1. The only user-adjustable parameter is min-shift, not levels, so
the advice is impossible to follow.
2. CSI auto-scales based on SQ headers, so we don't need to be
explicit anyway (assuming we currently have a BAI index that doesn't
fit).
3. If we already were using CSI index and if we did have the
configuration options to do what it asks, it wouldn't fix the problem.
Given CSI auto-scales, if we see this message it's because of the
alignments don't match the headers; either the header has been
replaced by something inappropriate or there are bugs in the aligner
that has …
=> Replace the indexing range check error message.

.appveyor.yml
Mainly to fix pacman, which broke following changes to msys2 packaging (see https://www.msys2.org/news/#2020-06-29-new-packagers)
Prior to this we were using the default image (Visual Studio 2015) which has not had the necessary updates to make pacman work.
Replaces and closes #1166
=> Update Windows image version in .appveyor.yml

hts_os.c
Note: this function is never used.  It was only added for reasons of completeness when we were putting in hts_drand48, used by htslib/ksort.h.
=> Fix a long-standing typo in hts_lrand48.

.cirrus.yml
This is a replacement for Travis, but it doesn't remove it (yet) so we can compare side by side for a while.  Compared to Travis is lacks the s390x test.
However we have gcc:latest (Debian),  clang (via ubuntu:devel) and MacOS X (clang only).  The mix of maintainer-checks, with/without config, libdeflate, pedantic and address sanitizer are sprinkled across the various environments so we don't have a huge matrix.  We also test libdeflate integration from local source (Debian, MacOS) and from OS installed package (Ubuntu).
Everything launches in parallel bar the 2nd MacOS X instance as it appears we're limited to just 1.
Other possibilities could include pretty much anything on docker-hub, so we could consider 32-bit builds if we feel it's worth it.
That also means we have the potential for …
=> Add Cirrus-CI integration

cram/cram_codecs.c, cram/rANS_static.c, hts.c, tabix.c, test/test_index.c, textutils_internal.h
[A trivial one that's been in a holding pattern since before the 1.11 release…]
Add comments indicating intentional fall-throughs, so that `gcc -Wextra` builds don't need `-Wno-implicit-fallthrough` as well.
(Clang understands only not-yet-standard attributes and annotations, not comment text, so there's little point in catering to its `-Wimplicit-fallthrough` warning, which isn't included in `‑Wall`/ `‑Wextra` in Clang.)
=> Prevent switch/case statement "fall through" warnings [trivial]

htslib/sam.h
`bam_itr_next` now sets the `data` argument of `hts_itr_next` to the BAM file pointer (of `htsFile *` type).
Fixes #1179
=> Fix the data pointer of hts_itr_next.

bgzf.c
The assumption is that we call bgzf_idx_flush once per outgoing multi-threaded block, and the block numbers will match.  The assertion is to validate we're not indexing out of order.
However, very long records (eg with huge aux tags or long seqs) can mean a single record spans multiple blocks and we inherently then skip blocks in bgzf_idx_push calls.  Hence the assertion is simply wrong.
Fixes samtools/samtools#1328
=> Removal the bgzf_idx_flush assertion.

Makefile, config.mk.in, configure.ac
This extra level of indirection, similar to that used in samtools's _Makefile_, simplifies making additions to the CPPFLAGS used during compilation (and simplifies ensuring that it's done without interfering with the user's setting for `$CPPFLAGS`).
e.g. this will let #1170 add `-DHTS_CPPFLAGS=\"$(CPPFLAGS)\"` to `ALL_CPPFLAGS` without needing any `TMP_CPPFLAGS := $(CPPFLAGS)` trickery or questions about `:=` vs `::=`.
Also fix related typo in the MSYS/MinGW part of configure.ac.
=> Minor build infrastructure: introduce $(ALL_CPPFLAGS) and use it

tabix.c
Previously, the default format configuration (`-p`) would overwrite the independent configuration settings, particularly the number of lines to be skipped in a file (`-S`), which is not tied to the format.
Now, the number of lines to be skipped can be set independently of the format.
Fixes #1186
=> [tabix] Set the number of lines to be skipped independently

htslib/vcf.h
There is a small typo in htslib/vcf.h.
Should read `separated` rather than `seperated`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, seperated -> separated

.gitignore, configure.ac
As detected in [Debian bug 978835](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978835), HTSlib's _./configure_ fails when built with autoconf 2.70 (released in December). It is a byproduct of [autoconf 2.70 being more careful about cross compilation](https://lists.gnu.org/archive/html/autoconf/2020-12/msg00002.html):
> *** More macros use config.sub and config.guess internally.
>
> As a consequence of improved support for cross compilation [snip]
Using the standard `$host_alias` variable name in our shared library check was fun and intended to be mostly already correct if we moved to using `AC_CANONICAL_HOST` at the top of the configure script, but causes problems when autoconf 2.70 implicitly uses `AC_CANONICAL_HOST` below our check. The simple fix is to use a variable name that's …
=> Fix configure.ac buglet when used with autoconf 2.70

sam.c
When encountering a new CIGAR segment, the index `icig`, which indicates the position of a base inside the current segment, has to be reset. This fix changes the reset value to **-1** (instead of **0**), so that the next first matching base starts from `icig=0` in the calling method (`tweak_overlap_quality`).
Replaces #1196
Fixes #1195
=> Fix the iteration over the CIGAR segments

hts.c
This bug was introduced during #1181 where the additional
HTS_OPT_FILTER meant the automatic fall-through from
HTS_OPT_COMPRESSION_LEVEL no longer applied.
I decided against continuing the previous obscurity of moving
HTS_OPT_COMPRESSION_LEVEL to the end of the switch and having no
return (thus falling into the cram_set_voption call), instead
favouring an explicit call.
An example command that demonstrated the problem was:
samtools view -O cram,level=1 in.bam -o out.cram
=> Renable changing CRAM compression level via hts_set_opt.

cram/cram_codecs.c, cram/cram_io.c
- Fixed buffer overflow in XPACK codec (security)
Now protects against overflow of rmap[i].
Fixes oss-fuzz 29827
- Add "cp_end" arg to varint_get* funcs in cram_varint_decode_init so
reading beyond the buffer can be spotted.
Fixes oss-fuzz 29837
- Set b->uncomp_size for FQZ decoder.  Already done in other codecs,
just accidentally missed here.  Without it, it invalidates the
boundary check in int32_get_blk.
Fixes oss-fuzz 29855
Fixes oss-fuzz 29908
- Fixed memory leak in XDELTA when recovering from malformed data stream.
Fixes oss-fuzz 29858
=> More OSS-Fuzz detected fixes

INSTALL
Use the current canonical option rather than the `--recursive` alias; there doesn't appear to have ever been a `-r` short form for this.
=> INSTALL: Spell out git clone --recurse-submodules option [minor]

vcf.c
The specification says REF must be present, so reject reads that do not have one.  Fixes a crash reported in bcf_sr_sort_set() which expects REF to be present.
Fixes samtools/bcftools#1361 (bcftools merge segfault when REF and ALT are unset)
=> Reject VCF/BCF records with no REF allele

cram/cram_codecs.c
Gcc 10 when using -O and -fsanitize=address produces a warning about
mallocing some insanely large amount of memory.
This is an impossibility given the limits on the sizes of some data
values, but gcc doesn't know this and is assuimng variables may wrap
around and go negative.  Using an unsigned type stops it from
exploring the inaccessible data ranges.
=> remove a strange gcc10 warning.

cram/cram_codecs.c
- Add bounds check in cram_const_decode_init.
I've checked and this is the only use of the varint decoders that
didn't have a bounds check.  Suitably sniffed out by the fuzzer.
Good fuzzer!
Fixes oss-fuzz 30012
- Free the sub-encoding when initialising XRLE encoding fails due to
malformed streams.  This removes a tiny memory leak.
Fixes oss-fuzz 30014
=> Fix more OSS fuzz reported issues.

cram/cram_decode.c
This is an old bug, but only recently picked up by the fuzzer.
Fixes oss-fuzz 30105
=> Remove small memory leak when decoding malform slice header.

cram/cram_codecs.c
As with recent changes to XPACK and XRLE, it now ensures the sub-codec
is also properly freed too.
Fixes oss-fuzz 30164
=> Remove small memory leak when decoding malformed XPACK encoding.

Makefile, htscodecs_bundled.mk, htscodecs_external.mk
- Fix an overflow bug in the unstripe function
Fixes oss-fuzz 30087
- Move some duplicated code to a new htscodecs/utils.h header
- Updates htslib Makefile infrastructure for the new htscodecs header
=> Pull in htscodecs changes and update Makefile

cram/cram_codecs.c, cram/cram_io.c, hts_expr.c, kstring.c, test/test-vcf-api.c, test/test-vcf-sweep.c, vcf.c
Fixes a number of warnings from running the tests on HTSlib built with clang 10.0.1 and -fsanitize=address,undefined
These fix "runtime error: applying zero offset to null pointer" warnings:
- Make `kvsprintf()` allocate some memory before trying to write a string into it
- In CRAM, always allocate memory for CIGAR data in slices
- Rearrange `cram_byte_array_stop_decode_block()` so it won't try to do maths on a NULL pointer
- Fix check on `bcf_get_format_int32()` return value in test-vcf-sweep so it doesn't try to work on a non-existent tag
- Fix dubious pointer comparisons in `bcf_update_alleles()`
- Ensure `bcf_read1_core()` always allocates memory for `rec->indiv.s` and `rec->shared.s`
Fixes for integer overflows:
- Prevent overflow of some elements in the `cram_metrics::sz` array
- …
=> Undefined behaviour fixes

Makefile
When building libhts.dylib, the  compatibility_version and current_version were not being set in the way documented by
Apple - notably they expect current_version to be from the same sequence as, and greater than compatibility_version. See:
https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html
Change the values so current_version is related to the current HTSlib version, and compatibility_version the last one that
introduced a backwards compatible change.  As earlier HTSlib releases set compatibility_version to 3, we prepend '3.' to
these numbers so programs linked to earlier versions will still work with libraries built after this change.  This will be removed on the next ABI-changing update …
=> Change MACH_O compatibility and current versions

.gitattributes, Makefile, configure.ac, htslib.mk
Small updates for build / release:
- Update `.gitattributes` to keep `.cirrus.yml` out of release tar files
- Add targets to `htslib.mk` so HTSlib's `distclean` and `check / test` can be run from packages that embed it (e.g. SAMtools / BCFtools).
- Clarify that the htscodecs submodule is part of htslib in messages printed when it's missing, so it's easier to see what needs to be updated when building SAMtools / BCFtools with HTSlib embedded.  Fixes samtools/samtools#1364.
=> Assorted build updates

.appveyor.yml, .cirrus.yml, INSTALL, README.md
autoconf 2.7 requires use of `autoreconf -i` for the AC_CANONICAL_HOST macro, which is pulled in by AC_FUNC_MMAP.
Update CI configuration to use this, and change the instructions in the INSTALL and README.md files to match.
Fixes AppVeyor builds, which have stopped working since they upgraded to autoconf 2.71
=> Change CI scripts to use "autoreconf -i" and update docs

vcf.c
Fixes https://github.com/samtools/bcftools/issues/1414
=> Allow a "remove tag" operation followed by an "add the same tag"

test/formatcols.vcf, vcf.c
The trick used in bcf_hdr_parse_sample_line() to rapidly find tabs and newlines could be defeated by UTF-8 characters outside the Basic Latin range on platforms where "char" is signed (like x86).  It's currently not clear if VCF intends to allow these, but the [4.3 specification does allow UTF-8](https://samtools.github.io/hts-specs/VCFv4.3.pdf#subsection.1.2) and it's easy enough to support.  Fix by casting to unsigned when making the comparison.
Modifies formatcols.vcf to include a UTF-8 character for a round-trip test.
Fixes samtools/bcftools#1408
=> Fix reading UTF-8 encoded sample names when char is signed

htslib.mk
I noticed these were still missing when adding more `*-all` targets to SAMtools following #1230.  With them, it will be possible to access most of the useful `*clean` targets when building HTSlib at the same time as SAMtools/BCFtools.
=> Add mostlyclean-htslib and testclean-htslib targets to htslib.mk

bgzf.c, hts.c, htslib/hts.h
Diagnosing samtools/samtools#1387 was hindered by `htsfile` identifying what was actually an obsolete RAZF-compressed file as plain gzipped. This patch adds basic support for recognising RAZF, similarly to how ef0b40d673bf3c3a0fe2080c448b4981c4784bae added basic recognition for bzip2 compression.
```
$ htsfile human_g1k_v37.fasta.gz 
human_g1k_v37.fasta.gz:	FASTA legacy-RAZF-compressed data
```
(RAZF is an obsolete predecessor to BGZF, and is similarly a variant of GZIP using an extra header field. It also adds a trailing index table.)
Adding this `htsCompression` value does not affect `bgzf_read_init()`'s detection of BGZF vs plain-GZIP; RAZF remains treated as `is_gzip` and the trailing index table is not handled well, leading to problems
if you try to decompress such a legacy file with …
=> Recognise legacy RAZF compression

INSTALL, Makefile, hts.c, htscodecs_bundled.mk, htscodecs_external.mk, htslib/hts.h, test/test_introspection.c
Updates the htscodecs submodule and updates dependencies for the new header files.
Adds Makefile infrastructure to build and clean up the htscodecs/htscodecs/version.h file, for git checkouts only. Release tarballs will ship with a pre-built copy of this file.
Fixes issue where the Makefile rules to test if the submodule is missing would cause missing source files to be silently ignored. They now run a recipe to check for the target, and suggest updating the submodule if it's missing.
Makes hts_version() report the submodule version along with its own.
Adds documentation for the '--with-external-htscodecs' configure option to INSTALL.
=> Update to htscodecs release 1.0

bgzf.c
Detected by making an RAZF file, but it could also leak on failure to create the cache.
Fixes oss-fuzz 31665
=> Fix leak of uncompressed_block on bgzf_read_init() error

synced_bcf_reader.c
This could happen with e.g. with `bcftools view -t` when the
last record in a chromosome block has the same coordinate as
the first record in the chromosome block that follows.
Fixes https://github.com/samtools/bcftools/issues/1441
=> Fix a bug where target regions could miss the first record

cram/cram_io.c
Er… I only just got around to actually reading this message… :rofl:
I've long been vaguely squicked by the first line ending mid sentence (makes it hard to glance at the message and get the gist), and I've only just noticed the slightly unfortunate “archival of data”.
This changes
```
./test_view  -t auxf.fa -C -o VERSION=3.1 auxf#values.tmp.cram.cram > auxf#values.tmp.cram
[W::cram_set_voption] CRAM version 3.1 is still in draft and is subject to
change. Please consider this a technology demonstration and do not use for
long term archival of data.
```
to
```
./test_view  -t auxf.fa -C -o VERSION=3.1 auxf#values.tmp.cram.cram > auxf#values.tmp.cram
[W::cram_set_voption] CRAM version 3.1 is still a draft and subject to change.
This is a technology demonstration that should not be used for …
```
=> Improve "CRAM version 3.1/4.0 is still draft" wording

NEWS, header.c
Some applications add supplementary **ID** tags to a header `@PG` line. This change prevents the corruption of the proper (first) **ID** value of a `@PG` line, when other unrelated **ID** tags are present.
Fixes   https://github.com/samtools/samtools/issues/1393
=> Prevent corruption of the ID value of a PG line

htslib/sam.h
A few typos and a missing argument from a function call.
=> Minor corrections in comments

vcf.c
When viewing a VCF file with a header containing duplicate sample names, the resulting error message prints the entire sample name list. This change limits the display to only the duplicate sample name.
Fixes  https://github.com/samtools/bcftools/issues/1451
=> [vcf] Display only the duplicate sample name, not the entire list

bgzf.c
These trip on with zlib-ng as the worse case expansion is 9-bits per byte (at level 1 only).  The test is done on opening a file, which seems strange.
We could do the check on opening for write only, but it seems more productive to error only when we actually can't fit the data rather than just incase it may if given truely random input.  Our real data doesn't seem to trigger this.
TODO: if we ever actually find genuine data that trips this up, then consider resetting level to above 1 and trying again, so the error is handled rather than exiting.
The worst case I could find on any of our data files was an ONT BAM file with high randomness in quality values, leading to 57k blocks at level 1.
Fixes #1257
=> Remove compressBound assertions.

INSTALL, configure.ac
This addresses a _configure_ issue and configure option documentation omissions from _INSTALL_ uncovered by #1261:
* Unlike the checks for other libraries, the libcurl check validated only that the link library _libcurl.so/.dylib/etc_ is available, but did not validate that the headers are available. In the #1261 case, inconsistent LDFLAGS and CPPFLAGS settings meant that the link library was available to the linker but the headers were not available to the compiler, which should have been detected at configure time.
(It's not recorded in the commit messages, but I think the other `AC_CHECK_HEADER`/`AC_CHECK_LIB` checks may have been written thus precisely so that such environment variable problems could be detected.)
* The default behaviour of `--enable-libcurl` was not documented in …
=> Add curl/curl.h configure check and improve INSTALL

vcf.c
The method that reads the VCF header (`vcf_hdr_read`) checks for missing contings and, if it detects any, tries to add them to the header from the index. However, a side effect of this operation was the unnecessary downloading of a remote index file. With the current change, the index file is only streamed into the memory.
Fixes #380
=> [vcf] Do not download the index file by default, when reading the VCF header

cram/cram_codecs.c, cram/cram_encode.c, cram/cram_io.c
Samtools cat utilises low level APIs to turn codecs from a read cram_fd to codecs sutiable for a write cram_fd.  This had a missing initialisation in the HUFFMAN code and a small memory leak, caused by the addition of the CRAM v4 code (but affecting CRAM v3).
Also while adding CRAM v4, the EOF block was changed from being a literal string of bytes into simply encoding an empty container and letting the code auto-generate the correct byte stream.  There were bugs in cram_encode_compression_header for empty blocks, which affected cram blocks that had gone through this read/write transcode process.  Specifically the compression header's num_record check is invalid as this is only populated for CRAM v1.0.  We check the container instead, which is always correct and permits us to find the …
=> Fix to make samtools cat work on CRAMs again.

sam.c
my analysis shows that it is possible to achieve double freeing of memory. to eliminate it, I propose a simple fix.
=> fix for double freeing of memory.

sam.c
Currently it always chooses the second sequence (except for the circumstance of differing base calls).  This is essentially random strand and random coordinate in most library strategies, but some targetted sequencing methods have a very strong strand bias (first is + strand, second is - strand) or positional bias (eg PCR amplicons). Given SNPs near the end of sequences can give rise to poor BAQ scores, both position and strand bias are detrimental.
This change makes it select either read 'a' or 'b' based on a hash of the read name.  Unlike using a traditional random number generator, this gives it consistent behaviour regardless of how many sequences have gone before.
An example from SynDip region 1:185M-200M:
```
No overlap removal:
SNP          Q>0 /   Filtered
SNP   TP   18830 / …
```
=> Make mpileup's overlap removal choose a random sequence.

htslib/synced_bcf_reader.h, synced_bcf_reader.c
It seems `bcf_sr_set_regions` ought be called before `bcf_sr_add_reader`. However, if a user unaware of this calls `bcf_sr_set_regions` **after** `bcf_sr_add_reader`, they are met with a failing `assert()`. This is particularly odd, as `bcf_sr_set_regions` already contains a useful error message about exactly this usage error.
This patch reorders the check for incorrect usage and the assert(), so that if an API user stuffs up the order of the calls, they get the nice message that already exists and not an assert().
I'm not sure if the assert() is even needed here, and probably is best replaced with a nice `hts_log_error()` in any case. I think
`readers->regions != NULL` only when either `bcf_sr_add_reader` or `bcf_sr_set_regions` has already been called, but I'll leave this in the …
=> Prevent assert() in bcf_sr_set_regions

cram/cram_codecs.c
Assumption: this is a gcc-11 warning, but I cannot be sure as I don't
have a local install.
cram/cram_codecs.c:1916:19: error: 'cp_end' may be used uninitialized [-Werror=maybe-uninitialized]
1916 |             cp += c->vv->varint_put32(cp, cp_end, zigzag16(c->u.e_xdelta.last));
|                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cp_end is initialised, but due to the malloc potentially returning
NULL, the initialisation of cp_end will have undefined behaviour if
the malloc fails.  The code does then check for NULL malloc and exits,
but the compiler generated code appears to have at least one path
which doesn't initialise cp_end due to this undefined behaviour.
(Unknown if a reachable path, but it's unlikely.)
=> Fix undefined behaviour in cram_xdelta_encode_char.

tabix.c
Extremely minor clarification I noticed while [answering this question](https://bioinformatics.stackexchange.com/questions/15842/use-htslib-to-extract-specific-region-of-vcf-file).
Both `tbx_itr_destroy()` and `bcf_itr_destroy()` are currently just aliases for `hts_itr_destroy()`, so this doesn't matter much except insofar as this code is useful example code.
=> Use bcf_itr_destroy() with bcf_itr_querys() [minor]

hfile_gcs.c
this is my attempt at introducing the ability for HTSLIB to access files in Google Cloud Storage buckets that have enabled [requester pays][0].
To enable requester pays, one will need to export the additional environment variable along with `GCS_OAUTH_TOKEN`:
GCS_REQUESTER_PAYS_PROJECT=my-project-name
[0]: https://cloud.google.com/storage/docs/requester-pays
=> + introduce GCP requester pays bucket access

htslib/kseq.h
The new uninitialised memory checking in gcc 11 is tripped up as it thinks there may be overflow cases in ks_expand meaning the resized buffer still isn't large enough.  We have already fixed this in kroundup.h, but it's not sufficient to silence it.
However adding an explicit check to spot if kroundup32 has overflowed is enough to silence it.
NB: this gcc 11.1 issue wasn't visible from within Htslib, but Samtools tickled it in samtools/dict.c.
Fixes #1283
=> Silence a gcc 11.1 warning with kseq.

vcfutils.c
1. Fixes a bug, which caused the iteration over the alleles to stop too early, due to a hidden updated of allele number.
2. Marks removed alleles as proper 'missing'.
3. Does the lazy unpack automatically, in case the user forgot to do it beforehand.
Fixes #1259
=> [vcf] Improve method `bcf_remove_allele_set`

cram/cram_codecs.c, hfile.c
Fixes for a couple of issues detected via cppcheck:
* Knet Must Die, but until it does the new `knet_open()` and `knet_dopen()` stubs probably shouldn't crash every time the underlying open fails;
* Fix `cram_xdelta_decode_init()` error handling memory leak. I assume passing in `option` as `E_SINT` or `E_SLONG` is not supposed to happen…
=> Fix crash in knet_open() etc stubs and minor memory leak

cram/cram_io.c, cram/cram_structs.h
Unsorted data is recognised by the rapid change in reference ID giving
rise to many tiny slices.  A flurry of this switches to unsorted mode
where we use the RI data series to store sequences from multiple
references in the same slice.
Unfortunately this also skews the cram data series metrics, which look
at average compression ratios for a variety of codecs, as the first
few slices may be tiny and the optimal codec isn't chosen
(initially).  Eg picking rANS0 for qualities as the buffers are tiny,
while rANS1 would be better.
Io_lib/scramble has a solution which resets the compression metrics on
detection of unsorted data.  This works, but here I try a more general
and hopefully stable approach which is to look for unusually very
large fluctuations in data series sizes.
=> Improve compression metrics for unsorted files.

NEWS, hts.c, htslib/hts.h
Adds new method `hts_idx_nseq`, which returns the number of covered contigs from an index structure.
~~Exports methods `hts_idx_getfn` and `hts_idx_locatefn`, which were previously internal.~~
Fixes a bug introduced by 18305510d010aab54706fe4abec4d90cd6462ecc. Older indices might encode missing entries with a 0, but the entries at the beginning of the linear index could contain 0 as a valid offset and, as such, are no longer considered missing. Thus, the linear index update from right to left stops at the first non-0 entry.
=> [index] New methods and a linear index fix

sam.c
Our error checking for kputw/kputc failing also wrongly claimed that the empty string was also a failure.
I considered returning "*" for empty, but it's not really true as in SAM formally that is unknown.  (Although genuine unknown would be considered to be empty, so maybe it's the same thing.)
To check for not-something, use e.g.
samtools view -e 'cigar!="" && cigar!~"D"'
Fixes samtools/samtools#1445
=> Fix the filter expression "cigar" on unmapped reads.

version.sh
Fix a bug in the separate build directory handling: `version.sh` reported the master release version rather than a git commit description when run from a separate build directory.
=> Make version.sh work from a separate build directory

NEWS
Please take a look for errors, omissions or entirely fictional updates.
This will be kept updated until we are ready for a release.
=> Summer 2021 NEWS update

NEWS
Fixes a bug with name tokeniser and variable number of names per slice.
Adds NEWS items.
=> Update htscodecs module to release 1.1.1

sam.c
For your amusement at this time, here is a PR that implements `endpos` as a filter expression, in response to <https://twitter.com/gringene_bio/status/1412686733225857024>.
See also the companion documentation PR samtools/samtools#1464.
"endpos" is the (1-based inclusive) position of the rightmost mapped base of the read, as measured using the CIGAR string. (`bam_endpos()` returns 0-based exclusive, which is the same thing.) For unmapped reads, it is the same as "pos".
=> Add "endpos" filter expression

NEWS
After a recent decloaking in google/oss-fuzz-vulns@8020f97eb86f46f4ca213d2bfcffcaa6491bbd38, it seems [CVE-2020-36403](https://nvd.nist.gov/vuln/detail/CVE-2020-36403) was recently allocated to represent the issue fixed in 1.11 by PR #1104. (That's the only one from that batch of oss-fuzz items that has acquired a CVE number.)
This PR continues the practice of mentioning non-spurious HTSlib CVEs in the _NEWS_ file :smile:
=> Update NEWS to add CVE number for 1.11's VCF parser fix

thread_pool.c
The tpool_worker threads have a check on
&& q->qsize - q->n_output > p->tsize - p->nwaiting
This is to ensure that all waiting threads have sufficient room to write their results to the output queue, so if they all start up, there's room.
However, when flushing, we need to leave a bit more leeway.  It's possible that we haven't yet consumed the results, so the output queue is full, meaning the flush isn't something that we can call and just wait on unless we have a separate thread that is able to drain the queue.  (This is valid for SAM and BAM, but not CRAM where the result consumer is also the same thread that calls the flush).
Hts_tpool_process_flush attempts to fix this, albeit with an ironic comment of "Shouldn't be possible to get here, but just in case".  It can, and it matters, …
=> Work around a deadlock in hts_tpool_process_flush.

README.md
There was a suggestion to update the document about the tabix on the htslib RPM package on Fedora project.
https://src.fedoraproject.org/rpms/htslib/pull-request/4
The tabix creates .tbi/.csi by indexing other file formats.
Note `[skip ci]` is a mark to skip Cirrus CI used in this repo. You can see <https://cirrus-ci.org/guide/writing-tasks/>.
=> README.md: Update for tabix. [skip ci]

sam.c
The SAM specification explicitly states the type for this tag is
CG:B:I.  However Htsjdk (sometimes or always?) writes these tags as
CG:B:i.  Htslib then silently ignores the tag, assuming it's some
unofficial (and incorrect) abuse of an uppercase tag for some local
purpose.
Given that there is data published in the wild using the incorrect
data type, it would be less problematic for us to simply handle the
incorrect value sign than the minimal risk of misinterpretting
someone's private tag data as CIGAR. (Plus they'd bring such woe onto
themselves by using the official name-space.)
Fixes samtools/samtools#1477
See also https://github.com/samtools/htsjdk/issues/1560
=> Make bam_tag2cigar's CG tag handling more lenient.

bcf_sr_sort.c
While non-symbolic variation is uniquely identified by POS,REF,ALT,
symbolic alleles starting at the same position were undistinguishable.
This prevented correct matching of records with the same positions
and variant type but different length (INFO/END)
A test case is added in bcftools in a separate commit
https://github.com/samtools/bcftools/commit/4578b76d91103dc8b6dd0091395c3c2bf70490ed
=> Pair lines with symbolic alleles by END tag

bgzf.c
Some implementations of bgzf do not include the proper EOF marker though are still readable.  This change softens the language of the warning.
This addresses samtools/samtools#1467.
=> Modified bgzf EOF warning to make it less alarming.

htslib/synced_bcf_reader.h, synced_bcf_reader.c
This is to address a long-standing design flaw in handling regions and targets,
as described in these BCFtools issues:
https://github.com/samtools/bcftools/issues/1420
https://github.com/samtools/bcftools/issues/1421
HTSlib (and BCFtools) recognize two sets of behaviors / options for resctricting VCF/BCF files by region, one
is for streaming (`-t/-T`) and one for index-gumping (`-r/-R`). They behave differently, the first includes
only records with POS coordinate within the regions, the other includes overlapping regions. This allows
to modify the default behavior and provides three options:
- Include only records with POS starting in the regions/targets
- Include VCF records that overlap regions/targets, even if POS itself is outside the regions
- Include only VCF records where the true …
=> Finer control of --regions vs --targets overlap

.cirrus.yml, Makefile, version.sh
This PR contains two commits.  The first fixes `version.sh` so that it works on `--depth=1` clones of the repository.  This both gets rid of the annoying "No names found, cannot describe anything." messages that were printed because `git describe` couldn't find a tag; and it also makes the `version.sh` report a correct-ish version string on such clones.
The second commit adds CI test support to catch any untracked files that make be present after build and test.  Finding such files usually means they need to be added to `.gitignore`.
=> Catch untracked files (and make version.sh work on shallow checkouts)

hfile_s3.c
Signature v4 requests were trying to create authorisation strings when no credentials were present.  This change adds the v2 lines that handle this. Fixes samtools/samtools#1491.
=> S3 V4 signature to handle no credentials.

bgzf.c, cram/cram_codecs.c, vcf.c
The new version of clang is better at finding unused variables.  This PR removes those variables.
=> Fix clang-13 unused variable messages.

bgzip.c
This is a small convenience feature that I've wished was present: Add a keep option to preserve input files to bgzip. Flag is -k or --keep, just like other compression tools. Default behavior is entirely unchanged.
I didn't see any tests for the bgzip tool, let me know if I missed them and I'll add tests for this.
=> [bgzip]: Add a keep option to not delete input files

cram/cram_io.c
This fixes #1329, which was discovered by code scanning and reported by Github @ryancaicse.
I do not believe it is likely to be triggered, but the value of this file can sometimes come from a CRAM file so it is possible malformed data could lead to a threading deadlock. (Untested)
=> Move the "start<1" error check in cram_get_ref to before thread locking.

sam.c
The offset to skip over the first name in the fastq header was being applied twice, potentially causing the search for the comment part to fall off the end of the allocated string.
Thanks to @jmarshall for reporting this.
=> Fix incorrect offset into fastq header in name2 mode

Makefile, cram/cram_io.c, hts.c, htslib/hts.h
There has been some recent discussion of using Zstandard compression (cf #530).
As a very small first step towards this, this adds `xz_compression` and `zstd_compression` to `enum htsCompression` and recognises their magic numbers, as we do for `bzip2_compression`. As htslib already uses liblzma, this also adds `decompress_peek_xz()` (if liblzma is configured in) to peek at the contents. Unlike libbz2's decompression routines, an `lzma_stream_decoder` can decompress a few hundred bytes of a stream without needing to read in an entire multi-hundred-KB block — hence is suitable for use with peeking.
There is also some talk of an intersection between D4 and htsget (though IMHO I'm not yet sure this intersection is non-empty), and of upcoming work in that area. So this also adds basic …
=> Add basic recognition for XZ- & Zstd-compressed data, and D4 format

sam.c
This was compared with string length 6 instead of 5, meaning it included the nul terminator byte.  This means "flag.read2" works at
the end of strings only.
Fixes samtools/samtools#1513
=> Fix a filter expression bug for flag.read2

cram/cram_encode.c
I'm sure no-one much cares about writing CRAM v1, but…
It seems like this branch of the `if`-`else` should also be filling in `cr->rg`. Noticed because with `brg` used only in the `assert()`, there is a “variable unused” warning when compiling with `-DNDEBUG`.
I suppose now that `brg` is used in the assignment, it could stay as an `assert()` and produce an assert failure (or a hard crash with `-DNDEBUG`) rather than `goto block_err` and returning an error code. Probably doesn't matter much either way — see paragraph 1 above!
=> Fill in cr->rg when writing CRAM v1 [minor]

hts.c, htsfile.c, htslib/hts.h
Fix the issue of some BED files being misrecognised as FASTA/Q indexes, by — as suggested in https://github.com/samtools/htslib/issues/1085#issuecomment-645360420 and https://github.com/samtools/htslib/issues/1085#issuecomment-645402870 — adding another API function that also considers the filename extension.
I have not implemented “`hts_detect_format()` should only recognise files as `fqi_format` or `fai_format` if they are uncompressed” — as suggested in https://github.com/samtools/htslib/issues/1347#issuecomment-952896121 — as it would mean that an affected BED file would be recognised as BED if compressed but as a FASTA/Q index if not compressed, and that seems like an unfortunate inconsistency. (The inconsistency of misrecognising an actual FASTA-IDX as BED when it's read from …
=> Consider filename extensions (where necessary) in format detection

vcfutils.c
=> Make bcf_remove_allele_set() set work on unpacked records

cram/cram_index.c
Fixes samtools/samtools#1541
The original report was for s3: URIs, but it turns out this is simply lacking in local files too.   It seems surprising we never implemented this, but even in 1.10 (where `##idx##` was first added) CRAM support was missing. 7e583ccea8e8a1a31c16bf5224d8f7785182dd82 stated "it works transparently for all file types and all programs".  I guess we never actually checked it.
=> Add pathA##idx##pathB support for CRAM indices.

htslib/sam.h
We have a GPU codebase that we use with htslib where we have to be very careful with `float`<->`double` conversions, for which we enable `-Wdouble-promotion`. Unfortunately, the publicly facing API has two lines that trigger this, mainly due to the fact that `printf` doesn't have float specifiers. This PR has two commits:
* The first one makes the public API `-Wdouble-promotion` clean by adding explicit casts.
* The second one fixes a simple `-Wdouble-promotion` issue. This one can be dropped, but it's not very invasive.
I tried fixing the whole codebase, but this required more casts. If desired, I can do those too.
=> `-Wdouble-promotion` clean API

synced_bcf_reader.c
Repeated seeks with implicitly created region list wouldn't initialize all internal structures to the original clean state, as demonstrated by the issue #1362, resolved by this commit
=> Make repeated seeks possible

cram/cram_decode.c
If using the required_fields option to select columns for decoding,
excluding CIGAR, then the sequence end position (cr->apos to cr->aend)
is not set correctly.
With CIGAR computed, ref_pos is increased by each CIGAR option.
Without it it'll end up being equivalent to cr->apos-1.  Now it is
always minimum cr->apos itself (ie covers apos to apos inclusive).
The impact of this is filtering for the entirety of a single
chromosome could leave a sequence as pos 1 with apos=1 aend=0, which
then rejected the sequence as aend < 1 (for region chr:1-LEN).
I think this also fixes samtools/samtools#1574, but cannot be sure without
confirmation.
=> Fix CRAM region queries when CIGAR isn't being decoded.

htslib/bgzf.h, htslib/hfile.h, htslib/hts_os.h, htslib/knetfile.h, htslib/kstring.h, htslib/sam.h
PR #1375 proposes unconditionally typedeffing `ssize_t` on MSVC in _htslib/hts_defs.h_, but as discussed in https://github.com/samtools/htslib/issues/1025#issuecomment-587032812 this is fragile if user code or other header files `#included` also include their own workarounds for this `ssize_t` issue. (It would be reminiscent of the olden days when every C library had its own bool type!)
A robust alternative is to `#define ssize_t` **within each affected HTSlib header only**, undoing it at the end of the header:
Define `ssize_t` within the public headers that use it, enabling them to be compiled with MSVC, which does not provide this type definition in its <sys/types.h> or any other headers.
Having `ssize_t` as a macro may confuse other headers, so be sure to do this only after all other …
=> Provide a definition of ssize_t when compiling with MSVC [more robust alternative to #1375]

hts_internal.h
sam_open_mode checks for ".fa" and ".fq" extension types, but these were never returned before as it had a hard rule of >= 3 characters.
=> Permit 2 letter extension in find_file_extension.

cram/cram_io.c
Previously for read names compression levels between 4 and 7 zlib
considerably beat libdeflate due to libdeflate's poor selection of
minimum match length. This was raised as issue ebiggers/libdeflate#85.
It's now been resolved in libdeflate 1.9 (along with some general
improvements elsewhere), and in all cases libdeflate is a better
choice.
Also fixed the mapping of levels 1..9 (standard zlib) to 1..12
(libdeflate).  The maths in the comment was incorrect as it's an
integer calculation not a floating point one.
Figures from converting 1 million NovaSeq records from BAM to CRAM 3.0:
```
Time       Size        RN
Libdeflate 1.9+PR-7  0m43.816s  204732408   48381374 (RN=libdeflate)
Libdeflate 1.8-7     0m45.379s  206626451   50580708 (RN=zlib)
Libdeflate 1.8-7     1m1.431s	210172035 …
```
=> Detect libdeflate >= 1.9 and adjust CRAM RN encoding.

cram/cram_decode.c, cram/cram_encode.c, cram/cram_encode.h, cram/cram_io.c
When writing, the specification states unmapped data must have alignment start and alignment span both zero.  Previously span was 1 (from end-start+1).
When reading, the code that filters data by the requested range now has an exception for ref_seq -1 (unmapped) so span is not checked.  This fixes the check for end-start-1 failing.  Note this previous triggered issues on files (correctly) output from htsjdk.
Fixes #1387
=> Improve handling of CRAM "alignment span" for unmapped data.

.appveyor.yml, INSTALL, Makefile
Specifically we create the extra files needed for MSVC linkage, and document the MSYS2/MINGW setup process.
Also added a win-dist target which attempts to produce a directory structure suitable for binary distribution.  This isn't executed by default, but is a good aide-memoire and to simplify testing compatibility with things like MSVC.
Ideally we'd have a similar mechanism for all platforms to permit easy creation of binary distributions (see #533).
=> Improve windows build.

hts.c, synced_bcf_reader.c
The function bcf_sr_regions_init() autodetects the format of input regions,
trying to decide between CHR,POS vs CHR,BEG,END formats. However, the function
hts_parse_decimal() was recognising standalone `G` as `0` which resulted in
`chr1 1234 G` being interpretted as `chr1 1234 0`.
This commit makes the digit parsing more strict, requiring at least one digit
to appear before the exponent or unit part.
See also samtools/bcftools#1598
=> Fix hts_parse_decimal and make synced BCF targets parsing more robust

hts.c, htslib/hts.h, test/sam.c
Motivated by #1395, this alters `hts_parse_decimal()` to validate that the number parsed is indeed a validly presented numeric value and to have a way of reporting failure. What we want to accept and the returned `strend` value are carefully considered, and test cases are added accordingly.
Follows `strtol()` et al's conventions, setting `strend` to the original `str` (or emitting a warning if `strend` is NULL) if the input string does not form a valid numeric constant. In particular, require it to have a non-zero number of digits.
Merges E and k/M/G handling, so that at most one can be used. In particular, "1e+3k" is non-standard and ambiguous, and should be rejected.
Adds documentation to _htslib/hts.h_ describing the numeric syntax parsed and the two modes of operation (as determined …
=> Check number syntax is valid in hts_parse_decimal()

INSTALL
Minimal updates for Windows builds.
- Warning about make check failing no longer appears to be true.  It works fine on current msys2/mingw-w64.
- Straight "make" fails and I've no intention of jumping through needless hoops, so document requirement for configure script.
=> Improve install notes for Windows.

hts.c
Refactor this code to avoid a `-Wformat-nonliteral` warning. Since PR #1406 was applied, this is the only instance of this warning produced by the HTSlib code base.
With this false positive corrected, it would be possible to turn `-Wformat=2 -Werror` on in a CI build.
(For GCC builds only; Clang's equivalent option has false positives as it does not suppress the warning for `va_list`-using functions.)
=> Use a constant printf format string in `hts_feature_string()` [minor]

htslib/sam.h
While compiling on Windows 10, we are getting multiple warnings from a single method.
This PR solves this issue by changing a data type for sub_type_size variable. It looks like the problem has something to do with a specific version of a compiler. We could not reproduce it on a Linux machine.
=> Changes a data type in sam.h to avoid compiler warnings

.cirrus.yml
Following a tidy up in 7981bc93 and 0d83a7b2, all format strings in HTSlib are now literals.  Prevent non-literal strings from coming back by using `-Wformat=2` in one of the CI tests, which enables `-Wformat-nonliteral`.  This has to be a gcc test as it excludes functions that take a va_list from the format-nonliteral warning while clang doesn't, and we need to be able to pass non-literal format strings to these functions.
While this might be slightly inconvenient for developers, any annoyances are far outweighed by being able to automatically detect a class of nasty and otherwise difficult to spot bugs.
=> Add stricter format string checking to a gcc CI build

hts.c, tabix.1, tbx.c
Double check the file coordinates are 1-based unless tabix -0 is
specified.  We treat a 0 coordinate as a warning now.  The
documentation is also more explicit that -0 also implied a half-open
coordinate system.
Also improve region parsing.  The code supports regions such as
"x"/"x:" (all of "x"), "x:10-20" "x:-20" (up to pos 20) and "x:20-"
(position 20 onwards).  However as genome coordinates are 1-based and
internally we have 0-based, we subtract one during parsing.  The
"x:-20" is done by negative value detection, but this was also
triggered with the illegal "x:0" region (treated as "up to 1").
Also, illegal regions such as "x:-10-20" were treated as "x:-20".
This is now a hard error.
Fixes #1409
=> Improve coordinate parsing, particularly with tabix.

vcf.c
Invalid definitions are fixed internally and warning such as
[W::bcf_hdr_register_hrec] The definition of Flag "INFO/SNP" is invalid, forcing Number=0
are printed so that downstream analyses can work (e.g. `bcftools merge`).
However, output VCF headers are not fixed.
This could go one step further and also modify the headers.
See also https://github.com/samtools/bcftools/issues/1685
=> Detect and fix invalid Type=Flag && Number!=0 header definitions.

test/test.pl
Prevent a very minor Perl warning that I noticed in passing:
```
…
cd test && REF_PATH=: ./test.pl ${TEST_OPTS:-}
"my" variable @p masks earlier declaration in same scope at ./test.pl line 617.
…
```
While checking differences between reruns I also noticed that the `test-bcf-sr` test cases select random numbers based partly on the current wall time (and without calling `srand()` first):
```perl
sub test_bcf_sr_sort
{
my ($opts, %args) = @_;
for (my $i=0; $i<10; $i++)
{
my $seed = int(rand(time));
my $test = 'test-bcf-sr';
my $cmd  = "$$opts{path}/test-bcf-sr.pl -t $$opts{tmp} -s $seed";
```
I didn't look at what that `-s` argument is used for, but this does theoretically mean that you could see a test failure and then be unable to reproduce it by rerunning the test suite.
=> Minor test/test.pl improvements

sam.c
This isn't permitted by the BAM specification, but was accepted by earlier htslib release.  62f9909 added code to check the maximum length.  This now has a warning at 2GB and the hard-failure at 4GB.
Fixes #1420.  Fixes samtools/samtools#1613
The problem still exists in CRAM, which also has signedness problems.  It's not as trivial there as simply removing the check.  (It will need CRAM v4.0 being adopted.)
=> Permit BAM headers between 2GB and 4GB in size once more.

NEWS
PR #1406 fixed which arguments were used as `printf()` format strings in `realn_check_tag()`, which is a subroutine of `sam_prob_realn()` (only). Correct the name of the function affected, and add a note of which HTSlib releases were affected: the problem was introduced in 5c401f2b9ab16ae71b45d3b5cb4717e3978e7fa0 and fixed in 7981bc9356899ea5dbf076d432e9645ee55df1d6 (on develop) / 328c3f5771695d32fcd7a9fc45899140879174d0 (on master & 1.15.1).
(FYI see also pysam-developers/pysam#1107 re effects of designating things “security fixes”. Sadly the second `hts_log()` instance fixed was indeed a potential issue.)
=> Fix NEWS entry for function affected by realn_check_tag() fix

hfile_internal.h, htslib/hfile.h, htslib/hts.h, htslib/hts_log.h, htslib/sam.h, htslib/tbx.h, htslib/vcf.h, textutils_internal.h
Under mingw clang requires dllexport to be applied to both function
declarations and function definitions.  (Gcc is happy for the
definition only to have the dllexport attribute.)
Note this exports several "internal" functions, including some
apparently unused anywhere (hts_json_*).   Perhaps they were once used
in htslib-plugins, but no more.
I haven't taken the decision to remove these though, but it's worth
considering for whenever we next do an ABI breaking change.  Either
that or stop pretending that their internal only when clearly they are
not, and move their API to the external htslib/*.h files instead.
These appear to be somewhat in Limbo right now.
Fixes #1433
=> Fix clang builds under mingw.

hfile_s3_write.c
`curl_easy_setopt(handle, CURLOPT_POSTFIELDSIZE, val)` takes a long, but was being passed a size_t.  This works on Linux where they're the same size for both 64 and 32-bit platforms, but not on 64-bit Windows which has 32-bit longs and 64-bit size_t.  We used to get away with it, but gcc 12.1 complains.
Casting the value to long should be fine.  The POST data is for the completion message which should not get that big due to the limit of 10000 parts when uploading data.
=> Fix curl type warning on Windows with gcc 12.1

faidx.c
This was probably a left-over from the transition to 64-bit positions in HTSlib.  Having the limit in fai_retrieve() caused
very long references to be truncated even though programs like `samtools faidx` should be able to support them (see issue samtools/samtools#1660 - samtools faidx fails to retrieve large scaffolds).
The limit is useful for legacy faidx interfaces that return the size in an `int *`, so tests for sizes over INT_MAX have been applied to them.
=> Remove limit on returned size from fai_retrieve()

cram/cram_external.c, htslib/cram.h
This is to enable samtools cram2ref PR.
Draft as although this works as-is, I'm thinking of adding io_lib's cram_size and cram_dump utilities too which will need further API additions.
If you wish each tool as its own PR to keep the size of this one day, then say so and I can take this out of draft, but if so then it needs merging promptly as I don't want to be making PR branches off another PR branch as that way lies merge hell.
=> Expose a bit more of the CRAM API.

hts.c, htslib/hts.h, test/sam.c
Something I noticed while writing a script to generate an enormous VCF record for #1447: the initial version of this generated a 2.5 GiB VCF record line, but `vcf_read()` failed to read it.
It turns out that `kgetline2()` (as used by `hts_getline()` for uncompressed input) reads such a line without trouble, but `hts_getline()` truncates the read string's length to `int` and returns negative — thus indicating error rather than a successfully read line.
This PR clamps the successful return value at `INT_MAX`. An alternative would be to change the return type to e.g. `ssize_t`, but this would have potential ABI implications perhaps…
In practice, no `hts_getline()` invocations in htslib, samtools, or bcftools use the length returned at all; they only use the return value to distinguish …
=> Cap hts_getline() return value at INT_MAX

htslib/ksort.h
The `register` storage class specifier was deprecated in C++11. and has been removed in C++17. The following C++ program:
```c++
#include "htslib/ksort.h"
KSORT_INIT_GENERIC(int)
```
produces numerous warnings with both GCC (by default) and Clang (with `-std=c++11`):
```
$ g++ -c use-ksort.cpp 
In file included from use-ksort.cpp:1:
use-ksort.cpp: In function 'int ks_ksmall_int(size_t, int*, size_t)':
htslib/ksort.h:91:52: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
91 | #define KSORT_SWAP(type_t, a, b) { register type_t t=(a); (a)=(b); (b)=t; }
|                                                    ^
htslib/ksort.h:263:61: note: in expansion of macro 'KSORT_SWAP'
263 |                                 if (__sort_lt(*high, *low)) KSORT_SWAP(type_t, *low, …
```
=> Don't use `register` in public header file [trivial]

tabix.1
This can help if there are spaces in the GFF3 file e.g. in column 2 or 3. Was found in the wild by my co-worker on a gff file here https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/285/GCF_000002285.3_CanFam3.1/GCF_000002285.3_CanFam3.1_genomic.gff.gz
Another alternative but similar command is
```
awk '$1 ~ /^#/ {print $0;next} {print $0 | "sort -t\"\t\" -k1,1 -k4,4n"}' file.gff > file.sorted.gff
```
But, the PR here keeps it as is
=> Set tab delimiter in manpage for tabix GFF3 sort

hts.c
If errno is non-zero we now use strerror to report the system error message when reporting on failure to load an index.
See samtools/samtools#1637 for an example where we believe this would aid the user to diagnose the problem.
=> Improve error message when failing to load an index.

.gitignore, Makefile, hfile_s3.c, hts_time_funcs.h, htslib-s3-plugin.7, test/test_time_funcs.c
This is to make HTSlib work better with AWS IAM credentials, which have a limited lifespan, and so may need to be refreshed. To allow this, hfile_s3 is made to look for an unofficial `expiry_time` entry in the `AWS_SHARED_CREDENTIALS_FILE`.  If present, the file will be re-read if the current time is within one minute of the given expiry (new credentails are available five minutes before expiry, according to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html, and in practice much earlier).
Currently no effort is made to understand the JSON format emitted by the AWS security-credentials endpoint - mainly because there are several ways to get credentials, which all have subtle differences.  Rather than try to support them all, it's left up to the end user to …
=> Make hfile_s3 refresh AWS credentials on expiry

sam.c
If we have an MM tag with base-type specific coordinates beyond the end of the sequence as there are too few bases of that type, then we now detect this within bam_parse_basemod.
This was already checked within bam_next_basemod for forward reads, but not spotted in reverse complemented ones.
Fixes #1466
Note this checks in a different place, as for reverse complemented reads we've already computed the total frequency as we're counting backwards, so spotting overflow can be done at the parse stage while setting up the "initial" (ie last) mod.  For forward reads our initial one is also the first, so a check isn't so useful here.
=> Further improve MM tag consistency checking.

.cirrus.yml
Change rockylinux docker image to rockylinux:9 following deprecation of rockylinux:latest.
Adds perl-FindBin to installation list, as it's now in its own package.
=> Switch to rockylinux:9

vcf.c
The 0 coordinate is valid in VCF specification, but the round-trip
VCF -> BCF -> VCF turns MT:0 into MT:4294967296. Add a check to
detect this overflow.
See https://github.com/samtools/htslib/issues/1475 and https://github.com/samtools/bcftools/issues/1753
=> Support 0 coordinate in BCF

Makefile
Extend the `print-config` target added in 155e1aacac741febd6fd722cf7e3660da38d6a9b. This target-specific compiler flag information (probed for by _configure_) may also be of use to third parties.
In particular, pysam's current build infrastructure will need this information — cf pysam-developers/pysam#1112.
Pysam might in future switch to using HTSlib's build infrastructure to build _libhts.a_ (rather than using Python setuptools machinery to build the object files listed in `LIBHTS_OBJS` as reported by `print-config`), but this would still be of use to other third parties.
=> Report HTS_CFLAGS_AVX2 et al in `make print-config`

bgzf.c
Libdeflate goes up to compression level 12, with the last 3 levels
using a much slower optimal parsing technique.  We reserve bgzip
levels 8 and 9 for two of these slow modes, and spread the remainder
out across levels libdeflate 1-9.
We map 1-9 to 1,2,3, 5,6,7,8, 10,12.
This was designed so that the files are generally smaller than their
zlib counterparts while still being faster (except for zlib levels 8
and 9 as noted above).
This is based on benchmarks (see below) for various data sets.
Hence users will find bgzf -l8 and -l9 considerably slower than
before.  Ideally we'd support bgzip -l10 to -l12, but this complicates
several tools and the htslib format string which assumes it's
level+'0' in various places (not just the library, but also the
command line tools).  This was the simpler …
=> Add a mapping of Zlib to Libdeflate compression levels for BGZF.

vcf.c
Adds a check for INFO/FORMAT values with type 0 (["A MISSING value without an explicit type provided"](https://samtools.github.io/hts-specs/VCFv4.3.pdf#subsubsection.6.3.3)) and number of elements > 0.
Normally type = 0 and number = 0 is used for a completely missing INFO/FORMAT value.  In theory you could use number > 0 to make an array of missing values (at least the specification doesn't explicitly disallow it), however trying to do so results in bcf_fmt_array() reporting "Unexpected type 0" and calling exit(1).  HTSJDK also appears to reject this encoding, and nothing appears to write it, so it seems reasonable to say that it's not valid.
The check for this encoding is added to bcf_record_check() so it's caught well before the data gets near bcf_fmt_array().
It also avoids problems …
=> Catch arrays of BCF_BT_NULL in bcf_record_check()

hts_expr.c, htslib/hts_expr.h, test/test_expr.c
This tries to follow the principles of 3-state logic used in other systems, such as SQL.  See https://en.wikipedia.org/wiki/Null_(SQL)#Comparisons_with_NULL_and_the_three-valued_logic_(3VL)
There is some controversy there and a suggestion that 4-state logic is better, which we sort of already have with the "null-but-true" concept, which may impact below.
The primary changes here are:
- New `hts_expr_val_exists` and `hts_expr_val_undef` inline functions to check if a value exists and to clear it.  These simply logic elsewhere.  This fixes SAM filter expressions like `[AB] / [BC] > 1` where tags AB or BC don't exist.  Similar updates have been applied to many logic and mathematical operators.  To avoid spammage these are silent, failing the expression without complaint due to undefined …
=> Improve filter expression language consistency

sam.c
Detected by giving a SAM file to `samtools import`.
=> Fix SEGV when handling errors from sam_read1_sam without headers

Makefile
If we haven't previously done a "make" or "make all", the .dll file
won't have been created.  The test/with-shlib.sh script will then fail
as the "cp -p ../../hts-*.dll ." command fails.  We no longer even
attempt to execute this test when plugins don't exist (which they
won't on Windows unless we've installed the dlfcn package).
Note the analogous non-mingw commands are "ln -s ../../libhts.so.* ."
and similar, which don't fail in the $? sense, but do fail with
regards to produced a bogus target containing a wild-card pattern.
This implies the error checking in this script is broken for all
platforms bar MinGW, but given the very limited use for this one test
case it's an irrelevance.
(See also the abandoned https://github.com/jkbonfield/htslib/tree/mingw_make_check which adds code so …
=> Fix "make check" on MinGW.

configure.ac, hts.c, hts_probe_cc.sh, m4/ax_check_compile_flag.m4, test/test_time_funcs.c
* Improve SIMD detection.
`_mm256_extract_epi64()`, used by the AVX2 rANS codec, is only available on X86_64.  Adding it to the configure tests prevents it from being used on i686.  Also change the `ax_check_compile_flag` test so it runs the linker, which catches missing symbols better than just running the compiler.
* Fix some overflow warnings in the test_time_funcs program, when `time_t` is only four bytes long.
* Silence an annoying gcc-10 format-truncation warning.
=> Fix problems found attempting to build on i686

tbx.c
Found via a git clone of clang (claiming 16.0, but pre-release so 15++)
=> Fix newer clang warning of unused variable.

vcf.c
This could be triggered by a #CHROM line ending in something like:
```
#CHROM\t...\tINFO\t\t\t\t\t\t ... many tabs ... \t\t\tfoo\n
```
Between each pair of tabs, `bcf_hdr_add_sample_len()` was called with `len = 0`, as if from `bcf_hdr_add_sample()`.  This made it use `strlen(s)` instead of 0 as the sample name length, resulting in the addition of a bogus sample name with lots of leading tabs.  The sample line parser then moved on to the next tab, and did the same thing again with one fewer leading tab.
Fix by making `bcf_hdr_add_sample_len()` always use the passed-in length, even if 0, allowing the empty sample name trap to do its work.  `bcf_hdr_add_sample()` is updated to call `strlen()` itself, and to also deal with the backwards-compatibility check where it was permissible to call it …
=> Fix n-squared complexity in sample line with many adjacent tabs

htslib/sam.h, sam.c, test/sam.c
As suggested in #1319, this adds new API functions for iterating through a BAM record's aux fields, inline accessor methods for field tag and type (or code can continue to use `s-2` and `*s`), and a  variant of `bam_aux_del()` that returns the (updated) iterator to the following field (for use in iterator-based loops that delete fields). IMHO there's no need for an additional `bam_tag_iter_t` type, as the `uint8_t*` pointer to aux fields is already all over this part of the API and there's no need for more iterator state anyway.
This draft rewrites `bam_aux_get()` in terms of the new iterator functions. It's slightly debatable whether to do that (and remove the old version) or to leave it alone.
Tossing up between using the C++-style `bam_aux_erase()` nomenclature or calling the new …
=> Proposal for an aux tagged field iterator API

Makefile, bgzip.1, bgzip.c, test/test.pl
An alternative to @mlin's #1369 for consideration.
The two implementations differ by:
- Using kstring's kgetline3 (a new variant of kgetline2), vs manual newline scanning.
- Efficiency (my version has considerably less overhead)
- Code complexity (my version adds around twice as many new lines of code)
- Text mode explicit (Mike's) vs text mode implicit (--binary to disable).
- IO block sizes are freer (Mike's) vs required to exactly match the BGZF block size (mine).
At bgzf -l1 Mike's text mode added 6.2% CPU cycles, vs +0.4% for mine.  However at level 6 these are considerably reduced as the Deflate overhead starts to dominate and these drop to 2.7% vs 0.0%.  So maybe this isn't such an issue anyway.  The main difference in CPU comes from searching backwards for the first newline vs …
=> Bgzip text mode (try 2)

synced_bcf_reader.c
Without this, bcftools returns error code 0 even when interrupted by these errors visible in stderr:
- [E::hts_itr_next] Failed to seek to offset 70116896333: Illegal seek
- [E::bgzf_read_block] Failed to read BGZF block data at offset 29255442 expected 12238 bytes; hread returned -1
This code change is in line with what is written in the next `else` block
=> Fix error code 0 returned by bcftools after error

hts.c, tabix.1, tbx.c
This already worked for SAM and VCF where the SQ and Contig lines indicate the maximum length of a reference sequence.  However for BED files this was left as zero, which had the effect of fighting against the user by decreasing n_lvls as we increase min_shift.
When unknown, max_ref_len is now an arbitrary large size (100G), but this may produce more levels than are strictly necessary, although this doesn't appear to have negative consequences.  For completeness however, the tabix command line now also permits this to be specified explicitly with --max-ref-len.
Also fixed the misleading error message about CSI being unable to index data.  This was perhaps intended to be for mis-specified VCF data where a contig was listed as small but the records were at larger offsets, however it simply …
=> Make tabix support CSI indices with large positions.

sam.c
Eg the minimal file of:
>foo
Fixes oss-fuzz 51378
=> Prevent crash when only FASTA entry has no sequence.

test/sam_filter/filter.tst
* GNU grep 3.8 considers `egrep` and `fgrep` obsolescent and throws warnings: https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html
=> Use POSIX `grep`

.cirrus.yml
Following removal of the Makefile in libdeflate commit [03fba38bd](https://github.com/ebiggers/libdeflate/commit/03fba38bd19af78e8484cbfb3b050701bfedb377).
=> Switch to building libdeflate with cmake

htslib/sam.h
Hi!
I am in working on htslib bindings for the [Ruby](https://github.com/kojix2/ruby-htslib) and [Crystal](https://github.com/bio-cr/hts.cr) languages. This is just a small typo that no one notices, but I am very happy to send a pull request to htslib for the first time.
Best regards and thank You.
=> Fix a typo in sam.h documentation

faidx.c, htslib/faidx.h
This exposes the input datas line wrap length (minus white-space / newlines).
Also fixed a SEGV in fai_retrieve given incorrect or malicious .fai files with a zero length "blen" figure.
=> Add an fai_line_length function.

sam.c
I don't know how best to deal with such situations, so rather than a hard error we treat the barcode component the same as if no BC tag was stored - with "0".  It also whinges, and you'll probably get this message many times, but take that as "encouragement" to fix the input data!
Also fixed the barcode to be uppercase, incase of e.g. "ac+gt".  I'm not sure if it's required, but we may as well.
Fixes samtools/samtools#1728
Note it's still clear as mud as to what this field really should contain.  The Illumina documentation is pretty atrocious here.
The old (deprecated) bcl2fastq had the most information: https://emea.support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v2-20-software-guide-15051736-03.pdf but it says "index …
=> Check for invalid BC tags in fastq output.

sam.c
We already validate CIGAR length vs sequence, but if we have SEQ '*' then it passes those checks.  Unfortunately this means we read beyond the end of sequence later on.
=> Fix buffer read-overrun in bam_plp_insertion_mod.

cram/cram_io.c
We have too many similarly sounding reference filenames. While the previous fixed worked when MMAP was in use, when it's not we end up setting fd->refs->fn in cram_populate_ref, which causes samtools test failures on Windows.
With hindsight, the fix was wrong as fd->ref_fn is the actual filename we specified with view -T, while fd->refs->fn is the current filename loaded (which is the same thing *unless* we're using a local cache and no mmap in which case it's also updated to point to the filename associated with the open file descriptor).
Definitely an "I wouldn't start from here" problem. (Sorry!)
=> Fix ref fix from c91804c

.cirrus.yml, vcf.c
Default on gcc 4.6 was 'gnu90', which allows some c99 features but not `for (int n = 0, ...)`
Adds a `-std=gnu90` build to the tests so we don't get caught by this again.
Fixes #1523
=> Fix build on ancient versions of gcc

Makefile
This is more tricky than it first appears as the strings in question have to make it through make expansion, shell string expansion, interpretation by the command writing the file, and end up making sense to the C compiler.
The values are escaped by converting `\` to `\\`, `"` to `\"` and `'` to `\x27` (as it's impossible to quote a `'` in a single-quoted string).  Writing the file is now done by `printf`, which won't try to interpret any of the strings being printed as an option.  Its arguments are all single-quoted to prevent the shell from trying to expand them in an unwanted manner.
Fixes #1527
=> Ensure strings in config_vars.h are escaped correctly

test/test.pl
Fixes a small testing inefficiency I noticed.
The test only runs on the ce#1000.sam file, so it shouldn't be inside the loop that runs on all sam files in the test directory.
=> Cut down the number of embed_ref=2 tests that get run

htslib/vcf.h
Do not rely on int_id being return value of bcf_hdr_id2int()
Resolves #1538
=> Make bcf_hdr_idinfo_exists() more robust

cram/cram_encode.c, cram/cram_io.c, cram/cram_structs.h
See https://github.com/samtools/samtools/issues/1748 for background, although this isn't fixing that issue and I'm not yet sure what that problem is.
I'm unsure on whether this is a desireable solution.  See the benchmarks below; the "fix" isn't free.
<hr/>
Given the possibility of creating a CRAM which cannot be decoded again due to specifying a fasta file that differs to the M5 tags specified in the header, we're now more militant in enforcing these match.
This does however add a performance hit when processing the header, which can unfairly penalise small files or creation of CRAMs for a small portion of the genome.
$ time samtools view -T $HREF -O cram,ignore_md5 -o /tmp/_.cram ~/scratch/data/9827_2#49.bam 10:10000000-11000000
real    0m0.807s
user    0m0.702s
sys     0m0.101s
$ time …
=> Add CRAM SQ/M5 header checking when specifying a fasta file.

bgzf.c, htslib/bgzf.h, tbx.c, vcf.c
Some changes to make reading and writing very long lines work better.  It is a partial fix for #1539 - the overflow mentioned in dealt with, but more work will be needed to make the very long VCF records readable.
* Cap the return value of `bgzf_getline()` to avoid integer overflow.
* Change data types in `tbx_parse1()` and `vcf_write()` so they can handle long lines (albeit only on 64-bit platforms).
* Put an extra loop around `read()` and `write()` in `fd_read()`, `fd_write()` to ensure they really have processed the expected amount of data.  This is especially important on Linux, which has a [limit on the amount of data that will be read or written](https://man7.org/linux/man-pages/man2/read.2.html#NOTES) in a single call.
This is mostly useful for `tabix`, which doesn't do much …
=> Improve support for very long input lines (> 2Gbyte)

cram/cram_codecs.c, cram/cram_codecs.h, cram/cram_external.c, htslib/cram.h
- cram_block_get_content_id is updated to return -1 for CORE block, removing the need to add a content_type API and share that enum.
- New cram_block_get_method method
- New cram_codec_get_content_ids, which externalises the existing cram_codec_to_id (with a hopefully better API and name).
- Make cram_decode_compression_header and cram_free_compression_header external.  The struct itself is opaque.
- Added cram_update_cid2ds_map, cram_cid2ds_query and cram_cid2ds_free to produce, query and free a block Content-ID to Data-Series mapping from the meta-data held within a CRAM Compression Header.
- Added a new cram_codec iterator to sequentially step through all cram_codec structures produced by decoding a compression header. This new code is entirely internal to htslib and is solely used by …
=> Expand CRAM API a bit to cope with new samtools cram_size command.

sam.c
This means `4M1D1D1D3M` is reported as `4M3D3M` instead as far as mpileup is concerned (although samtools view will report as-is) and importantly `p->indel=-3` for the first `1D` and the 2nd `1D` has `p->indel=0` (with `p->is_del=1`, the same as it would for the 2nd base in a `3D` cigar op).
Previously samtools mpileup would produce incorrect looking output for the `1D1D` scenario.  Fixing this in sam.c means not only is samtools mpileup now looking better, but any tool using the mpileup API will be getting consistent results.
Note that samtools mpileup already resolved the ...`1I1I1I`... case, but it did this within the samools bam_plcmd.c code itself.  Hence while the pileup API works, it left `p->indel=1` instead of `p->indel=3` for this situation.  So we also resolve that in a similar …
=> Merges neighbouring I and D ops into one op within pileup.

htslib/bgzf.h
Note that this now works on reading as well as writing.
Removed the comment about only when compiled with `-DBGZF_MT` as this was misleading implying the user has to adjust CFLAGS.  It's on by default and there's nothing the user can do to turn it off without manually editing bgzf.c, in which case they're on their own.
Also document that n_sub_blks now does nothing.
Fixes #1553
=> Improve API docs for bgzf_mt

hts.c
Fixes a couple of places where file read errors could be silently ignored.
=> Catch errors from bgzf_getline() in hts_readlist, hts_readlines

cram/cram_io.c
The name tokeniser has a rANS vs Arithmetic coder choice as a parameter (in the "strat" variable).  We lacked this distinction when learning which method works best, so in the choice of toka (tok3+arith) vs bzip2 vs gzip etc we selected tok3 and switched back to strat 0, disabling the arithmetic coder.
This only affects archive mode, or where a user explicitly used eg "samtools view -O cram,version=3.1,use_arith".
=> FIx a bug in the codec learning algorithm for TOKA

cram/README, cram/cram_decode.c, cram/cram_encode.c, cram/cram_io.c, cram/cram_structs.h
- Fix crash when `cram_encode_container` during multi-threaded CRAM encoding.
- Prevent embed_ref=2 on name sorted data from being a hard failure for cram encoding.  It now switches to non-ref mode instead, so we always encode something, even if it's suboptimal.
=> Embed ref2 unsorted

NEWS
Putting up the first draft now.  Will put the final one in just before the release.
=> January 2023 NEWS Update.

test/test_bgzf.c
The test script is expected to fail as it's testing both working and failing conditions, but the test harness prints up strerror(errno), which is usually some unrelated event and the text also differs per platform.
=> Prevent spurious and random system errors from test_bgzf.c

hfile_libcurl.c
The older CURLINFO_CONTENT_LENGTH_DOWNLOAD has been deprecated, and is now causing warnings to be printed on distributions that have moved on to the latest libcurl versions.  CURLINFO_CONTENT_LENGTH_DOWNLOAD_T was [officially added in curl 7.55.0](https://curl.se/libcurl/c/CURLINFO_CONTENT_LENGTH_DOWNLOAD_T.html).
=> Switch to CURLINFO_CONTENT_LENGTH_DOWNLOAD_T for newer libcurl

cram/cram_index.c, cram/cram_structs.h, hts.c
The cram_index_query_last used by sam_itr_regarray had problems when dealing with slices whose region is contained within another region.
Fundamentally this is due to the cram_index arrays being contiguous in memory until a containment is found, at which point the pointers will be to an entirely different array.  This breaks naive pointer comparisons.
The cram_index struct already had a "next" field holding the file offset of the next container.  This has been replaced by e_next pointing to the next cram_entry struct in file ordering, and e_next->offset is equivalent to the old "next".  This allows consumption of the index either as the original nested containment list or as a traditional linked list.
Also fixed cram_index_query with from != NULL, which similarly was incorrect before.  We …
=> Fix cram_index_query_last function

hts.c
hopen() uses a ':' in `mode` to indicate that there are extra parameters.  hts_crypt4gh_redirect() needs to add this so that the "parent" parameter is picked up by the crypt4gh plug-in.
Failing to do this caused it to re-open the file instead of reusing the existing file handle - which worked for regular files but not for things like pipes or htsget.
Problem noticed when trying to reproduce some crypt4gh-over-htsget work.
=> Fix crypt4gh redirection

sam.c
This is rather questionable, but htslib can read in empty fastq records and generates "*" for SEQ and QUAL.  The same is true vice versa now.  Eg:
name	4	*	0	0	*	*	0	0	*	*
becomes
@name
+
Bwa mem and minimap2 can both read these fastq entries too, although the SAM output is bugged as it outputs an empty field instead of "*" for SEQ.  (Note this is still readable by htslib and interpreted the same).
Potential reasons for accepting this:
- When dealing with paired data, we don't want to output a differing number of records from samtools fastq if read1 has seq and read2 has "*".
Note as this filtered at the htslib layer, it's not considered as a singleton so fastq -s won't rescue this.
- At least some aligners apparently support this format.  Although inevitably they just produce unmapped …
=> Permit fastq output to create empty FASTQ records for seq "*".

sam.c, vcf.c
1. sam_idx_save wasn't validating the file is BGZF.  It's invalid usage to try calling this function on uncompressed data, but we should double check.
Note this is triggered by a bcftools bug where -o foo.vcf.gz##idx##foo.vcf.gz.csi writes VCF rather than VCF.gz as the "filename" doesn't end in .gz.
2. Add the hts_idx_amend_last calls to vcf_write as we did previously for SAM/BAM.
This isn't technically a requirement, as all it's doing is changing virtual offsets to an alternate form that gives the same file offset (see comments above hts_idx_amend_last), but doing so means the auto-build indices match those produced by a standalone index command.
This fix isn't complete as it hasn't been worked on for BCF yet. However it comes under the "nicety" category and isn't really fixing a bug so …
=> Fix a couple small VCF auto-indexing bugs.

cram/cram_decode.c, cram/cram_io.h, sam.c
None of this is huge, but it all adds up.
- bam_set1 has been refactored so -O3 is more likely to do unrolling and vectorisation.
```
// Old          time   inst        cyc
// gcc -O2      12.36  78936832183 36853852204
// gcc -O3      12.37  78713347525 36867027825
// clang13 -O2  12.43  77451926728 37012866717
// clang13 -O3  12.32  77627221907 36691623424
// gcc12 -O2    12.43  78895089091 37081260172
// gcc12 -O3    12.36  78505904437 36829216967
// New
// gcc -O2      12.47  78832021505 37200597109 +
// gcc -O3      12.14  76499369401 36390334338 --
// clang13 -O2  12.38  76678460761 36920111561 ~
// clang13 -O3  12.26  76678023071 36548488492 ~
// gcc12 -O2    12.38  78581694397 36880034181 -
// gcc12 -O3    12.15  76356625541 36293921439 --
```
- Improve the MD/NM generation in …
=> Slightly speed up various cram decoding functions

cram/cram_io.c
The code would now trigger on 3.2 as well as 4.x, although 3.2 doesn't exist.  It's easier to check this way though as a future-proof.
=> Remove CRAM 3.1 warning.

cram/cram_index.c, cram/cram_io.c, cram/open_trace_file.c, hfile_s3.c, kstring.c, plugin.c, sam.c, test/hfile.c, test/sam.c, test/test-regidx.c, test/test_mod.c, test/test_view.c, textutils.c
None of these instances were really a problem, but using it upsets some downstream packagers (notably R).  The easiest way to keep them happy is to stop using it and (mostly) switch to snprintf() instead.
Fixes #1586
=> Remove use of sprintf() from HTSlib source

hts.c
When searching for `max_off`, `hts_itr_query()` and `hts_itr_multi_bam()` look for a bin to the right of the end of the region.  For whole chromosomes, this would be HTS_POS_MAX, which is far beyond the maximum bin position supported.  The `bin` calculation overflowed leading to either a negative bin number or an incorrect positive one, depending on the number of levels in the index.  Negative bin numbers simply caused time to be wasted as the search loop eventually counted up to zero, but incorrect positive ones could cause the iterator to finish too early.
Fix by catching the out-of-bounds case and setting max_off to UINT64_MAX, which should be used for bins beyond the end of the indexable range.
Luckily in practice this didn't cause too much harm, at least for the default `min_shift` …
=> Fix bug where bin number could overflow when looking for max_off

hts.c
It's faster to iterate through the index hash table when requesting whole chromosomes, compared to the old behaviour of iterating through all the bins that could exist and looking them up in the hash table to see if they're present.  The latter method works better for narrow ranges though, so we choose which to use based on the number of bins covering the range compared to the number in the index.
The speed-up is most notable on CSI-indexed BED files, which since #1506 have used eight-level indexes.  Iterating through all the unused bins took around 0.2s in my testing.  With this fix applied, the same query can be done in a few milliseconds.
=> Make reg2bins, reg2intervals faster on whole-chromosome queries

htslib/khash.h
This was fixed upstream in attractivechaos/klib@384277a
Fixes #1598
=> Fix typo in kh_int_hash_func2 macro.

INSTALL
Document static linking options needed with current plugin mechanism. Addresses #1600.
There may be platforms where the option is called something other than `-rdynamic`, and the underlying `ld` option is called something else. This could mention what CMake calls it, but they'll only change the name of the property again next week… :smile:
=> Mention in INSTALL that using plugins may need -rdynamic

htslib/sam.h
Hi!
I am glad to have the opportunity to send you another pull request.
In the example in the `sam_hdr_add_line` documentation, I propose changing "ID" to "SN."
```
[E::sam_hrecs_update_hashes] Header includes @SQ line with no SN: tag
```
https://github.com/samtools/htslib/blob/279cc9ec8d3fd5ad94aa0df730dac6e9ec0ead8f/htslib/sam.h#L471
Best regards.
=> Fix example in docs for sam_hdr_add_line

cram/cram_decode.c, cram/cram_encode.c, cram/cram_structs.h
CRAM encoding can overflow the concatenated block of BAM aux tags used in the decoder when the size of the aux tags becomes excessive.
This can happen in real world data in some bizarre circumstances.  For example very long ONT records with per-base aux tags left intact, passed through an aligner that records secondary alignments as SEQ "*" but leaves the aux tags in place.  This means the limit of the number of bases per container is not triggered, giving rise to excessively large containers, and specifically aux tags that combine to >2GB.
We fix it in two ways.
1) Protect against existing files with this problem by detecting the overflow may happen and simply bailing out.  This is perhaps overly harsh, but previously this would simply have core dumped and to date we've only ever had one …
=> Protection against over sized aux tags in CRAM

Makefile, configure.ac, test/compare_sam.pl, test/maintainer/check_copyright.pl, test/maintainer/check_spaces.pl
Pulls in the latest version of htscodecs, including a change to add `#include "config.h"` to the htscodecs test sources, allowing a hack (which didn't work on FreeBSD) that set `_POSIX_C_SOURCE` when building them to be removed.  `configure` is also changed so that it adds `#define _XOPEN_SOURCE 600` by default to `config.h` instead of relying on the `PTHREAD_MUTEX_RECURSIVE` test to do it, which allows that test and various other places that set `_XOPEN_SOURCE` to be removed.  I've set the author of the commit that does this to @jmarshall as it's mostly his work - hopefully that's OK.
The other commits fix some minor annoyances when running `make maintainer-check` on a repository where `configure` has been run; and makes all the perl scripts use `#!/usr/bin/env perl` (some already did) …
=> Pull in latest htscodecs and improve portability

tbx.c
If the end column appeared before the begin column then the end value was being overwritten in the begin value initialisation.
Fixes #1622.
=> Stop the overwriting of the end value.

htslib/sam.h, sam.c
update to ensure NUL termination of Z/H type aux data on sam_format_aux1.
update to avoid failure on next base modification check - on alignments without MM tag which has a lower length than previously processed alignment.
comment updates.
=> fixes and comment update

hts.c
Fix for #1617
when bam write is attempted with 'u', the bgzf compression/decompression buffers are not allocated as it denotes uncompressed output. bgzf_flush, called at end, accesses the compression buffers and causes segfault in such case.
Binary data files are implicitly expected to be bgzf compressed and this 'u' flag is not valid / supported.
The fix made is to remove the 'u' flag on write of bam/bcf that the output is written as bgzf compressed with default compression level.
=> changes to avoid segfault with uncompressed bam

htslib-s3-plugin.7
When preparing the htslib 1.17 upload in Debian, lintian caught a bad-whatis-entry issue.  Looking closer, whatis(1) and apropos(1) commands fail to locate htslib-s3-plugin(7) manual and the parsing of the page fails with:
$ lexgrog htslib-s3-plugin.7
htslib-s3-plugin.7: parse failed
It seems to stem from the two words "s3 plugin" in the name of the manual, instead of having a single word as needed.  This change names the manual page "htslib-s3-plugin" instead, making the mandb, the lexgrog parser, and lintian happy:
$ lexgrog htslib-s3-plugin.7
htslib-s3-plugin.7: "htslib-s3-plugin - htslib AWS S3 plugin"
The name could also simply be "s3-plugin", but having htslib in the name felt more apropos.  :)
=> htslib-s3-plugin.7: fix whatis entry

htslib/synced_bcf_reader.h, synced_bcf_reader.c
and make repeated bcf_sr_seek()+next_line() calls consistent.
Resolves #1623 and https://github.com/samtools/bcftools/issues/1918
=> Allow repeated calls of bcf_sr_set_regions

htslib/synced_bcf_reader.h, synced_bcf_reader.c, test/bcf-sr/weird-chr-names.1.out, test/bcf-sr/weird-chr-names.2.out, test/bcf-sr/weird-chr-names.3.out, test/bcf-sr/weird-chr-names.4.out, test/bcf-sr/weird-chr-names.5.out, test/bcf-sr/weird-chr-names.6.out, test/bcf-sr/weird-chr-names.vcf, test/test-bcf-sr.c, test/test-bcf-sr.pl, test/test.pl
Note hts_parse_region() cannot be used because it requires the header and without the header the caller does not learn the contig name.
Resolves #1620
=> Add support for non-standard chromosome names containing [:-] characters

hts.c
Demonstration:
```
$ echo -e "@seq\nAAAAA\n+\nABCDE" | gzip > _normal.gz                           
$ (gzip < /dev/null;cat _normal.gz) > _empty.gz                                 
$ ./htsfile _normal.gz                                                          
_normal.gz:     FASTQ gzip-compressed sequence data                             
$ ./htsfile _empty.gz                                                           
_empty.gz:      empty gzip-compressed data                                      
$ ./test/test_view _empty.gz                                                    
Unsupported or unknown category of data in input file                           
```
Zlib's `inflate` ends with `Z_STREAM_END` and then repeated calls to get more won't give any difference, so we need the explicit …
=> Fix decompress_peek_gz to cope with files starting on empty gzip blocks.

hts.c
The "zs.total_out < destsize" should have been "zs.avail_out" to be more robust to total_out being reset by inflateReset.  However looking again neither the avail_in or avail_out checks are necessary, as once we hit the end of either input or output buffer the next cycle triggers ret == Z_BUF_ERROR and we drop out as normal.
Thanks to John Marshall for the spot.
See #1643
=> Fix to 2e672f33 decompress_peek_gz change.

Makefile, hts.c
* A few missed _Makefile_ changes from recent PRs.
* Add `const` to avoid a warning when zlib is configured (via `-DZLIB_CONST`) to be more const-correct than is the default:
```
hts.c:335:25: warning: assigning to 'unsigned char *' from 'const Bytef *' (aka 'const unsigned char *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
last_in = zs.next_in;
```
=> Add missing Makefile dependencies and other minor fixes

faidx.c, htslib/bgzf.h, htslib/faidx.h
This is a simple skim around bgzf_thread_pool.
Also added a missing `@param qsize` to the bgzf_thread_pool documentation.
Fixes #1638
=> Add fai_thread_pool interface.

htslib/sam.h, sam.c
It makes little sense for this to exist as a public API when it's only capable of handling the internal during-SAM-parse situation, and the changes are relatively minor.
Also removes an undocumented assumption that end == &in, and fixes cut and paste errors in bam_aux2f API docs.
Fixes #1650
=> Make bam_parse_cigar able to modify existing BAM records rather than partially parsed ones.

hts.c
In samtools/samtools#1884 we saw a BAM file downloaded via a web browser and ungzipped. `htsfile` reported this file as follows:
```
$ htsfile wgEncode-browser.bam
wgEncode-browser.bam:	BAM version 1 sequence data
```
In isolation it's not obvious that this is reporting that the BAM file is **not** BGZF-compressed as normal. (For usual BAM files, `htsfile` reports `BAM version 1 compressed sequence data`, but if you don't have one handy to compare…)
This PR adds “uncompressed” for uncompressed files in formats, like BAM and BCF, that are normally compressed, to make this clear. Thus:
```
$ htsfile wg*.bam
wgEncode-browser.bam:	BAM version 1 uncompressed sequence data
wgEncode-curl.bam:	BAM version 1 compressed sequence data
```
=> Add "uncompressed" in hts_format_description() where appropriate

bgzf.c, htslib/vcf.h, kstring.c, vcf.c
This is an amalgamation of many small optimisations which jointly can have a significant effect.
I've benchmarked it on data that is very heavy on INFO fields, very heavy on FORMAT fields (many samples), and more "normal" single sample data.  Also tested it with the system gcc (7), gcc 13, and clang 13.  All with default optimisation levels (-O2).
With gcc7 it's 26 to 75% quicker, gcc13 is 23-53% quicker and clang13 is 12-57% quicker.  Depending on how modern the host is and whether it's INFO or FORMAT dominated.
```
A chunk of GIAB truth set.  Single sample:
Seconds for dev / PR
seq4d           seq4-head1
gcc7    12.62 / 7.17    10.13 / 6.49
gcc13   10.65 / 6.96     8.65 / 6.29
clang13 11.87 / 7.55     8.61 / 6.49
gnomad-g1k.10k.vcf (many-samples):
seq4d           seq4-head1
gcc7 …
```
=> Speed up the VCF parser

header.c
sam_hdr_remove_lines and sam_hdr_remove_except are very slow when removing large numbers of header lines due to the effort of deleting hash entries one by one.  This commit instead rebuilds the hashes at the end of the deletion process.
Some stats on using sam_hdr_remove_lines on a sam file with one million RG entries.  The first run removes a single entry, the second 500,000 entries and the final one leaves only one entry.
The current timings:
```
time samtools view -R filter_1.txt 1M_test.sam -o most.bam
real	0m0.849s
user	0m0.745s
sys	0m0.088s
time samtools view -R filter_half.txt 1M_test.sam -o half.bam
real	30m6.381s
user	30m5.930s
sys	0m0.116s
time samtools view -R filter.txt 1M_test.sam -o single.bam
real	54m23.422s
user	54m22.656s
sys	0m0.176s
```
The new timings:
```
time …
```
=> Speed up removal of lines in large headers.

Makefile, bgzf.c, cram/cram_codecs.c, cram/cram_io.c, fuzz_settings.h, sam.c, vcf.c
* Skip CRC checks in fuzzing build mode
This may improve fuzzing coverage, as test runs won't get blocked by incorrect CRC values.
* Add some checks for large allocations in fuzzing build mode
Libfuzzer by default stops and reports out-of-memory if more than 2G is allocated.  Avoid this by adding code to catch inputs that trigger large allocations.  These tests are only enabled for fuzzing builds as they would prevent some legitimate inputs.
* Add a missing dependency for hts_open_fuzzer
=> Fuzz testing improvements

htslib/hts_endian.h
... so that the following code
```
static inline void u32_to_le(uint32_t val, uint8_t *buf) {
*((uint32_u *) buf) = val;
...
```
will not cause -fsanitize=alignment failures when building with Clang.
=> Apply the packed attribute to uint*_u types for Clang

hfile.c, htsfile.c, htslib/hfile.h, test/test_view.c
Revisiting the `stdin`/`stdout`/`dup` conversation from #1658:
>> Specifically the stdin/stdout code feels inherently wrong and I don't entirely understand why it's not just dealt with automatically as any other filename.
>
> `hopen_fd_stdinout()` just creates an `hFILE_fd` with an fd of 0 or 1. Hence `in = hopen("-", "r") … hclose(in) … in2 = hopen("-", "r")` would fail because fd 0 is no longer open or no longer refers to the original stdin. […] really this has caused no significant problems in all the years since it was implemented so far — largely because reading two BAM files from stdin or writing two BAM files to stdout just isn't a useful operation.
Reconsidering this… In fact it **has** caused some problems over the years: _htsfile.c_ needed some circumlocutions because it too …
=> Avoid really closing stdin/stdout in hclose()/hts_close()/et al

bgzf.c
A bgzip read with an offset asserts when the offset is invalid / above the file limit.
The assertion was from bgzf_useek when the offset position is beyond the uncompressed file size.
It is modified to return a failure in such case to avoid the assertion.
It might even be OK to remove the assertion but the "todo" comment along with it indicates some unclear case that an explicit failure seems better.
=> bgzf_useek fails when offset is above block limits

cram/cram_codecs.c
If we have an unofficial CRAM v4.0 encoded file and are attempting to use non-byte based data in an EXTERNAL encoded block, then we didn't free the cram_codecs structure when failing to parse and initialise.
Fixes oss-fuzz 62144
=> Fix a minor memory leak in malformed CRAM EXTERNAL blocks.

bgzip.1, bgzip.c, test/test.pl
This PR contains the changes for #1642.
Multiple files are supported and given operation is performed on all inputs, except with rebgzip.
Returns failure when multiple inputs are given with -I option.
Returns failure with rebgzip and index used together.
-b / -s options, which requires index file, work with single input when index is explicitly providing using -I.
-b / -s can work with multiple inputs if implicit indexes, i.e. \<compressed filename.gzi\>, are in use (i.e. no -I option
and all having their implicit index file along with it).
Corrected the error message with rebgzip invocation without -I option.
hfile.c/h, bgzf.c updated to add new methods which doesn't close the stdin/out, to support multi file processing.
=> changes to support multiple files

cram/cram_io.c
I suspect this was initially hard as on, but later made something we explicitly enable but forgetting to add that code into htslib.
On Illumina it made little difference, but wasn't detrimental. I need bigger data sets, but they're mostly on unavailable systems right now.  Small tests demonstrate utility though, specifically on decode speeds.
For other platforms:
Ultima Genomics
===============
Orig
real    0m25.784s
user    0m24.506s
sys     0m1.189s
real    0m9.155s
user    0m7.775s
sys     0m1.379s
RANS_ORDER_SIMD_AUTO
real    0m24.987s
user    0m23.699s
sys     0m1.219s
real    0m8.097s
user    0m6.635s
sys     0m1.461s
That's 13% quicker decode and 3% quicker encode.
It's mostly QS and tags:
$ ~/samtools/samtools cram-size -v _.cram|grep 32x16
BLOCK       10       617823        77895 …
=> Enable auto-vectorisation in CRAM 3.1 codecs.

htslib/vcf.h, kstring.c, vcf.c
Speeds up the VCF writer.  The main changes are:
- VCF writer can handle packed BCF objects, meaning we don't have to unpack before writing as VCF.
- Improve the GT formatting loop so once we've found it (often early on) we don't continue the penalty of looking again.  This assumes it only ever turns up once, but the VCF specification forbids duplicate keys.
- Optimise `bcf_fmt_array` on character arrays, treating them only as strings.  This is a bit vague in the spec, but I believe this code to be valid.
- Cache header key lengths to avoid repeated calls to strlen everywhere (`kputsn` over `kputs`).
Benchmarks showing 3 trials of "perf stat" cycle counts, in millions to make it easier to read, for develop (1st) vs this PR (2nd) on a variety of data sets.  The third number in parentheses …
=> Vcf write speed

bgzf.c, sam.c, vcf.c
* Change how virtual offsets pointing to the end of a BGZF block are adjusted to point to the start of the next block.  The previous method was not reliable when multi-threading as the block could be written out, and offsets included in the index, before the adjustment could be applied.  Fixes samtools/samtools#1861
* Switch from hts_idx_push() to bgzf_idx_push() for on-the-fly indexing of BCF and VCF.bgz files.  The latter function is needed to record the correct offsets when using multi-threaded BGZF compression.  Fixes samtools/bcftools#1985
* Only allow indexing of BGZF-compressed files.  It's necessary to enforce this as on-the-fly indexing assumes that the file pointer is in `htsFile::fp.bgzf`, but uncompressed VCF uses `htsFile::fp.hfile`.
=> Fix multi-threaded on-the-fly indexing problems

hfile_libcurl.c
Ensure that `to_skip` is updated correctly when handling a small seek by skipping data in libcurl_read().  In particular, if the number of bytes returned by wait_perform() exactly matches the number left to skip, `to_skip` needs to be set to zero, and wait_perform() needs to be called again to get some data for the function to return.
Fixes samtools/samtools#1918; possibly also #1037, #1625 and samtools/samtools#1622
@jmarshall I've made you author of ths commit, as it was your patch.  Let me know if you'd like to change anything before it gets merged.
=> Fix hfile_libcurl small seek bug

htslib/kseq.h
Port of @kloetzl's lh3/seqtk#123 and attractivechaos/klib#173 to HTSlib's copy of _kseq.h_.
Per the original PR: “Doubles throughput; can now parse FASTA at 2GB/s”.
For one large data file on my machine, this reduces klib's _kseq_bench2_'s `kstream` time from ~1.65s to ~0.92s.
(I have not heavily tested it otherwise.)
As [noted here](https://twitter.com/jomarnz/status/1661586585769611270), HTSlib doesn't use `kseq` itself though a few samtools commands do use it to read a few small BED files etc.
=> Apply seqtk PR to improve kseq.h parsing performance

cram/cram_io.h
46bcc3661 changed the memory block realloc from growing by size*1.5 to size*1.25, but neither are correct when the original size is very small.  Specifically the hts-specs test/cram/3.0/passed/1002_qual.cram file calls block_resize with b->alloc=2.  Doing *1.25 on this gives us 2 still due to integer rounding, and so an infinite loop occurs.
It never assumed we'd start with such a small block and it attempts to leap from size 0 to size 1024, but obviously allocating its own blocks to exact sizes and bypassing this initial block growth check.
Refactored the code so to remove the loop, remove the ?: for size 0, and generally just smarten it up a bit.
Tested on Illumina, Ultima Genomics and Oxford Nanopore files and it's no worse on speed / memory to before, and sometimes 2-3% quicker or …
=> Fix a cram decode hang from block_resize.

htslib/klist.h, htslib/kseq.h
Klist.h and kseq.h use calloc, realloc and memchr in static inline code, but if we wish to permit our external headers to be used from a C++ include then these all need explicit casts as "void *" doesn't work the same in C++ as in C.
It's tempting to use `extern "C"` in an `#ifdef __cplusplus` guard, but the nature of these pseudo-template klib headers is such that the code will be expanded up later inside a C++ file so the extern "C" doesn't solve it.
See #1674 and #1682
=> Add C++ casts for external headers.

htslib/hts_defs.h, sam.c
On long read data, the time to format SAM files is dominated by sequence and quality.
The qual[i]+33 loop to turn binary quals into printable ASCII is not vectorised by GCC without using -O3.  I would consider this a weakness of the compiler, but nothing I've done has persuaded gcc (before v12) to generate vector instructions.  Not even the "restrict" keyword.
Hence using __attribute__((optimize("O3"))).
The time the new add33 function is approx 15x quicker with gcc -O3 than gcc -O2.  Clang's and icc's default optimisation level gives speeds comparable to the gcc -O3.
With a compressed Illumina BAM this was just 3% overall speed gain to decode to SAM.  The extreme opposite is uncompressed ONT BAM which shows a 23% speed gain.
=> Enable optimisation level -O3 for SAM QUAL+33 formatting.

Makefile, test/usepublic.cpp
Add a C++ test file that includes all the public HTSlib headers, to verify that the headers compile cleanly when compiled as C++. At present they do not compile cleanly, due to the new problem identified in https://github.com/samtools/htslib/pull/1674#issuecomment-1743740305 and similar pre-existing problems in _klist.h_.
Rather than adding configury to find a C++ compiler, take advantage of Clang and GCC's drivers using C++ when given a _.cpp_ file. As this may not be true in general, add this test to `maintainer-check` only.
=> Add test case compiling the public headers as C++

cram/cram_index.c, cram/cram_stats.c
The warnings appeared due to the values only being used for `assert()` statements.  The one in `cram_stats_encoding()` is just checking some counts, so the variable is just annotated with `HTS_UNUSED` to silence the warning.
The `assert()` in `cram_index_build()` could actually be triggered with a suitably-adjusted cram file.  As it therefore detects bad inputs, it is replaced with code to write a better error message and return the documented value for read errors in this function.
The attached [bad_len.zip](https://github.com/samtools/htslib/files/13311396/bad_len.zip) file contains an example that can be used to test `cram_index_build()` via
```
./test/test_index bad_len.cram
```
=> Fix a couple of unused value warnings when built with NDEBUG

header.c, test/sam.c
If all the `@PG` records passed to `sam_hdr_link_pg()` form a single `PP` loop, all entries in the `sam_hrecs_t::pg_end` array it builds get set to -1, indicating that there are no chain start points. These entries are then removed to make the final list, but due to a bug in handling the case where there are no `PP` links the number of entries was incorrectly set to 1 instead of 0. This could lead to an out-of-bounds read in `sam_hdr_add_pg()` when linking new `@PG` entries to the existing ones.
Fix by ensuring that only valid end points are returned in the `sam_hrecs_t::pg_end array`, and the length is set to zero if no ends are detected due to a loop.
Adds a warning if a `@PG` record is found with a PP link to itself. Detecting longer loops is left for future work.  Fixes another …
=> Fix `@PG` linking when records make a loop

Makefile, cram/cram_codecs.c, cram/cram_decode.c, cram/cram_encode.c, cram/cram_io.c, cram/cram_structs.h, test/fuzz/hts_open_fuzzer.c, vcf.c
Fixes a raft of CRAM errors, with thanks to Octavio Galland for finding and reporting.
Draft as I have a few memory leaks when erroring out after failure to encode.
=> Cram fuzzing improvements.

test/fuzz/hts_open_fuzzer.c
This is because we don't know that ../c2.fa is a valid path as it's relative to where we are.  We can reenable with -DFUZZ_FAI.
=> Disable hts_set_fai_filename call in hts_open_fuzzer.

cram/cram_encode.c
In CRAM, sequence bases have to be stored for certain read features, even if the input record has SEQ set to "*" (i.e. no sequence stored).  In such cases, the sequence becomes a string of "N"s, which need to be accounted for when calculating how many items are put into a slice.  Failing to do this could lead to some data structures overflowing with certain unusual inputs. The number of Ns is set by the query-consuming operators in the CIGAR string, which can become quite large if you have lots of long insertions.
A limit is also set on the apparent sequence length of these records to prevent problems with excessive time and memory use when trying to encode them.  This also prevents issues with integer overflow if the apparent sequence length exceeded INT_MAX.
In cram_encode_container() …
=> Ensure no-stored-sequence reads are counted in container size

cram/cram_encode.c, cram/cram_io.c
=> More CRAM fuzz fixes (integer overflows)

vcf.c
The BCF limit of ~2GB per VCF row causes the parser to return an error. In this temporary solution we drop the excessive fields, typically these will be PL and other Number=G tags. in future work the library would automatically convert such tags into their localized alternatives (LPL).
=> Temporary workaround when excessive memory is required by FORMAT fields

cram/cram_encode.c
B tags need [eight bytes](https://samtools.github.io/hts-specs/SAMv1.pdf#subsubsection.4.2.4).  Previously this only checked for at least seven, which could lead to a single byte out of bounds read.  The impact of this is mostly limited by a [later check](https://github.com/samtools/htslib/blob/61b037bb881e85259f8df30c78d99ad3a357ed52/cram/cram_encode.c#L3144) on `blen`; however it was also possible that `blen` could overflow, allowing the check to incorrectly pass.  A second commit expands `blen` so it can't overflow, and ensures it has an acceptable value before passing it to the encode function.
=> Fix B aux tag length check in cram_encode_aux

faidx.c, hts.c
This change is for #1723 where misleading failure message is displayed.
The error number is reset if it is due to reference file access before reporting the error, to avoid misleading message.
Another change is made to avoid crash/invalid access in hts_close.
A change in samtools will also be raised to do null check before invoking hts_close.
=> fix for incorrect failure message with invalid reference file and crash fix

cram/cram_encode.c
In an attempt to fix memory leaks during encode of malformed CRAM data, that lead to bailing out early, we attempted to get everything to a uniform state as soon as possible.  Specifically s->aux_blocks get migrated to s->blocks earlier, so if we bail out we don't have the decision to make as to which bit of memory needs freeing.
That worked, but unfortunately I forgot that the compression is applied to s->aux_blocks and not s->blocks for auxiliary tags, so moving the blocks earlier gives uncompressed blocks in CRAM.  The format is valid and all tests pass, but it's overly large for obvious reasons.
Sadly this is a rather serious bug caused by an attempt to fix a really minor bug.
Fixes samtools/samtools#1968
=> Revert a bug from c1f4b7c where CRAM aux tags were not compressed.

sam.c
After calling these, bam_aux_get() expects three bytes to be available (two before the returned pointer).  While a test to prevent running off the end of the aux data was present, it didn't account for incrementing the returned pointer by 2.  The new version ensures that the expected data is available.
The bug could lead to a read of up to two bytes beyond the end of the aux data in bam_aux_get().  As a later call to skip_aux() would have correctly detect that the tag is invalid, bam_aux_get() should still have returned NULL, making it difficult to exploit the out-of-bounds access.
Fixes oss-fuzz 65820
=> Fix over-lenient check in bam_aux_first() / bam_aux_next()

cram/cram_encode.c
RG:Z tags without a proper NUL termination could lead to use of invalid data, or a heap overflow when the tag is passed to sam_hrecs_find_rg(), or hts_log_warning() if the former returns NULL.  Fix by moving the line that skips to the end of the aux tag and then checking that it was terminated correctly.  Should it not be, the aux parser is reset so the tag can be stored verbatim (the code that does that already handles badly-terminated Z tags).
Fixes oss-fuzz 66369
=> Fix possible heap overflow in cram_encode_aux() on bad RG:Z tags

cram/cram_io.c, cram/cram_io.h
While the Mistletoe reference has been chopped into segments of less than 2^31 bases, they were still long enough to cause an overflow in the load_ref_portion() `len` calculation.  This was due to the line endings taking the total over INT_MAX.  Fix be changing the data type of `start` and `end` to `hts_pos_t` so the entire calculation is done on 64-bit values.
Callers to load_ref_portion() are also updated where necessary to use `hts_pos_t`, making long references more likely to work should they ever be supported in CRAM.  All callers of callers were already using 64-bit values due to earlier upgrades.
There's a potential complication over calculating the MD5 checksums as the exported hts_md5_update() function takes an unsigned long for the length.  On 64-bit platforms with 32-bit …
=> Fix arithmetic overflow in load_ref_portion() on very long refs

bgzip.1, bgzip.c
Fixes #1718 
Updated bgzip to retain the file modification and access time during compression and decompression.
In Mac/linux it retains upto microsecond and in windows it does with second precision.
=> bgzip - modified and access time as in source file

faidx.c
This adds a small amount of extra information to errors when running `samtools faidx`, specifically it adds a helpful message when dealing with zero-length compressed data, which can occur eg: when downloading a file from the internet fails.
before:
```
$ bgzip < /dev/null > empty.gz
$ ls -l empty.gz
-rw-rw-r-- 1 nick nick 28 Feb  8 11:41 empty.gz
$ samtools faidx empty.gz
[faidx] Could not build fai index empty.gz.fai
$
```
after:
```
$ ./samtools faidx empty.gz
[E::fai_build_core] File truncated at line 1
[faidx] Could not build fai index empty.gz.fai
$
```
which is a pretty big hint that something has gone wrong in your tool chain somewhere.
... and also line numbers to some of the other error messages to make it easier to track down the problematic lines.
=> Make faidx error messages slightly more enlightening

htslib/hts_defs.h, sam.c, textutils_internal.h
There are a few issues with this.
hts_str2int and hts_str2uint are slightly inefficient.
- The use of unsigned char for "d" causes type conversions which are unnecessary.  All we care about is wrap around to positive values.
- The check on !fast normally passes for values that aren't huge, as we nearly always end before hitting that loop.  Hence we then pointlessly do devisions and a while loop with zero cycles, so we can lift that check up one left.
- Simplification of the overflow conditions.  This is not necessary as every possible positive number can be negated to negative without overflow.  (Overflow can only possibly occur when doing the reverse.)
The sam_parse_B_vals function is more tricky to nail. In attempting to speed up the str2int functions I found huge variation in speeds …
=> Speed up sam_parse_B_vals

sam.c
The pileup interface maintains a linked list of lbnode_t pointers. These start at iter->head, chain through lbnode->next, and then end up at iter->tail.  We also have a separate linked list in iter->mp of items we've previously freed, so we don't have to free and malloc continually.
bam_plp64_next adds and removes items to these linked lists, and it calls iter->plp_destruct when it puts items into the free list.  So far so good, and so correct.
However if for whatever reason we bail out of the pileup interface early, before we've punted all records onto the iter->mp free list, then we weren't calling plp_destruct on the current "in flight" data. This caused a memory leak, fixed in d028e0d.
Unfortunately there is a subtlety I didn't notice at the time.  The in-flight linked list goes from …
=> Bug fix the recent bam_plp_destroy memory leak removal

tabix.1, tabix.c, test/tabix/tabix.tst
Fixes #1735.
Added option to provide number threads to use, disabled by default.
Uses the thread pool in operations except listing of sequence names (-l).
=> added thread pool to tabix operations

bgzf.c, hts.c, hts_internal.h, sam.c
This is to ensure the timestamp on the index file is later than the one on the file being indexed, preventing spurious "The index file is older than the data file" messages when it's used.  The delay is necessary because the main file EOF block may not have been written when hts_idx_save_as() has been called.
Reworks the idx_save functions to add one that keeps the index handle open, storing it in the hts_idx_t struct.  hts_close() checks for this, and closes the index file if it finds one after having closed the file is was passed.  Unfortunately this means hts_close() will report any errors that happen when the index file is closed.  To reduce the chance of that happening, the index writer calls bgzf_flush() to reduce the amount of work that the final bgzf_close() on the index has to …
=> Delay closing the index file when indexing on-the-fly

test/noroundtrip-out.vcf, vcf.c
The removal of large tags introduced by https://github.com/samtools/htslib/commit/b49eea478114759efe19e718c38e7deb00614b21 and https://github.com/samtools/htslib/commit/9db565de3d89235f625de07363f1cd726c43f8f2 could not work correctly, the memmove pointers were wrong!
Resolves https://github.com/samtools/htslib/issues/1733
This is a fix of the botched pull request https://github.com/samtools/htslib/pull/1736
=>  Drop duplicate FORMAT tags and fix an error with dropping large tags

sam.c
It looks like it is meant to be a warning when a sam/cram file is using a CG tag (bam only in the spcec).
Fixes samtools/samtools#2002.
=> [minor] Change error to warning.

test/noroundtrip-out.vcf, test/noroundtrip.vcf, vcf.c
7ce510c added code to drop duplicate FORMAT tags, but missed the case where the duplicated entry was off the end of the per-sample data, so it hit the part that put in MISSING values.  This lead to an attempt to call memset() with a negative size.  Fixed by adding code to skip the duplicated FORMAT tag.
=> Fix duplicated but missing FORMAT bug

hfile.c
Failing to check this could cause an attempt to call a NULL pointer, where the plugin doesn't supply an isremote() implementation.
Fixes oss-fuzz 67349
=> Check that handler->isremote has been set before calling it.

htslib/tbx.h, tabix.c, tbx.c
This pulls in @jmonlong's implementation of Tabix indexing for [GAF files](https://github.com/lh3/gfatools/blob/master/doc/rGFA.md#the-graph-alignment-format-gaf), in graph node ID space.
This is to allow random access to bgzip-compressed GAF files in vgteam/vg using a tabix index.
=> Allow tabix indexing of GAF graph alignment files

hfile_s3.c
When following a 3xx redirection from AWS, `redirect_endpoint_callback()` wasn't putting `https://` on the new URL.  The redirection worked, but dropped back to http.  Obviously, this is not desirable.
Fix by prepending `https://` to ensure it uses TLS, and adding a bit of error checking to ensure all parts of the new url have been included.
Fixes #1760
=> Ensure S3 redirects use TLS

INSTALL
OpenSUSE doesn't seem to have a libdeflate package in an official release yet, but it's mentioned more prominently elsewhere now.
=> Further recommend use of libdeflate and list OS packages

cram/cram_io.c
Input files with very long CIGAR strings and consensus generated embedded reference can lead to exceptionally long CRAM blocks which overflow the check for large size fluctuations (to trigger new compression metric assessments).
Reformulated the expression to avoid scaling up values.
Fixes oss-fuzz 68225
=> fix fuzz integer overflow in cram encoder.

hts.c, htslib/hts.h, tbx.c, vcf.c
As noted on https://github.com/samtools/samtools/pull/2032 (which includes test queries exhibiting the problem):
> Additionally with this data file samtools goes into an infinite(?) loop when given [a particular location / query interval]: […]
>
> This can be traced to the `do … while` loop in `hts_itr_query()`, which loops perhaps forever through negative bin numbers. Possibly this code should check for a `beg` value massively beyond the maximum position covered by the index's bins and sidestep most of its processing. 
This PR checks start positions of query intervals against the maximum position representable in the index's geometry, to avoid negative bin numbers and the resulting infinite loops in the `do...while` loop. It's effectively the `beg` equivalent of #1595.
I considered …
=> Check interval start to avoid overflowing bin numbers

cram/cram_decode.c, cram/cram_decode.h, cram/cram_external.c, cram/cram_index.c, htslib/cram.h
Provide extra CRAM container manipulations and index queries.
Added to support extra functionality to `samtools cat`.
- Some internal cram functions are no longer static as they're called
from cram_external.c, but they don't have HTSLIB_EXPORT and aren't
an official part of the API.
These are cram_to_bam, cram_next_slice
- New public CRAM APIs:
These facilitate manipulation at the container level, both seeking to specific byte offsets, but also being able to specify containers as the n^th container listed in the index.
cram_container_get_coords returns refid, start and span fields from the opaque cram_container struct.
cram_filter_container copies a container but applies region based filtering, as already specified in the cram_fd with a range request.  (Note we currently also provide …
=> Extra low-level CRAM manipulation functions.

htslib/hts_defs.h, sam_internal.h
See https://github.com/samtools/htslib/pull/1677 for prior discussion.
I made the PR such that nibble2base is dynamically dispatched on x86-64 cpus with SSSE3 instructions. 
No build options need to be changed and nibble2base gets a nice speed up on the majority of the install base.
=> Make nibble2base faster using x86-64 pshufb instruction (SSSE3) and using dynamic dispatch.

synced_bcf_reader.c
Quoting from samtools/bcftools#2179:
> As the `…` in the `##contig=<ID=…>` lines unambiguously denotes a contig name (and there are no region strings anywhere near ID in the grammar, such as it is), passing this to `_regions_init_string()` as is is clearly a bcftools (or htslib) bug. Whatever the code is trying to do, it needs to do it by calling a dumber function that accepts only a contig name […]
The dumber function already exists and is already used by this code for all but the first contig header line. The code used `_regions_init_string()` rather than `_regions_add()` only when needed the first time to allocate a new `bcf_sr_regions_t` structure; instead extract basic initialisation into a new `bcf_sr_regions_alloc()` function and use `_regions_add()` exclusively.
As a bonus, the …
=> Use only _regions_add() in synced_bcf_reader.c when adding the list of contig names

hts.c, hts_internal.h, tbx.c
Text files badly transferred from Windows may occasionally be UTF-16-encoded, and this may not be easily noticed by the user — see for example, [this report of tabix woes](https://www.biostars.org/p/9530170/) (`??#` is as reproduced locally by me, and equally as confusing as the OP's output):
```
$ tabix myVcf.vcf.gz
[E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?
The offending line was: "??#"
[E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?
The offending line was: ""
[E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?
The offending line was: ""
```
It turned out that the text VCF file was UTF-16-encoded, and the lines returned contained alternating NULs when interpreted as ASCII C-strings, hence all lines appearing truncated to 0 or 1 or …
=> Warn if bgzf_getline() returned apparently UTF-16-encoded text

sam_internal.h
Selecting which version of nibble2base() to use on first call is fine in a single thread, but may lead to a race in multi-threaded code.  While this is likely harmless (the value stored to the function pointer will always be the same, and the update will probably be a single store), it is best to avoid the problem by making the selection at library initialisation, before any threads have started.
As the optimised nibble2base_ssse3() already uses gcc function attributes, it seems reasonable to use __attribute__((constructor)) on the function that selects the version to use.  If the constructor does not run, it will use the non-optimised version, which is a safe default.
=> Avoid possible race when selecting nibble2base implementation

hts.c
For a BED file with:
_chr1 1000 1000_
`samtools view -M -L intervals.bed $infile` worked with CRAM multi-region iterator but not with BAM.  This change makes them work the same.  Fixes samtools/samtools#2060.
NB Even though BED file format ([spec](https://samtools.github.io/hts-specs/BEDv1.pdf)) has a 0-based, half-open coordinate system, having the same beginning and end coordinate is valid.
=> Make BAM zero-length intervals work like CRAM

synced_bcf_reader.c
Replaces assert(0) with abort(). This ensures no behaviour change except the check is now not skipped when NDEBUG is defined.
Fixes #1791
=> Replace assert(0) with abort()

htslib/bgzf.h, test/test_bgzf.c
This bug crept in with #1772 which was added since last release, so there is no regression.
Fixes #1798 with thanks to John Marshall
=> Fix a missing bgzf->uncompressed_address incr in bgzf_read_small

cram/cram_encode.c
We check pos against the ref end, and if that fits we then fetch `&ref[apos]` to get the reference, but this understeps the array.
The fastest way to handle all this and other related errors is simply to sanity check the input for out of bounds POS and bail out early.
Fixes oss-fuzz 70014
=> Protect against negative POS fields in CRAM encoder.

.gitignore, Makefile, configure.ac, htslib/hts_defs.h, sam_internal.h, simd.c, test/test_nibbles.c
This PR moves `nibble2base_ssse3()` from an internal header file to a new source file, _simd.c_, and adds an ARM implementation `nibble2base_neon()` alongside. Because these functions are always called via a pointer, they are never inlined so there is nothing gained (other than build complexity!) by having them in a header.
I initially translated the SSSE3 algorithm directly to Neon, during which I noticed some tweaks that could be usefully applied to the SSSE3 version — see the “Minor improvements” commit below. I then realised that the Neon implementation could be simplified by using Neon's rather excellent interleaved load/store instructions, which I then replaced by an in-register zip as it is (sadly) faster (on aarch64 at least). (It may be possible to apply a similar approach for …
=> Refactor SIMD code and add ARM Neon nibble2base() implementation

.gitattributes, .github/workflows/windows-build.yml, test/header_syms.pl
The AppVeyor builds have become slower to launch and they're also a bit slow on execution.  GitHub Actions runs in about half the time.
Note this needs https://github.com/samtools/htscodecs/pull/123 merging first, but for purposes of testing I just incorporated it in this PR via an extra commit to change the submodule commit.  If the htscodecs PR gets modified in any way, changing the hash, then I'll update this appropriately.
Also, if you wish to see these tests in-situ here, we could copy this PR branch to samtools/htslib from jkbonfield/htslib as otherwise it won't enable the workflow.  (As I did for htscodecs)
=> Windows builds via GitHub Actions

faidx.c
- bgzf_getc is slow as it's a heavy function and not inlined.  Most of the time though it's just an array fetch, so inline the basic form and revert to the function call for the complex form.
- isgraph and all other ctype functions are slow.  We assume ASCII and just do a naive implementation.
The speed benefits are (seconds):
Old    New
Index GRCh38      13.4    8.4
Query chr1         1.7    0.9
Given a significant speed change for a small localised modification it seems worth while having.
=> Speed up faidx.

simd.c
As promised in https://github.com/samtools/htslib/pull/1795, here is the simplified version of the SSSE3 routine for nibble2base conversion. @jmarshall suggested that the unpack instructions could be used for a simpler routine and that is what is done here.
=> Simplify SSSE3 nibble2base function

faidx.c
While looking around for functions that could benefit from SIMD techniques a few weeks ago, I looked at `fai_retrieve()`'s search for (uncommon) non-graphic characters. However I soon realised that it already knows exactly where these characters are, so doesn't need to search or check for them at all!
Because `fai_retrieve()` is given only well-formatted input containing lines of the same length, it already knows exactly where the base and non-graphic characters are. So in general the interval to be read will look like
```
......ATGCAT    (read last six bases and line terminator)
ATGCATGCATGC    (read complete line including line terminator)
ATGCATGCATGC    (read complete line including line terminator)
ATGC........    (read first four base characters)
```
and can be read a line at a time …
=> Speed up fai_retrieve() by reading whole lines at once

htslib/kstring.h, test/test_kstring.c
The kputuw function is considerably faster as it encodes 2 digits at a time and also utilises __builtin_clz.  This changes kputll to use the same 2 digits at a time trick.  I have a __builtin_clzll variant too, but with longer numbers it's not the main bottleneck and we fall back to kputuw for small numbers.  This avoids complicating the code with builtin checks and alternate versions.
An alternative, purely for sam_format1_append would be something like:
static inline int kputll_fast(long long c, kstring_t *s) {
return c <= INT_MAX && c >= INT_MIN ? kputw(c, s) : kputll(c, s);
}
#define kputll kputll_fast
This works as BAM/CRAM only support 32-bit numbers for POS, PNEXT and TLEN anyway, so ll vs w is an irrelevant distinction.  However I chose to modify the header file so it fixes other …
=> Speed up kputll.

.gitignore, Makefile, htslib/khash.h, test/test_khash.c
Note draft because samtools/samtools#2081 needs to be merged first, to fix a dependency on hash table ordering on some outputs.
The existing X31 hash propagates bits fairly slowly, resulting in a poor distribution of keys if most of the differences in strings are at the end.  Fix by using FNV1a instead, which is a similar speed to calculate but distributes keys much more effectively.  While this cannot completely solve the problem of certain inputs distributing badly, it hopefully makes it less likely to accidentally find one.
Includes kh_stats() function in khash which produces a histogram of probe chain lengths and a khash test framework.  The test program can also be used to benchmark insertion and lookup times.
Some benchmarking results are listed below.  The "Numbers" input is the …
=> Use FNV1a for string hashing

.github/workflows/windows-build.yml, README.md
Use the mingw-w64-x86_64 flavour of all packages.  Add curl, so hfile_libcurl etc. build.  Remove the mingw git package as git for windows is already present.  Add the location of git for windows to `$PATH` (note this must be at the end, else the wrong shell gets picked up when running tests leading to backslash conversion issues).
Switch badge on README.md from AppVeyor to GitHub.
=> Adjust GitHub actions windows build package list

hts.c, hts_expr.c, vcf.c
As reported by clang (gcc finds fewer).
Ie [nasal demon](https://deathandthepenguinblog.wordpress.com/2021/02/13/undefined-behaviour-and-nasal-demons-or-do-not-meddle-in-the-affairs-of-optimizers/) avoidance.
=> Fix some minor undefined behaviours

sam.c, test/sam.c, vcf.c
Help avoid overflow on arithmetic involving POS, MPOS and TLEN by limiting values in the SAM parser to fit in 62 bits (or 63 for TLEN as it's signed).  The new limit is still massively bigger than any known reference so it should not cause any problems in practice.
The actual problem reported was a signed value overflow [in `process_one_read()`](https://github.com/samtools/htslib/blob/fbe5ff6c/cram/cram_encode.c#L3851).  Getting this calculation to work correctly for the entire range of `int64_t` would be complicated.  It's easier just to ensure the inputs are within a range where overflow cannot happen.
Fixes oss-fuzz 68750
=> Stricter limit on POS/MPOS/TLEN in sam_parse1()

cram/cram_encode.c
We check pos >= ref_len, but didn't check for pos 0 (aka -1 in BAM).
Fixes oss-fuzz 70917
=> Protect against mapped CRAM records at POS 0.

hfile.c
Otherwise, we might try to `hread()` a `NULL` pointer.
Fixes oss-fuzz id 71069
=> Check underlying hopen() worked for preload: URLs

.cirrus.yml, .github/workflows/windows-build.yml, Makefile, bgzip.c, htsfile.c, htslib/vcf.h, test/hfile.c, test/test-bcf-sr.c, test/test-bcf-translate.c, test/test-bcf_set_variant_type.c, test/test-vcf-api.c
Due to cirrus-ci lacking ubsan in the clang installation it needed a bit of juggling as to what checks are executed in which compiler, but this now allows us to automatically spot some undefined behaviour via the CI system.
=> Add undefined behaviour sanitizer into the CI checks

hts.c
SAM and VCF files opened for write both start with `htsFile::format.format` set to `text_format`, and then update it after writing the header.  This means it's possible to open a `text_format` file with compression, so `hts_hfile()` needs to handle it in the same way as SAM and VCF.
Noticed when `hts_set_opt(fpout, HTS_OPT_BLOCK_SIZE, BAM_BLOCK_SIZE)` failed in `samtools sort` in the case where the output was a compressed SAM file.  At this point `fpout` was a `text_file`, so the wrong pointer was passed to `hfile_set_blksize()`, which luckily bailed out and returned -1 before doing any damage to the incorrectly passed-in structure.
=> Fix hts_hfile() for compressed text_format files

samples/Makefile, samples/write_fast.c
The _samples/write_fast.c_ code confusingly never instantiated `out_samhdr`, and doesn't really have a header to supply. It got away with this because writing FASTA/Q doesn't actually need a header, so this PR makes that explicit.
Cast `time_t`, which isn't necessarily a `long` itself.
Use the usual `-rm -f` incantation so that doing `make clean` twice completes without diagnostics even when the `$(PRGS)` files already don't exist.
=> Several minor samples/ fixes

cram/cram_external.c
`cram_block_compression_hdr::tag_encoding_map[]` has `CRAM_MAP_HASH` elements, so the iterator should not go beyond that.
=> Fix out-of-bounds read in cram_codec_iter_next()

Makefile, README.md
The awk script used to extract htscodec's version string (if `git describe` fails or returns a hash) used a three-argument form of `match`, which is a GNU extension.  Rewrite for better compatibility with other awk implementations, notably `mawk`, which supplies awk in some Cirrus-CI images.
This doesn't appear to show up on HTSlib's tests, which get a suitable version number from `git describe`, but [does on SAMtools'](https://cirrus-ci.com/task/6105782926704640?logs=htslib_compile#L96) where HTSlib (and so htscodecs) is cloned separately.
Also fix the cirrus-ci badge, which linked to the wrong location.
=> Fix gawk-ism in Makefile

NEWS
* Fix list of new cram functions
* Add PRs #1831 #1832
* `bgzf_getline()` warning about UTF-16 is a feature, not a bug-fix.
=> Add last-minute NEWS items for release

hts_internal.h
When checking for another delimiter before .gz or .bgz, the pointer into the string was decremented without checking to see if was at the start.  This could lead to a one byte read before the start of the string when copying out the delimiter.
Fixes oss-fuzz id 71740
=> Fix possible 1 byte underflow in find_file_extension()

sam.c
With long aux tags the trival while loop can be suprisingly slow.
"while (s < end && *s) ++s;" isn't well vectorised or turned into word-by-word processing by neither gcc nor clang, but these tricks are used by the system memchr implementation.
An alternative could be this (used in my WIP VCF parser), which is more optimised for relatively short strings.  Included here just for potential future reference on systems with noddy memchr implementations.
#define haszero(x) (((x)-0x0101010101010101UL)&~(x)&0x8080808080808080UL)
static inline char *memchr8(char *s, char sym, size_t len) {
const uint64_t sym8 = sym * 0x0101010101010101UL;
uint64_t *s8 = (uint64_t *)s;
uint64_t *s8_end = (uint64_t *)(s+(len&~7));
while (s8 < s8_end && !haszero(*s8 ^ sym8))
s8++;
// Precise identification
char …
=> Replace home-brew string end searching with memchr.

synced_bcf_reader.c
When an empty VCF file with a header but no data lines is indexed, tbx_seqnames() called via bcf_sr_add_reader() returns an empty list. Consequently, when bcf_sr_regions_next() is called and no in-memory regions are available, it attempts to read from a file which is not initialized.
This fixes https://github.com/samtools/bcftools/issues/2286
=> Prevent segfault on empty tbi index

cram/cram_encode.c, cram/cram_io.c, cram/cram_structs.h, test/sam.c, test/test.pl
If the sequences align off the end of the reference and we are creating consensus on the fly, then the consensus generated also steps beyond the reference length.  Although this longer reference is embedded, it is trimmed back by the CRAM decoder which validates against the declared reference length in SQ LN, leading to Ns appearing in the decoder.
Therefore we now validate in the encoder too, which also needed refs_from_header updates to parse the LN tag so the encoder can trim. Note we already overloaded r->length==0 for an indication that we've not parsed the fa/fai file yet, so we can't just naively fill this out from the SQ LN header.  We could hold this information elsewhere via a proper flag and modify all the places that utilise that knowledge, but the simplest (and safest) fix is …
=> Fix CRAM embed_ref=2 with seqs overlapping ref end.

cram/cram_encode.c, cram/cram_io.c
We shouldn't be attempting to create embedded reference sequences for CRAM containers with reads mapped to chr -1 (ie unmapped).  We don't permit embed_ref in multi-ref mode and it's nonsensical for entirely unmapped data.
The only real fix needed here is `&& c->ref_id >= 0` just before calling cram_generate_reference(), but checking elsewhere can sidestep other potential issues and we have safety in checking in more than one place.
Fixes oss-fuzz issue 372547397
Note the following test triggered it, but it's only for that most recent commit and 1.21 was fine so this is a brief regression.
```
@SQ	SN:foo	LN:999
x	4	*	1	0	*	*	0	0	ACGT	PQRS
```
=> Fix issue created in PR#1848

htslib.pc.in
I noticed that `htslib.pc.in` specifies `-lhts` in both the `Libs` and the `Libs.private` fields. This causes problems when using HTSlib from vcpkg, because vcpkg [merges](https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_fixup_pkgconfig) the latter field with the former, resulting in `Libs: "-L${libdir}" -lhts "-L${libdir}" -lhts -lhtscodecs "-L${prefix}/lib" -lm -lpthread`. This causes CMake to remove the first `-lhts`, which causes link errors because of undefined symbols from htscodecs.
This PR fixes this by removing `-lhts` from `Libs.private`. According to [my understanding of pkg-config](https://people.freedesktop.org/~dbn/pkg-config-guide.html#:~:text=Libs%3A%20The%20link%20flags%20specific,but%20not%20exposed%20to%20applications.) the duplication in both `Libs` …
=> Remove `-lhts` from `Libs.private` in the pkg-config file.

header.c
Parameter check on argument 'position' was not accounting for 0 based indices as per header description:
/* sam.h
/// Remove nth line of a given type from a header
/*!
* @param type     Type of the searched line. Eg. "SQ"
* @param position Index in lines of this type (zero-based). E.g. 3
* @return         0 on success, -1 on error
*
* Remove a line from the header by specifying the position in the type
* group, i.e. 3rd @SQ line.
*/
HTSLIB_EXPORT
int sam_hdr_remove_line_pos(sam_hdr_t *h, const char *type, int
position);
*/
=> BUGFIX header.c sam_hdr_remove_line_pos()

bgzf.c, htslib/hts.h
This follows on from the hts_md5* functions which wrap up either OpenSSL or our own implementation.  Libdeflate's crc32 function is considerably faster than the native zlib, so we want to use it in (for example) the new "samtools checksum" code, but we do not wish to add baggage of looking for libdeflate in the configure script.
=> Add an hts_crc32 function to use zlib or libdeflate.

configure.ac, hfile.c
Commit e495718 changed bgzip from unix raw POSIX read() calls to hread().  Unfortunately hread gets its buffer size from stat of the input file descriptor, which can be 4kb for a pipe.  We're reading 0xff00 bytes, so this ends up being split over two reads mostly, with one or both involving additional memcpys.  This makes the buffered I/O worse performing than non-buffered.  In the most extreme cases (cat data | bgzip -l0 > /dev/null) this is a two fold slow down.
The easy solution is just to increase the buffer size to something sensible.  It's a little messy as we have to use hfile_internal.h to get hfile_set_blksize, but it works.  I'm not sure why we didn't elect to make that API more public.  Probably simply out of caution.
Fixes #1767
=> Increase the input block size for bgzip.

test/test-bcf_set_variant_type.c, vcf.c
it was incorrectly assumed that the ALT allele is
of equal length to REF allele, but the VCF specification allows breakend insertions, such as C > CAGTNNNNNCA[2:321682[
Resolves https://github.com/samtools/bcftools/issues/2317
=> Fix a bug in breakend detection

cram/cram_decode.c, cram/cram_encode.c, cram/cram_io.c
Introduced in 24e4e31 with the cache of the LN_length field.  We now validate this as positive.  The check in cram_encode.c should now not be necessary, but it's fixed in two places incase we ever get this cropping up via another route.
Fixes oss-fuzz issue 382922241
=> Fix cram_encode fuzzer issue caused by negative reference lengths.

cram/cram_codecs.c, cram/cram_io.c
Our htscodec name tokeniser decoder always adds nul bytes between names.  This happens to match the default STOP byte used in htslib's CRAM implementation, but there's nothing to say it has to be 0 and indeed Java uses 9 (tab).
This is an oversight and ideally we'd change the name tokeniser decode function to take an additional parameter to specify the stop byte, but that's changing the API.  Easiest is just to recognise this on-the-fly and correct the error by looking for a different stop byte.
Also fixed cram_uncompress_block setting of b->orig_method.  This was only correct when the original prototype definitions of RANS_PR0 were in use, and with the RANSPR official numbering the calculation caused RANSPR with method RLE+O1 to be mislabelled as TOK3.
This field isn't used in anything …
=> Allow BYTE_ARRAY_STOP to work on non-zero STOP code with TOK3.

htslib/synced_bcf_reader.h, synced_bcf_reader.c, test/test-bcf-sr.c, test/test.pl
Fixes #1862 
Added bcf_sr_add_hreader to add already opened htsfile to reader list.
The file added can be set to close along with reader or closed explicitly by user. Aux data in synced_bcf_reader.c is updated to hold the file closure status.
When the file name is passed along with file pointer, the index can be anywhere and mentioned using ##idx## method with file name.  As file name in htsfile does not maintain index information, the index has to be present in default location with default name (i.e. same location as file with file name.<index extension>) when no filename is passed to this method.
bcf_sr_add_reader updated to open the file and passes the file to bcf_sr_add_hreader with autoclose enabled.
Test utility and script updated to use the new interface. With -u argument, it uses …
=> update to use htsFile in synced reader (for #1862)

vcf.c
Currently bcf_has_variant_types always returns 0 when testing for the presence of VCF_REF, regardless of the actual type
=> Make it possible to test for VCF_REF as declared in the documentation

htslib/thread_pool.h, thread_pool.c
This returns a numeric value from 0 to nthreads-1 corresponding to the current running thread, or -1 if unthreaded or the thread does not correspond to one allocated to this pool.
It may be used to associate data to a thread rather than to a job. For example maintaining one open file handle per thread spawned.
=> Add hts_tpool_worker_id() API

vcf.c
Variant type calls produced by `bcf_set_variant_types()` may be stale after updating alleles via `bcf_update_alleles()` or `bcf_update_alleles_str()`, so set `d.var_type` to -1 to force a recalculation.
Fixes an out of bounds access in bcftools consensus that occurred when it added a new allele to a record.
=> Reset variant types after updating alleles

Makefile, configure.ac, sam_internal.h
We released a new pysam based on HTSlib et al 1.21 last week, and now #1838 has been re-reported as pysam-developers/pysam#1327. So that nobody gets more support requests, it would be good to fix it so that the _simd.c_ code is disabled for these ancient compilers.
Playing with the [Compiler Explorer](https://godbolt.org/), I confirmed that GCC ≤ 4.8.5 cannot compile _simd.c_, while GCC ≥ 4.9.0 can. I considered `HTS_GCC_AT_LEAST(4,9)` but realised that the existing `HAVE_SSSE3` appears to be exactly what is needed.
However further Compiler Exploration showed that GCC ≤ 4.8.5 can compile these intrinsics with `-mssse3` but not with merely `__attribute__((target("ssse3")))`, which fails to enable the intrinsics. Hence the right approach is to actually use some intrinsics in the configure …
=> Make HAVE_ATTRIBUTE_TARGET check also check that SSSE3 intrinsics work

htslib/sam.h
The helper function `bam_set1()` is great for creating `bam1_t`s from scratch. However I fell over a foot gun in using it. I expected to be able to pass ASCII text as from a fastq file; instead to use the function correctly one first needs to subtract 33 from each char of the quality string.
=> Clarify bam_set1 parameter documentation.

header.c, sam.c
Fixes #1866
Updated to use 1st LN tag value as in cram handling.
Accepts duplicate LN tags as long as they have same value.
If the values differ, returns failure.
sam_hdr_create updated for sam file checks and sam_hdr_sanitise for handling bam and cram.
sam_hdr_sanitise calls sam_hdr_fill_hrecs and in turn sam_hrecs_update_hashes, where duplicate check is made.
For cram, there is no added overhead as fill_hrecs is already in use.
For sam and bam, the sanitise update adds as overhead which is required to identify the duplicates.
For sam, the check occurs during normal parsing in sam_hdr_create and sanitise update is redundant.
For bam, fill_hrecs update is required to identify the duplicates. sanitise seem to be the best common place to have this.
=> update to fail on duplicate LN tags, with different LN values

hts.c, htslib/bgzf.h, htslib/kstring.h, sam.c, vcf.c
While investigating pysam-developers/pysam#1328, I noticed that in a number of cases `hts_itr_multi_next()` returns -1 after `iter->seek(…)` failure. -1 returned from this function (and from `sam_itr_next()`, which for multi iterators just returns this function's result) indicates a successfully reached EOF. Hence seek failure at these locations in the code results in `samtools` or other invoking code **silently omitting data** for multi-region queries.
A full audit of HTSlib functions that return ≥0 record / -1 EOF / ≤-2 error found a handful of other instances of incorrect -1 returns in `sam_read1()` and `vcf_parse()` and hence `bcf_read()`.
It also found a documentation error for `bgzf_getc()`, which does indeed distinguish between EOF and errors.
The usual reason for kstring functions …
=> Return errors instead of EOF after all I/O errors etc in `hts_itr_multi_next`/`sam_itr_next`/`sam_read1`/`vcf_parse`/`bcf_read`

htslib/vcf.h, tbx.c, test/test-vcf-api.c, vcf.c
rlen set based on version, position, end, svlen and format len.
depends on PR #1861 (rebased).
recalculates rlen on END and SVLEN info field update, LEN format field update and allele updates.
test updated for validation of rlen calculation.
4.3 uses END and reference length
4.4 uses END, SVLEN and reference length
4.5 uses SVLEN, LEN, reference length
When SVLEN/LEN is not present, it is inferred from END. It is made irrespective of version and no. of alleles, to make it simple and it seems OK.
Cross check of SVLEN with allele is made only for INS, as it is expected to be '.', resulting in 0, for non - SV alleles.
Note: 
Version change may necessitate rlen recalculation and needs to trigger it. It is not handled in this PR.
Until it is made, we may have to save as vcf and reload to have …
=> rlen calculation for vcf 4.4, 4.5

vcf.c
See https://github.com/samtools/bcftools/issues/2395 and https://github.com/samtools/bcftools/pull/2404
=> Use the highest VCF version when merging headers

cram/cram_decode.c
With mismatching ref_id and SQ headers this turned into a null pointer dereference.
Fixes oss-fuzz issue 418125747
=> Protect the failed reference error message.

Makefile
Update the wildcard to include source files and directories added since this was added in 2015 and last modified in 2017. Give up on omitting _**/README.md_ even though they are omitted from proper release tarballs, as we want to include _README.large_positions.md_.
In particular add the bundled parts of _htscodecs/**_ and ensure that _htscodecs/htscodecs/version.h_ has been built so is present in the distribution directory. (HTSlib's _version.h_ continues to be built via `version.sh` and omitted from the distribution directory.)
With this, `make distdir=../dist` produces a directory with the same files as the htslib-1.21 release tarball, modulo the addition of _README.md_ files and several expected test output files added on **develop** since the last release.
Fixes #1846.
=> Update distdir target to include more recent source files

NEWS
Some trivial suggested updates, notably and motivated by correcting the spelling of a contributor's name.
=> Trivial NEWS updates including correcting a name's spelling

Makefile, NEWS
Remove a stray `fi` and the misleading indentation that made it difficult to spot.
It's odd that this has gone unnoticed for so long, as the script has run successfully in the past (most recently adding symbols for `HTSLIB_1.21`).
To test, it's necessary to do something like:
```
make htslib.map PACKAGE_VERSION=1.22
```
so it thinks it needs to add new versioned symbols.
=> Fix symbol version file building script

NEWS, configure.ac, ref_cache/http_parser.c, ref_cache/listener.c, ref_cache/log_files.c, ref_cache/main.c, ref_cache/options.h, ref_cache/ping.c, ref_cache/poll_wrap.h, ref_cache/poll_wrap_epoll.c, ref_cache/poll_wrap_poll.c, ref_cache/request_handler.c, ref_cache/server.c, ref_cache/transaction.c, ref_cache/upstream.c
Fixes a log rotation bug, and a number of others discovered when testing on 32-bit NetBSD and alpine.
* Deal with alternate layouts for `struct msghdr`
* Unhide some symbols that disappear when `_X_OPEN_SOURCE` is set.
* Add configure checks for `AI_V4MAPPED` and `AI_ADDRCONFIG`
* Fix a use after poll_free() bug in the `poll()` based poller.
* Fix the length of the response string in `handle_hello()`
* Add poll debugging printfs
* Fix poll bugs that could cause event loop spinning, or transactions becoming deadlocked when not using edge triggered `epoll()`.
* Fix type casts to silence signed-compare warnings.
There is still one warning when compiling on alpine due to a signed compare issue in musl libc's definition of `CMSG_NXTHDR`.  As this is in the musl header files, it cannot be fixed …
=> ref-cache bug fixes and portablilty improvements

ref_cache/main.c, ref_cache/server.c
Work around problems caused by symbols being hidden when defining `_POSIX_C_SOURCE` or `_XOPEN_SOURCE`:
* The `IN6_IS_ADDR_V4MAPPED` macro fails to compile on glibc before 2.25.  Fix by avoiding it and using `memcmp()` to match the prefix it detects instead.
* macOS SDKs before 12.0 hid `O_DIRECTORY`.  Fix by defining `_DARWIN_C_SOURCE` to get it back.
Thanks to @jmarshall for spotting these problems, which affected Conda builds even on modern systems.
Replaces and closes #1927
=> Fix compilation against older glibc / macOS SDK

.cirrus.yml
Combining `-O3` with `-fsanitize=address,undefined` leads to slow builds and high compiler memory consumption.  Speed up compilation by switching to `-Og`.  Even though less optimisation is done, tests still run at an acceptable speed and the total run time is faster.
=> Change optimisation for -fsanitize=address,undefined test build

configure.ac
Fix typo that incorrectly made configure report an error about not being able to build ref-cache if libcurl was not available. If ref-cache is not explicitly requested, it should just print a warning.
Fixes #1926
=> Fix typo in ref-cache configure check for libcurl

sam.c
It's undefined behaviour to pass a null pointer into `memcpy`, which trips up UBSan with the following error:
```
runtime error: null pointer passed as argument 2, which is declared to never be null
```
A lot of the `memcpy`s in `sam.c` already guard against 0-length spans so do the same in these 2 places which can be hit when duplicating an empty header and when adding a 0-length array.
=> Guard against memcpying 0-length spans

hts_internal.h, tbx.c, test/test-vcf-api.c, vcf.c
PR #1897 updated the VCF rlen calculation in line with VCF 4.4, including taking account of INFO `SVLEN` for non-INS alleles.  This was not correct though as it included non-symbolic alleles if they (incorrectly) had a non-missing `SVLEN`; and other types of symbolic allele that do not affect the length with respect to the reference. In fact, only deletions can have an affect on rlen, so this changes the calculation to only use `SVLEN` for `<DEL>` alleles.
A bug is also fixed on big-endian platforms where INFO and FORMAT values were being accessed incorrectly.  These are always stored in little-endian order, so need to be converted to native ordering when read.  The tests are updated to include values greater than 128 to ensure that this works correctly.
Fixes #1940
=> For the VCF rlen calculation, only use SVLEN for DEL, DUP and CNV symbolic alleles
