vcf.c
bcf_hdr_append() followed by bcf_hdr_write() should not make a
subsequent bcf_read() call fail if tag IDs remain unchanged, as
in the issue #213
=> fix in VCF header parsing

Makefile, hfile.c, htslib/bgzf.h, htslib/hfile.h
Key things to review:
- Is use of the "specific" field of htsFormat appropriate?
- How does any of this (or how SHOULD any of this) impact on vcf/bcf?
=> Output fmt option

cram/cram_index.c, cram/cram_index.h, hts.c, htslib/hts.h, htslib/sam.h, htslib/tbx.h, htslib/vcf.h, sam.c, tbx.c, vcf.c
Please review proposed API (naming, usage of `fnidx==NULL`, etc)…
=> Add index build/load functions with explicit index filenames

htslib/vcf.h, vcf.c
This is a htslib-side fix for samtools/bcftools#208
=> deprecate bcf_hdr_combine in favour of new bcf_hdr_merge

tabix.c
=> tabix: fixes --only-header option so that is now works!

cram/cram_codecs.c, cram/cram_codecs.h, cram/cram_encode.c, cram/cram_external.c, cram/cram_io.h, cram/cram_structs.h, htslib/cram.h
Note: PR against cram_reheader_2.1.
The analogous branch for Samtools.
=> Samtools cat for CRAM files

hts.c
=> File format strings can now be specified uppercase or lowercase.

hfile.c
Finally implementing this TODO, as this has caused trouble out in the real world.
Re `hfile_exit()`, seems like all bets are off for `atexit` functions in multithreaded programs (cf this [libguestfs bug report](https://bugzilla.redhat.com/show_bug.cgi?id=790837)), but if other threads are still opening files when someone calls `exit`… well, what can you do…
@daviesrob @jkbonfield **other-pthreads-experts**: does this look sufficient / about right?
=> Wrap load_hfile_plugins() in a critical section

tabix.1
-C --csi had duplicate of previous line. Add proper CSI mode description (Fixes #348).
=> Fix tabix man page CSI option

vcf.c
Fixes stack smashing in vcf_parse_format if the FORMAT field contains more than 255 items.
=> Limit number of FORMAT items to maximum allowed by bcf1_t n_fmt field

cram/cram_index.c
Eliminate repeated error handling code in `cram_index_load`, and ensure
that `fd->index` in freed and set to NULL (by calling `cram_index_free`)
when exiting on failure.  Setting `fd->index = NULL` is important as
otherwise repeated calls to `cram_index_load` using the same fd after an
error will apparently succeed even though the index has not been loaded
(this can happen, for example, if a caller is trying different names for
the index).
Ensure that realloc failures won't cause memory leaks, and that the
value of `fd->index_sz` is always correct as it's used by `cram_index_free`.
=> Fix error handling in cram_index_load.

Makefile, NEWS, hfile.c, hfile_internal.h, hfile_libcurl.c, hts.c, hts_internal.h, htslib/hfile.h, htslib/hts.h, multipart.c, test/hfile.c, test/sam.c, textutils.c
This is the GA4GH stuff finally ready to merge.  There was one more gnarly bug at the end there…
One further thing to add to this is a minor _htsfile.c_ reorganisation to facilitate testing this with `htsfile -c`.  Or that can come later on **develop** post-merging.
=> GA4GH streaming protocol

vcfutils.c
* handle cases with missing data
* remove asserts to give more informative error messages
Fixes samtools/bcftools#213, samtools/bcftools#256, samtools/bcftools#322, samtools/bcftools#404
=> allele trimming bugfix

vcf.c
Fix multiple crashes discovered by fuzz testing with American Fuzzy Lop.
* Prevent reads past the end of the VCF header.
* Make bcf_read1_core() return an error if ks_resize fails() or on a short read.  Should make the BCF reader better at reporting I/O errors as well as malformed files.
* Add bcf_record_check() to validate BCF records.  Checks that IDs are within the range given in the header, and that certain record elements are a sensible type.  It also ensures that bcf_unpack() won't run off the end of its input buffers.
Benchmarking suggests that bcf_record_check() has a minimal impact on BCF read speed, for example reading a chr. 22 bcf file I got:
Current devel:      11.436286906 seconds time elapsed
This PR:              11.483674794 seconds time elapsed
Currently …
=> Improve VCF/BCF error checking

cram/cram_structs.h, regidx.c, test/test_view.c, test/thread_pool.md, thread_pool.c
Fixed some minor issues: pointer offsetting with void pointers (which is not supported in standard C) and missing include directives. Also added some documentation for the thread pool test program.
=> Portability and docs

hts.c
Resolves https://github.com/samtools/htslib/issues/478
=> Prevent infinite loop on empty indexes

cram/cram_decode.c, cram/cram_io.c, cram/rANS_byte.h, cram/rANS_static.c
Fixes the identified RANS bugs plus some issues with embedded references.
=> Rans hardening

NEWS
(Ideally merge on day on release, editing date if required.)
=> NEWS update.

bgzf.c, cram/cram_codecs.c, cram/cram_io.c, faidx.c, hfile.c, hts.c, htslib/hts.h, multipart.c, sam.c, tbx.c, test/test-logging.pl, vcf.c, vcfutils.c
Replaced all the fprintf(stderr, ...) calls that already made use of the hts_verbose setting into hts_log_... calls.
This is the second pull request in a series that aims to solve https://github.com/samtools/htslib/issues/403 .
=> Logging improvements 2

Makefile, faidx.c, hts.c, htslib/hts_log.h, htslib/vcf.h, knetfile.c, regidx.c, sam.c, synced_bcf_reader.c, tbx.c, vcf.c, vcfutils.c
Replaced another batch of fprintf(stderr, ...) calls with hts_log_... calls, this time aiming to cover everything except the CRAM code.
Also fixed some missing header file dependencies in the Makefile that I happened to find.
This is the third pull request in a series that aims to solve #403 .
=> Logging improvements 3

sam.c
Standardize the error codes resulting from functions calling cram_get_bam_seq.
------
Currently a CRAM parsing error from a call to `sam_read1` results in an return code < -1 (where -1 is used to indicate a non-error end of stream condition). This patch standardizes the CRAM error handling to other functions which call `cram_get_bam_seq`, such that errors can be detected from the return values of methods like `hts_itr_next`.
=> Make CRAM error reporting more consistent

hfile_libcurl.c
https://curl.haxx.se/libcurl/c/threadsafe.html states that handles
should not be accessed from more than one thread at the same time.
This makes having a global cURL multi handle problematic in code
that could be called from multiple threads.  Solve this by using
a multi handle for each hfile and introducing a global cURL share
handle (with suitable locks) for DNS caching.
=> Make hfile_libcurl work with multiple threads

vcf.c
Fixes potential segfaults, as reported in #593 and #594.
=> Fixes potential seg faults.

hts.c
=> Fixes compiler warnings.

hfile_libcurl.c
Always call curl_multi_timeout(), even if curl_multi_fdset()
returned a negative value for maxfd.  It frequently returns
zero in this case, indicating that work still needs to be done.
The timeout is also set to a maximum of 100ms when maxfd < 0, as
recommended by the curl_multi_fdset() manual page.
If fp->perform_again is true, the calls to curl_multi_fdset() and
curl_multi_timeout() are skipped completely as the values
calculated were not used.
Fixes #633 (Curl vs knet speeds).
Some quick benchmarks grabbing 192 locations from a yeast BAM file, served from localhost:
```
time ./test/test_view-knet -B http://127.0.0.1:31338/18429_1%231.bam `for p in $(seq 1530000 10 1531917);do echo chrIV:$p-$p;done`
[E::knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged
real	0m2.847s …
```
=> Avoid unnecessary delays in wait_perform()

htslib/sam.h, sam.c
Adds create/update/delete operations to tag:value pairs of the HD line from a SAM header.
=> CUD operations on HD line

bgzip.c
Add --test option
Uncompresses each block and check crc32
=> Bgzip intergity check

bgzf.c
I accidentally added the CRC32 check to the wrong function (inflate_block rather than bgzf_uncompress) back in 44c6a36f2894b45ad6cb491833d27c6a2106410f, meaning it only applied on non-threaded decodes.  This has now been moved. CRC checks are done inside the child threads for extra speed.
=> BGZF CRC checking on decode now also applies when threaded.

tabix.c
=> Add long option --min-shift

faidx.c
=> Rephrase error message in `faidx_adjust_position`

htslib/sam.h
=> Add documentation to sam_read1 and sam_write1 functions

htslib/sam.h
=> Improved description on bam1_t structure.

sam.c
Fix https://github.com/samtools/samtools/issues/987
=> Improve overlap detection heuristic.

bgzf.c, bgzip.c, htslib/bgzf.h, test/test.pl
=> Fix bgzip index creation when using multiple threads

vcf.c
Fixes https://github.com/samtools/bcftools/issues/707
=> Don't create TBI indices for BCF files

cram/cram_index.c
It's not foolproof, but it spots most cases of unsorted data.
What I'm not checking is the ref ids themselves are sequential, but I am unsure if that is a valid restriction.  Statistically speaking unless we have millions of references it's very likely we'll trigger quickly on the same ref occurring twice in a row with out of order positions.
=> Make "samtools index" fail on non-position sorted CRAMs

htslib/hts_log.h, textutils_internal.h
Not sure if these days you prefer trivia like this as a PR or committed straight to **develop**…
=> Silence -Wstrict-prototypes warnings

htslib/tbx.h, tabix.c, tbx.c
=> Display an error message about the compression mismatch

cram/cram_decode.c
Specifically the MD string calculation optimises poorly.  The total impact on cram decoding speed is around 10%.  (For reference decode_md=0 is only around 7% further saving.)
=> Speed up cram_decode_seq.

htslib/vcf.h, vcf.c
See also
https://github.com/samtools/bcftools/issues/736
https://github.com/samtools/bcftools/issues/817
https://github.com/samtools/bcftools/commit/db2e2b66f4164e650d627297375c60dfdcca7ad6
=> Add new variant type VCF_OVERLAP

htslib/kstring.h
KS_EMPTY     -  Initializer for structure assignment
ks_init()    -  Initializer for pointed-to kstrings
ks_expand()  -  Increase kstring capacity by a given amount
ks_reset()   -  Reset kstring length to zero
ks_free()    -  Free the underlying buffer
ks_destroy() -  Free both the buffer and the pointed-to kstring
Brings together some kstring-related macros and functions that have been added in various other parts of the code-base.
=> Add extra kstring functions

sam.c
Certain records (for example one with a CIGAR that contians only I operators) could be added to the overlap hash table without being pushed on to the pileup list.  This would result in the hash table pointing to invalid data after the bam structure is reused on the next call to bam_plp_push().
Fix this by delaying the call to overlap_push() until it is known that the record will be added to the pileup.
Fixes #852 (overlap_push assertion failure)
=> Fix possible stale pointers in mpileup overlap hash

bgzf.c
It was possible for bgzf_mt_reader() to catch its own signal on mtaux_t::command_c, resulting in a deadlock as the signal was not delivered to the thread that it was intended for.  This recently manifested as a problem with the Appveyor tests, which were frequently failing to complete due to a random lock-up when reading a BAM file in multi-threaded mode.
Fix by adding extra values for mtaux_t::command, which can be used to detect when  mtaux_t::command_c needs to be re-signalled.
=> Improve BGZF multi-thread command state machine

htslib/sam.h, sam.c, test/sam.c
I needed this function for bambi, so it seemed sensible to add it to htslib
=> Added bam_set_qname() function

header.c
If there are duplicate entries in the `sam_hdr_t::target_name` of a BAM file, one or more of the ref stubs end up with a header line type null pointer. Although, symptoms of this issue appear earlier in the call hierarchy ([sam_hrecs_refs_from_targets_array](https://github.com/samtools/htslib/blob/5162f01532d10514a44b76af6e41f205aa8b646b/header.c#L1018) and [sam_hrecs_update_hashes](https://github.com/samtools/htslib/blob/5162f01532d10514a44b76af6e41f205aa8b646b/header.c#L216)), a check for consistency and validity of the internal header data is still necessary in `add_stub_ref_sq_lines`.
Fixes oss-fuzz 18148
=> Replace assert with an error mesage and return

vcf.c
The success of `strto{l,ll,d}` methods is rarely checked. However, when the out-of-range parsed value is subsequently used in arithmetic operations, it could lead to an overflow.
Fixes oss-fuzz 18149
Fixes oss-fuzz 18164
Fixes oss-fuzz 18193
=> Prevent overflowing of string parsed integers in VCF files

hfile_libcurl.c
`select` on Windows is unreliable as a sleeping mechanism, as it spuriously returns -1 before timeout, without setting `errno`.
https://curl.haxx.se/libcurl/c/multi-double.html
=> Fix waiting mechanism on Windows

hts.c
We only read 1Kb, so we may not get all the way through the SEQ and
QUAL fields.  If we've not finished counting the columns in our 1Kb of
text then we permit SAM to be recognised on the first 9 columns
instead of all 11+.
=> Fixes a bug in hts_detect_format on unmapped long read SAM.

NEWS
=> Update the NEWS file

Makefile
Pull request to mark the milestone.
=> Bump shared library version to 3

header.c
Remove the unnecessary updates of the `sam_hdr_t::target_name` and `sam_hdr_t::target_len`.
The calling method `sam_hdr_update_line` checks whether the name or length of a reference has been changed and only then triggers the external array entry update.
Fixes #1007
=> Update target arrays only when name or length is changed

cram/cram_decode.c
To help diagnose #1038 by reporting which chromosome and region is affected.
=> Improved CRAM error messages in cram_decode_slice

test/fieldarith.sam
Only one recently added file.
Spotted while doing some round-trip testing.
=> Fix test data to have "=" for RNEXT when matching RNAME.

textutils_internal.h, vcf.c
1. `vcf_parse` was split into dedicated parsing methods `vcf_parse_filter`, `vcf_parse_info`, along the already present `vcf_parse_format`.
2. Some calls to `strtol` have been replaced with `hts_str2int`.
3. Calls to `strtod` have been replaced with `hts_str2dbl` (by @jkbonfield).
A 2% speed improvement has been observed on a 1812841 record Human genome VCF file with 2500 samples.
Still to do:
Implement other speed gains.
=> [WIP] VCF parser improvements

NEWS, hts_internal.h, htslib/vcf.h, sam.c, synced_bcf_reader.c, test/test-vcf-api.c, vcf.c
Similar to `sam_open_mode` for variant call files.
Fixes #1095
=> Implement vcf_open_mode method

sam.c
bam_aux_get sets errno=ENOENT when we look for a tag and don't find it.  Personally I think this is a misfeature, but it's part of the
documented API so we can't change that. Instead we undo the damage as not finding the tag is not an error.
The consequence of samtools/samtools#1296 is that now all almost errors found while decoding a BAM file get converted to "No such file or directory" prior to this commit.
=> Don't trash errno in bam_tag2cigar.

Makefile, bgzf.c, cram/cram_decode.c, cram/cram_encode.c, cram/cram_io.c, cram/cram_stats.c, hfile.c, htslib/hts.h, htslib/khash_str2int.h, htslib/thread_pool.h, htslib/vcf.h, kstring.c, sam.c, tbx.c, thread_pool.c, vcf.c
May or may not solve the problems in https://github.com/samtools/samtools/issues/1293.  We can't reproduce that exact scenario, but have found others and it's unclear if we're fixing the same problem or not.
The issues fixed here are mainly for error recovery; what happens if we fail parsing due to malformed SAM or receive and external source of error (I/O, memory, etc).  Various deadlocks and/or race conditions could occur, sometimes leading to crashes too.
=> Sam threading improvements

vcf.c
In #498 I removed the warning:
vcf.c:3030:26: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
d->allele[i] = tmp.l;
by storing a pointer starting from a fixed "" string, and later on
subtracting it back again to get the length.  While that works, it's
pretty icky and I think undefined behaviour as it uses pointer
arithmetic outsides the bounds of an object.  (In reality it's fine on
all modern systems as the days of segmented pointer archictures are
long gone.)
Instead I now cast the length into a char* as the size of allele is
never going to grow beyond the size of a pointer, and then cast back
prior to adding to the d->als pointer.
[Ideally we wouldn't need these shenanigans at all and keep it in index
space instead of pointers so growing memory doesn't …
=> Improvement (personal preference) to previous C99 fix.

vcf.c
This is mainly by speeding up bcf_dec_typed_int1_safe, but also by
some other code in there to streamline the function and keep the
loops tighter.
The effect on clang is slight.  On gcc9 reading an uncompressed BCF
file can be a bit faster (up to 15% on one file), bringing the speed
of gcc and clang to similar speeds when using -O3.  (Gcc -O2 is still
noticably poorer than clang -O2 on this test though.)
Examples on CHM1_CHM13_2.1.gatk_raw.gvcf.ubcf and gcc9 -O3.
Before:
1549.79 msec task-clock                #    0.999 CPUs util
5549055377      cycles                    #    3.581 GHz
16764915993      instructions              #    3.02  insn per
After:
1345.83 msec task-clock                #    0.999 CPUs util
4806341286      cycles                    #    3.571 GHz
13942053336 …
=> Sped up bcf_check_record.

hts.c
Unmapped placed reads can be skipped by an iterator read, when they fall at the beginning of a BGZF block, because they are not added to the linear index. However, the meta-bin from the bin index records the presence of unmapped reads and can indicate a potential change of the `min_off` value.
The logic for adjusting the `min_off` is to look backwards in the linear index until a smaller offset value is found. This new value is then compared to the smallest starting offset of a chunk inside the respective bin. The largest of the two values is then chosen as the new `min_off`.
Replaces #1155 
Fixes #1142
=> Adjust the min offset of a bin when unmapped placed reads detected

sam.c
Replaces #1154
See also #1153
It does this by the addition of a separate variable to do the boolean check on instead of fd->dispatcher itself.  I deemed this easier to understand than overloading the interpretation of fd->h being set plus I'm unsure of the potential failure case in sam_hdr_fill_hrecs where fd->h has been set but we errored before creating the threads.
Also improves error recovering in case of pthread creation failure, avoiding a false pthread_join later.  Thanks to John Marshall for identifying that issue.
=> Fix assumption of pthread_t being a non-structure.

vcf.c
=> Fix memory leak on bad input in vcf_parse_info()

Makefile, test/plugins-dlhts.c, test/test.pl
[A followup to PR #1072, needed to fix #1176: the previous PR causes breakage limited to macOS when the main executable contains a statically linked libhts.a.]
PR #1072 changed plugin linking so that plugins are linked back to the dynamic libhts.so/.dylib, to facilitate use when libhts is itself dynamically dlopen()ed with RTLD_LOCAL, e.g., by the Python runtime which uses default dlopen() flags which on Linux means RTLD_LOCAL.
This broke plugin loading on macOS when opening plugins in an executable in which libhts.a has been statically linked, as there were then two copies of the library globals (notably _hfile.c_'s `schemes`), one from the executable's libhts.a and one from the plugin's libhts.NN.dylib. (The Linux loading model does not suffer from this issue.)
The default dlopen() flag …
=> Don't link plugins with libhts.dylib on macOS (correction to PR 1072)

probaln.c
The changes are:
- Replace a lot of the repeated set_u macro usages that go from k to
{u, v01, v10, v11} with pointer increments instead.  This rather
obfuscates things as the difference between v01/u and v11/v10 (+/-3)
is now hidden (but see PROBALN_ORIG comment below).
- An attempt at manual ordering of code to avoid as many instruction
latency issues as possible.  Mostly compilers do this already, but
some combinations benefit here.
- Cache and reuse of variables computed during the previous loop
iterations.  This can have a big impact, but again whether or not it
was already done for us is compiler specific.
- Removal of some loop invariants (ideally already done for us, but
safer to do it ourselves).
- Perform the bi (backwards) rescaling during the backwards
calculation loop instead …
=> Further optimisations to probaln_glocal.

INSTALL, configure.ac
See the author's [blog entry](https://daniel.haxx.se/blog/2020/11/04/the-journey-to-a-curl-domain/) and [tweets](https://twitter.com/bagder/status/1326655100836859904) in which he asks (a bigger player than htslib!) to update accordingly.
=> Update links to curl project website [minor]

cram/cram_codecs.c, cram/cram_io.c, htscodecs_bundled.mk
A few minor issues thanks to Google's OSS Fuzz.
Also spotted a missing dependency in the Makefile, so fixed that while editing (in a separate commit).
=> Cram3.1 fuzzing fixes

hts.c
The linear index can be used to fine tune the minimum file offset from where a targeted read starts. However, the linear index does not cover unmapped reads, so a solution was constructed to look backwards for a valid offset which is guaranteed to cover the unmapped reads. 
The problem arose form a heuristic that was employed when no other offset value was found in the backwards search. The current code uses the starting offset of the first chunk of the first matching bin from the bin index, in the assumption that this chunk will cover the starting coordinate of interest. However, this assumption was not always met, so the current fix reverts to setting the minimum offset to the corresponding bin `loff` value, which was the initial value of the minimum offset, before it was updated by the …
=> [index] Fix the update of the minimum offset, when unmapped reads are present

htslib/sam.h, realn.c
The flag passed to sam_prob_realn can now contain platform data, encoded via the htsRealnPlatform enum.
It also automatically selects long-read parameters if the read length is bigger than 1kb, but otherwise it defaults to the same parameters as before.
This helps bcftools mpileup call SNPs on PacBio CCS reads.
=> Permit platform specific BAQ parameters.

LICENSE, bgzf.c, hfile_gcs.c, hfile_s3.c, hts.c, htslib.mk, htslib/hfile.h, htslib/hts.h, htslib/sam.h, realn.c, synced_bcf_reader.c, test/test-vcf-api.c, test/test_introspection.c, vcf.c, vcfutils.c
=> Summer 2021 Release Copyright Updates.

NEWS, bgzip.1, bgzip.c
Added missing --keep and --test options to man page. Updated NEWS file.
=> Update to bgzip man page.

vcf.c
… as in https://github.com/samtools/bcftools/issues/1575
=> Warn if spaces instead of tabs are detected to prevent confusion

htslib/sam.h
I think this needs to iterate through the records, as it is just passing the index right now.
=> Update docs: Iterate through bam1_t records

Makefile, cram/cram_decode.c, cram/cram_encode.c, cram/cram_io.c, vcfutils.c
Ready for the February 2022 release.
=> Update copyright dates for February 2022 release.

vcf.c
This commit will only result in warnings printed on stderr. This
should be improved to propagate the error all the way up to the
caller and let it decide whether to throw an error or proceed despite
the error.
See
https://github.com/samtools/htslib/issues/1065
https://github.com/samtools/samtools/issues/1573
=> Check for incorrect contig names and INFO/FORMAT tags

NEWS
(To merge when ready for release candidate.)
=> NEWS updates for 1.15.

cram/cram_io.c, test/test.pl
Also adds an auto-mode embed_ref=2 test.
=> Fix (un)lock bug and memory leak introdued in commit 9562aeba

configure.ac, cram/cram_external.c, hfile_s3.c, hts.c, hts_expr.c, htscodecs_bundled.mk, htslib-s3-plugin.7, htslib/bgzf.h, htslib/cram.h, htslib/hfile.h, htslib/hts.h, htslib/hts_expr.h, htslib/knetfile.h, htslib/kstring.h, htslib/sam.h, sam.c, test/sam.c, test/test.pl, test/test_expr.c, test/test_mod.c, version.sh
Readying for the next release.
=> Summer 2022 Copyright Corrections.

NEWS
=> NEWS additions for Summer 2022 Release.

.cirrus.yml, htslib/hts.h, htslib/vcf.h, vcf.c
Changes to have description of error values through bcf_strerror method.
=> bcf_strerror method to get description of error code

cram/cram_io.c
This function is about 7x faster than before, which speeds up low-depth CRAM decoding by around 10% of so.  Obviously the time spent in this function is constantly regardless of depth, so the deeper the data the less important the speed of this becomes.
The two main improvements are:
1. Drop toupper_c and replace it with "c & ~0x20".  This works for ASCII, and we already have far too many places with char lookup tables e.g. converting ACGT to 0123 that we're not going to work on mythical EBDIC systems anyway.
2. Remove the continuous white-space check.  We exploit the knowledge that the FASTA format must have white-space only at the end of lines. The fai index can't work if this isn't true and I've already tested that samtools faidx fails to query correctly if we have whitespace …
=> Speed up load_ref_portion.

bgzip.1, bgzip.c, cram/cram_encode.c, cram/cram_io.c, faidx.c, htslib/faidx.h, htslib/vcf.h, tabix.1, tbx.c, test/sam_filter/filter.tst
Update copyright for winter release, 2023.
=> January 2023 release copyright update

vcf.c
This is an initial test framework as suggested by https://github.com/samtools/htslib/issues/1543#issuecomment-1373575003
@daviesrob is this what you had in mind?
=> Initial test framework for #1543 (to be continued)

htslib/kseq.h
Original PR by Pall Melsted, with only manual merging and one trivial bug fix by myself.
Fixes #1579
=> Backport attractivechaos/klib#78 to htslib.

bgzf.c, configure.ac, cram/cram_decode.c, cram/cram_index.c, cram/cram_structs.h, hfile_s3.c, hts_probe_cc.sh, htslib/bgzf.h, htslib/faidx.h, htslib/kseq.h, htslib/vcf.h, probaln.c, tbx.c, test/base_mods/base-mods.tst, test/test-bcf-sr.c, test/test-bcf-sr.pl, test/test-regidx.c, test/test-vcf-api.c, test/test.pl, test/test_bgzf.c, test/test_mod.c
Polishing copyright for summer.
=> Summer 2023 Copyright Update.

NEWS
=> NEWS updates for pending release

cram/cram_io.c
For simplicity and to remove a lot of conditionals the code using mutexes is always used irrespective of whether we are multi-threading.
For example cram_get_ref starts with:
pthread_mutex_lock(&fd->ref_lock);
The mutexes themselves however are only initialised when using cram_set_voption with CRAM_OPT_NTHREADS or CRAM_OPT_THREAD_POOL option.  Attempting to lock an uninitialised mutex has undefined behaviour.
On linux this does nothing as A) we're not checking the return value from the lock functions anyway (the only meaningful error is not-initialised) and B) we calloc the structure and a blank mutex is the basically the same as initialising it.
Under MSVC however this leads to crashes. So moved both init and destroy into the cram_dopen function.  Note this adds an additional destroy …
=> Always do the CRAM mutex lock/destroys.

NEWS
First draft of htslib news in preparation for a release.
=> Winter News 2023

NEWS
No code changes, just picking up the tagged release.
=> Update htscodecs to v1.6.0

annot-tsv.1
Man update for change 1709. Updated with a sample usage.
=> man update for -a option

hts.c
=> Add check for .gzi when determining whether to rebuild the fai index.

bgzf.c, cram/cram_io.c, hfile.c, hfile_s3.c, kstring.c, sam.c, sam_mods.c, test/pileup.c, test/sam.c, textutils_internal.h
Updates the copyright for spring 2024.
=> Spring 2024 Copyright Update.

NEWS
=> Add NEWS ready for 1.20 release

Makefile, configure.ac, faidx.c, hts_expr.c, hts_probe_cc.sh, htslib/bgzf.h, htslib/cram.h, htslib/hts_defs.h, htslib/kstring.h, sam_internal.h, test/test_bgzf.c, test/test_kstring.c
=> Copyright updates for summer 2024.

vcf.c
When this is merged, this problem will go away https://github.com/samtools/bcftools/issues/2389
=> Recognize T > A[chr15:12345[ breakend type

cram/open_trace_file.c
Not updating `len` in all cases, combined with `strncpy()` padding out its destination with NULs, could result in an overflow of the output `path` buffer.  This could also happen if it was asked to expand a path with a negative or large enough value in a `%s` directive (e.g. `%-2s`).
Fixed by adding extra validation, and using `memcpy()` which only touches the bytes we want it to.
=> Fix possible buffer overruns in expand_path()
